### ISSUE TITLE
Cold/Flu: Submitted Forms View and Form Functions (FE&BE)

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1007]
**User Story**
A user should be able to edit their response to the form. There should be a page showing the user their submitted form. 

Once an edit is submitted, the site Admin(s) should be notified via email. User changes should be captured in the email notification.

**Tasks**
- [x] Create Submitted Forms view / page
- [x] GET submitted forms data from backend API
- [x] Edit new forms data to backend API
- [x] DELETE form record (mark as deleted in database, no deletion of record) [#1025](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1025)
- [ ] ~Revision history in email notification (can be triggered by onChange or value audit when form is submitted)~

**Acceptance Criteria**
- Logged in user can see their submitted form(s)
- User can view and edit their submission (Edit and Delete)
- Once changes have been submitted, the site Admin(s) are notified via email
- Edits to a form is summarized in an email.

**Comment by MeghanStothers** [comment]
history: available for enterprise edition not the open-source version. May interfere with existing workflow.

**Comment by ca-liu** [comment]
Hi @bhumin-fw, @EduardoRamirezBC,

I have updated the ticket to remove the history log requirement on the form submission. Instead, the changes will be captured in the email, change history does not need to be stored in the database.

Changes can be triggered by form onChange event triggers or when the form is submitted and a value audit is conducted (=== match).

Thank you for looking into this issue!

**Comment by MeghanStothers** [comment]
@ca-liu Thanks! I have looped Stella into this thread so she's aware. Can you confirm that, simply put, the updated requirement is the program area will get notified of changes (such as the # of clinic attendees) by email? Does the requirement/email notification change when when the form is "open" or "closed"?

**Comment by ca-liu** [comment]
Hi @MeghanStothers ,

Thanks for checking! Correct, the updated requirement is to:

- Notify the site admins of any changes submitted by the registrant via email
- Email notification will be enabled after the registration window closes (3 weeks after intake form opens)
- The email notification should outline what was changed on the form. This can be captured using JavaScript (onChange) event trigger or form value audit onFormSubmit.

Please let me know if that makes sense; happy to provide additional information if required.

**Comment by EduardoRamirezBC** [comment]
Emai; notification only happens when its closed

**Comment by bhumin-fw** [comment]
@ca-liu 

Thanks for checking! Correct, the updated requirement is to:

- Notify the site admins of any changes submitted by the registrant via email
**Does this email contain predefine template, Like User XXX made change to Worksite xxx?**
- Email notification will be enabled after the registration window closes (3 weeks after intake form opens)
**From where we will fetch this details, Is it pre-defined dates? or we have to calculate any duration at the time of form submission?**
- The email notification should outline what was changed on the form. This can be captured using JavaScript (onChange) event trigger or form value audit onFormSubmit.
**If we are sending what was changed on the form in the email. Do we still need to send separate email as mentioned on first point? or first and this(3rd) point to the same email.**

I have a favor to ask you,
You did mention "onChange" to identify changes. In core javascript, we are using it to identify update values in the form. In the FormIo that handles on FormIo repo/CDK.
I need to explore the FormIo document to identify how to collect changed form data in an execution context where I can modify code. If you have any idea or document link handly, Could you please share it with me?

**Comment by ca-liu** [comment]
Hey @bhumin-fw 

Great questions! Please see clarification points below:

> - Notify the site admins of any changes submitted by the registrant via email
> **Does this email contain predefine template, Like User XXX made change to Worksite xxx?**

Correct. Please see email template below.

> - Email notification will be enabled after the registration window closes (3 weeks after intake form opens)
> **From where we will fetch this details, Is it pre-defined dates? or we have to calculate any duration at the time of form submission?**

Good point. We will make the form dynamic and not static to 3 weeks as things may change. Created ticket #1023 to allow Site Admin to open/close the registration form. The open/close will only trigger email notifications, the form will remain open.

> The email notification should outline what was changed on the form. This can be captured using JavaScript (onChange) event trigger or form value audit onFormSubmit.
> **If we are sending what was changed on the form in the email. Do we still need to send separate email as mentioned on first point? or first and this(3rd) point to the same email.**

You got it, please see email template below. I hope this helps clarify for what we are looking in an email template.

**Email Template for changes when the intake is CLOSED**
Subject: Cold/Flu: {contacts.fName} has made a change to their clinic registration
Body:
{contacts.fName} {contacts.lName} has made the following changes to their clinic registration form on {lastModifiedDateTime}:
- {form field name} was changed from {old value} to {new value}
- {form field name} was changed from {old value} to {new value}
- {form field name} was changed from {old value} to {new value}

Click here (link to the registrations.registrationId) to view the revised submission.

**Email Template for new registrations when the intake is CLOSED**
Subject: Cold/Flu: {user} has submitted a new clinic registration
Body:
{contacts.fName} {contacts.lName} has submitted a new clinic registration on {submittedDateTime}.

Click here (link to the registrations.registrationId) to view the submission.

**Comment by ca-liu** [comment]
@bhumin-fw  please see notification email template above.

**Comment by bhumin-fw** [comment]
@ca-liu This looks good. Thank you.

**Comment by Stella-Archer** [comment]
waiting for API/ endpoints

**Comment by bhumin-fw** [comment]
To test please check below points only, other detail will be test in different tickets:

1. you should be able to submit form.
2. you should be able to edit submitted form.
3. you should be able to see submitted forms in "Submitted form" tab along with "Edit" an "Delete" button. (delete functionality will be test separately in 1025 ticket)

**Comment by ayushdamani** [comment]
Thank you for the instructions @bhumin-fw !

Acceptance criteria met:
- I was able to submit the form.
- I was able to see the submitted forms in "Submitted form" tab along with "Edit" an "Delete" button.
- I was also able to edit the submitted form.

![Screenshot 2023-05-03 113305.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/12f3fc6e-0c63-43cf-b2c0-1d9868bec497)

**Comment by Stella-Archer** [comment]
worked perfectly - PO approved & tix closed
