### ISSUE TITLE
Cold/Flu: Logic - one registration per primary contact

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1016]
**User Story:**
As a registrant, I can only register once per year. If I have already submitted a request for that year, I must edit my submission instead of submitting in another one (this is how the db is built)

As a site Admin, this rule does not apply.

**Tasks:**
- [ ] Add conditional rendering logic to isAdmin = false roles
- [ ]  Have a popup to say that the user has already registered, if their userId is in the Registration table primaryContactId row

**Acceptance Criteria:**
- [ ] Validate that logic is true. Cannot submit another form if one is already submitted for that year

**Popup message:**
Header: "We have received your response!"
Paragraph: "You have already submitted a request for {year} cold and flu clinic. If you need to edit your submissions, please go to the Submitted Forms tab to make any changes.

Please contact the Cold and Flu team (cold.flu@gov.bc.ca) if you have any questions. Thank you"

**Comment by fazil-ey** [comment]
How do we know which year the registrant is submitting the form in? 
Is there an approver in this form?

**Comment by EduardoRamirezBC** [comment]
@NassNK @ca-liu confirm with Heather if clinic registration can happen in the same calendar year?

**Comment by ca-liu** [comment]
> @NassNK @ca-liu confirm with Heather if clinic registration can happen in the same calendar year?

Hey @EduardoRamirezBC,
Registration will be open for the calendar year only. 

Maybe I'm not understanding the question. Please let me know if you require further clarification.

**Comment by EduardoRamirezBC** [comment]
Sorry.. I meant to ask..  if clinic registration could happen **twice** in the same calendar year? We are assuming no, but wanted to confirm.

**Comment by ca-liu** [comment]
> How do we know which year the registrant is submitting the form in? 
> Is there an approver in this form? 
> 

Hey Fail, there is a row in the registrations table indicating the year of registration.

Would be something like Date.today() and Date.timeNow()

**Comment by ca-liu** [comment]
> @ca-liu Sorry.. I meant to ask..  if clinic registration could happen **twice** in the same calendar year? We are assuming no, but wanted to confirm.
> 

Gotcha! No, registration is once per year.

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov @mikeshitelus
endpoint: GET <please provide endpoint from your end Mike>
input: <email> of primary contact
output: return registration object. only basic details required no join needed as we only need data to check that this primary contact has registration or not.

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov that's quick. Thank your for you prompt update on it. By Thursday I'll work on it and let you know if any query. But i'll test it by end of the day today only :).

**Comment by bhumin-fw** [comment]
@ayushdamani 
Here, If you are admin you are allowed to go ahead and fill the form. If you are not admin then you will see popup (If your logged-in email is added in primary contact for any worksite registration) saying above content and when you click on "ok", it will redirect you to form list page.

When you open form it will open form for any user and you can select ministry and worksite without any restriction.
when you click on "worksite or registration" button in the form then it will trigger this validation check.

Feel free to add your query or suggestion is any. If you want to jump on a call just let me know So I can find some slot in this afternoon for the same.

**Comment by bhumin-fw** [comment]
One more point, ticket [#1090](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1090) auto populate primary contact information. if you just check it along with this ticket that will be really helpful.
Made some change along with this ticket. 
If admin primary contact are editable, if regular user it will pre-populate primary contact information but not editable.

**Comment by ayushdamani** [comment]
@bhumin-fw and I reviewed. Thank you so much for your time, Bhumin!

The ticket is verified as working ✔️
