### ISSUE TITLE
Cold/Flu: Form fields format/validation (phone, email domains, etc)

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1017]
**User Story**
As a registrant, the form should prevent me from entering wrong input formats and alert me if the the input fails regex.

Validation should be built in front end and back end

**Tasks:**
-  [x] Phone field 
Regex ex: ^(\+\d{1,2}\s?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$
- [x] Email (should be @gov.bc.ca)
- [x] Number of employees (positive, not zero)
~- [ ]  Free text should do sql-injection and other security checks~ automatically handled by formsflow

**User Acceptance:**
-  [ ] Data is validated before form submission.

**Comment by Stella-Archer** [comment]
Hi @ca-liu 
1/ Phone field has validation on format 
2/ email is not restricted yet. is there domains other than @gov.bc.ca that should be included? We have a list of IDIR groups with different domains that we use for the telework agreement we could use here
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/44af728b-8f33-4dec-94d4-753b4b6c5145)
"gov.bc.ca",
  "freshworks.io",
  "ca.ey.com",
  "inbcinvestment.ca",
"bcassessment.ca",
"bc-ebc.ca",
"bcehs.ca",
"bcest.bc.ca",
"bcfarmreviewboard.ca",
"BCFerryCommission.ca",
"bchumanrights.ca",
"bciif.ca",
"bcldb.com",
"bcliquorstores.com",
"bcrcf.ca",
"bcspp.org",
"bcucipp.org",
"crtbc.ca",
"cullencommission.ca",
"cupsa-aspc.ca",
"destinationbc.ca",
"destinationbc.travel",
"eaat.ca",
"elections.bc.ca",
"healthlinkbc.ca",
"iiobc.ca",
"justicebc.ca",
"lrb.bc.ca",
"obcctc.ca",
"paab.bc.ca",
"patientcarequalityreviewboard.ca",
"ptboard.bc.ca",
"robsonsquare.ca",
"seniorsadvocatebc.ca",
"surfacerightsboard.bc.ca",
"tourismbc.com",
"ticorp.ca",
"workbc.ca",
"wao-bc.org",
"eao-bc.org",
"wcat.bc.ca",
"royalbcmuseum.bc.ca",
"rcybc.ca",
"lngbuybc.ca", 
"eabtribunals.ca",
"wao-bc.org",
];

var bcGovDomainError = 'Email address must be a bc gov email address';

**Comment by ca-liu** [comment]
Hi @Stella-Archer ,

Thank you for testing this out.

1. Phone - perfect thanks!
2. Email - good point, please accept the email domains from your list.

Curious: what if we just rejected @gmail, yahoo, Hotmail, outlook? We just don't want to make sure that it is a valid email and that the email is not a personal email address.

Please let me know your thoughts. Thanks!

**Comment by Stella-Archer** [comment]
For telework we went with a restricted list of known/researched BCPS domains as the list of dodgy public domains could be endless and emails send anywhere outside the gov domain could be a privacy risk. This of course is more an issue with telework which had PDF attachments and included personal information (employee names, home address & numbers)  although Cold and Flu doesn't have a lot of PI it's a still a concern.

**Comment by ca-liu** [comment]
Thanks for the insight. 

Happy to use the list you have in the comment above.

Cheers

**Comment by chriscaldwell-psa** [comment]
Email domains have been set to a predefined list and number of employees validation has been set to a min of 1. This ticket can be tested.

**Comment by ayushdamani** [comment]
Tested and verified:
- Phone: Working
- Email: Working
- Number of employees: Working

Acceptance criteria met ✔️

![no of employees.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/16f27030-61c8-4a91-be1b-af02aeade3bf)
![email.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/cf69ea22-f127-4537-9522-f918b00337ba)

**Comment by Abuchana** [comment]
@Stella-Archer Ayush tested, over to you for PO review. Might be linked to new ticket #1087...?

**Comment by Stella-Archer** [comment]
this is working great :

- Phone: working, doesn't validate if not correct character & format
- Email: Working for .gov .bc.ca domain and test on 'elections.bc.ca' domain worked as well, but public domains did not -YAY
- Number of employees: Working, serves up error if '0'
@Abuchana @MeghanStothers I know we want to amend the email label to "work email" is this in another ticket?
PO approve for requirements of this ticket and am closing

**Comment by Stella-Archer** [comment]
I've checked in with Heather and have her approval to close
