### ISSUE TITLE
Cold/Flu: Edit Ministries List View

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1020]
**User Story:**
As a site admin, I would need to update and mark inactive ministries as the wider GOV changes.

Mockup:
https://bcgov.sharepoint.com/:b:/r/teams/03991/Shared%20Documents/Cold%20and%20Flu/3_Design/Mockups/Ministries.pdf?csf=1&web=1&e=jABOFR

**Tasks:**
- [ ]  Create Ministries view (FE)
- [ ]  Create Ministries activate/deactivate functions (FE) - onClick trigger
- [ ]  Create Ministries endpoints (BE)

**Acceptance Criteria:**
- [ ] Page for ministries is only viewable by site admin
- [ ] Sort criteria is met
- [ ] Activate / deactivate buttons working

**Comment by fazil-ey** [comment]
Covered in #738
