### ISSUE TITLE
Cold/Flu: We need to move data from the legacy db for testing

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#1039]
**User Story**
As the form and API developers, we need to have more data in the database for testing purposes. We will move data from the legacy tables into the new tables for this purpose

**Tasks**
- [x] Mike will move data from the legacy tables into the new tables.  
- [x] Bhumin will confirm that this is a sufficient amount of data to complete testing.

**Acceptance Criteria**
- [x] Mike will confirm on this ticket that that the data has been moved.
- [x] Bhumin will confirm that he can see the new data via the API and that it is sufficient.

**Comment by mikeshi-bcgov** [comment]
@DonMoffatt

Data has been transferred or uploaded (from Caleb's spreadsheet) to 3 tables in ODS,  ministries, worksites, and worksite_ministries. Do you want transfer "Contact" to "Contacts" too? noticed there is  no employee_number in the legacy tables

**Comment by DonMoffatt** [comment]
> @DonMoffatt
> 
> Data has been transferred or uploaded (from Caleb's spreadsheet) to 3 tables in ODS, ministries, worksites, and worksite_ministries. Do you want transfer "Contact" to "Contacts" too? noticed there is no employee_number in the legacy tables

Hi Mike,
Given that this is all "dummy data" I think that is fine, along with made-up employee numbers. They just need something to test on.

Don

**Comment by ca-liu** [comment]
> > @DonMoffatt
> > 
> > Data has been transferred or uploaded (from Caleb's spreadsheet) to 3 tables in ODS, ministries, worksites, and worksite_ministries. Do you want transfer "Contact" to "Contacts" too? noticed there is no employee_number in the legacy tables
> 
> Hi Mike,
> Given that this is all "dummy data" I think that is fine, along with made-up employee numbers. They just need something to test on. @ca-liu do you agree? 
> 
> Don

Awesome, thanks so much, Mike!

We do not need contacts at this time, but thanks for asking!

The data loaded to the db will be the 2023 Cold and Flu registration base so it is accurate 🙂.

**Comment by DonMoffatt** [comment]
@mikeshi-bcgov Hi MIke - have you concluded loading test data? If so I will close this ticket.

**Comment by mikeshi-bcgov** [comment]
@DonMoffatt 

Yes, test data  has been loaded to all the tables in ODS, also copied to tables in DWH.

**Comment by DonMoffatt** [comment]
I will close the ticket. Thank you @mikeshi-bcgov

**Comment by ca-liu** [comment]
Thank you very much, @DonMoffatt  and @mikeshi-bcgov !

![Alt Text](https://media.giphy.com/media/GVMhZwYv8U5NK/giphy.gif)
