### ISSUE TITLE
[NAME OF FORM]: Issue description

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1053]
**User Story**
As a non-IDIR user (e.g. employees from Transportation Investment) with a services agreement with PSA to provide influenza clinics, I would need to submit my request to Cold and Flu registration to capture my worksite.

**Tasks**
- [ ] Review options to grant non-IDIR registrants access to the form [Stella / Meghan]
- [ ] Engage developers to map out IAM and how it may impact current database schema
- [ ] Present options to Form Owner (Heather)
-  [ ] Reach decision and implement solution

**Acceptance Criteria**
- Non-IDIR users can have their registration requests added to the Cold and Flu BI report

**Comment by ca-liu** [comment]
April 17: Exploration
Meghan and Stella to review options and understand how credentials / user access will be managed.

**Comment by Stella-Archer** [comment]
For the MVP release we could have Non IDIR client contact the program area who would have permissions to create and edit  request

**Comment by MeghanStothers** [comment]
@ca-liu  As Stella noted above, those non-IDIR users who need access would need to contact Heather/program are and the program area would register the worksite/person.  Do you want to chat about this request or can we close this ticket?

**Comment by MeghanStothers** [comment]
Thanks Caleb. We'll connect with Stella and Heather. I mentioned to Josh that Heather would be connecting with him about content updates - he's all set :)

**Comment by fazil-ey** [comment]
This is not a requirement for this launch. Decision made Apr 27
