### ISSUE TITLE
Cold/Flu: Create a report that can be run regularly for the Line of Business

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#1063]
**User Story**
As the Program Manager for Workplace Health and Safety for this Cold and Flu form, I need a report on the Influenza Database contents that I can obtain whenever I need it.

**Tasks**
- [x] Determine requirements for line of business.
- [x] Choose the appropriate technology for the solution.
- [x]  Build the query and save it in a place where the BI group can find it and run it
- [x] Vet a sample report with the Line of Business (Heather Bishop)
- [x] Notify the BI Group that the script has been created.

**Acceptance Criteria**
- [ ] All tasks are complete.
- [ ] The Line of Business accepts the report.

**Comment by DonMoffatt** [comment]
I am working on the query for the form and will run the results by Caleb and Nass before I show the results to Heather Bishop to obtain her approval.

**Comment by chriscaldwell-psa** [comment]
BP teams report, outside the scope of our  team.

**Comment by Abuchana** [comment]
@DonMoffatt do you know who on the DJ DEV team was going to "build the query and save it in a place where BI group can find it and run it?" Point #3 in requirements? I'm afraid that because this isn't assigned to a dev nobody is working on it...

**Comment by Abuchana** [comment]
@mikeshi-bcgov and @DonMoffatt can you comment on this ticket and let us know what we need to move it forward?

**Comment by DonMoffatt** [comment]
Hi @Abuchana I've had competing high-priority requests, one of which I just finished. I have not forgotten about you, however.

**Comment by Abuchana** [comment]
Thanks @DonMoffatt! We are getting close to the finish line and Heather wants to see what the reports will look like for her and I'm not sure what we need to do to get her that info. Do you need help from anyone...?

**Comment by DonMoffatt** [comment]
I've created a sample report in spreadsheet form and shared it with Caleb for review. The output can be customized according to what Heather wants every time they request it.

**Comment by ca-liu** [comment]
[https://app.zenhub.com/files/439477060/d202a513-3436-4002-9345-1fee79de0332/download](https://app.zenhub.com/files/439477060/d202a513-3436-4002-9345-1fee79de0332/download)

**Comment by Stella-Archer** [comment]
thanks @DonMoffatt @Caleb and @Abuchana I have forwarded the sample report on to Heather. I am meeting with her later today, I will gather initial feedback and set up some time to meet with you directly

**Comment by DonMoffatt** [comment]
The preference on our side is to set up something self-serve as well. I am looking into it and hope to have something set up in the next week or two (it takes time to set up). In the meantime, I will attempt to provide updated reports same-day.

**Comment by Stella-Archer** [comment]
Heather had some feed back - I've set up a meeting to review
a few high level points she's noted:
**Missing elements
-	Phone number
-	Email
-	All info for secondary contact
-	Open/Closed + Justification
-	Team Relocating yes/no
-	And Special Instructions

I think it will also be important to specify which contact info is for PRIMARY contact and which is SECONDARY to avoid confusion.**
She's also sent along report headings from pervious years:

Ministry	Street Number	Address	City 	Province	Postal Code	First Name (Primary)	Last Name (Primary)	Phone Number (Primary)	Email (Primary)	First Name (Alternate)	Last Name (Alternate)	Phone Number (Alternate)	Email (Alternate)	# of Employees	Clinic Type (Open/Closed) 	Justification (Closed)	Relocating (Y/N)	Special Instructions	Registered Date

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/d6f47bcb-fd32-4adc-9096-ff6f47b7b019)

**Comment by DonMoffatt** [comment]
I sent an updated report via email for the team / Heather to inspect. We will discuss it at our 2 p.m. meeting today.

**Comment by Abuchana** [comment]
Caleb: Don would be the point of contact for Heather; should she need support from me, she can reach out to us directly. We have also provided Don with a sample query to display the information that Heather has requested.

**Comment by MeghanStothers** [comment]
@DonMoffatt morning! can you give an update on this ticket? Thanks

**Comment by DonMoffatt** [comment]
We are finalizing the report contents and format before enabling it to be sent automatically, as there is setup with TES that should not be revised to find-tune the report format once it is in place. We would like to do this once before launch. I can provide reports as needed by Heather before this in place. The current plan is that it will be run twice a day. Alison discussed it with Steven.

**Comment by Stella-Archer** [comment]
@DonMoffatt Could you please update this ticket please.

**Comment by Stella-Archer** [comment]
@Don Heather would like to confirm the frequency and process for on demand request

**Comment by MeghanStothers** [comment]
@DonMoffatt  Heather to follow up with you today.

**Comment by DonMoffatt** [comment]
The report generated in the data warehouse was approved for testing by Heather and I have moved it to the reporting server. I have set up the subscription schedule for me to test (it will send me test emails with the report attached). After I am convinced that works I will move the recipient to Cold.Flu@gov.bc.ca (the recipient email address requested by Heather). This should be functioning for their group by midday Thursday May 25 or by Friday morning.

**Comment by MeghanStothers** [comment]
@mikeshi-bcgov @DonMoffatt Morning! I am wondering if one or both of you would be willing to show/share a preview of your reports/reporting work for cold and flu at our sprint demo today? It's at 10 to 10:30. I will drop you an email - thanks a bunch for your expertise and oversight of this key work for the form owner.
