### ISSUE TITLE
Cold/Flu: Delete Clinic Registration Front End

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1067]
**User Story**
As a registrant, if I need to make changes to my clinic registration, I would need to delete the registration and create a new one.

**Tasks**
- Replicate delete link in Draft Forms table. Expected outcome below:
![image.png](https://images.zenhubusercontent.com/63d039ffe477f5df944dbc73/05816756-99d8-46ae-8146-e2d41625000b)

**Acceptance Criteria**
- [x]  Delete button is appended to each row on the Submitted Forms table
- [x]  Delete button removers record from the Digital Journey's database and soft deletes from Cold/Flu database
- [x] Submitted form is reloaded with the record removed from the table (state change)

Reference to ticket #1025

**Comment by iman-jamali-fw** [comment]
@Stella-Archer  @fazil-ey 

Could you please review and confirm the UI changes in this ticket and also clarify how this new delete submitted form functionality is going to be for the existing forms (SL Review, Mat/Pat)? Thank you

**Comment by Stella-Archer** [comment]
@Caleb @iman just to be super clear on this ask; 
After a form is submitted, 
But NOT before it's sent to the ODS, (so while the while registration period is still open)
end users (registrants) need to be able to delete their submission and start an new one?
I'm wondering why they wouldn't just edit their old submission?

**Comment by Stella-Archer** [comment]
just applyng this to cold and flu

**Comment by mikeshi-bcgov** [comment]
@iman-jamali-fw 
Just fixed a bug due to field renaming, could you test again?

**Comment by mikeshi-bcgov** [comment]
@iman-jamali-fw 
I see 8718 and 8719 are marked as deleted

**Comment by iman-jamali-fw** [comment]
@ mikeshi-bcgov
Great, thanks Mike. Can you confirm another one with id of application_id of **1839**? I just deleted it from TEST environment using UI. Thanks

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @ca-liu 
This is ready for testing on the TEST environment. As a regular user, you can submit a cold/flu submission and then you'll be able to delete it under **"Submitted forms"** tab

**Comment by iman-jamali-fw** [comment]
@ca-liu 

Could be because of the cache. Can you please open it on an incognito page to make sure seeing the latest version of the website? 
I can see the delete on test:
![Screenshot 2023-05-01 at 12.10.01 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/82c2a79f-ca65-465e-99b1-14fc62b4803c)

**Comment by mikeshi-bcgov** [comment]
@iman-jamali-fw 
confirm 1839 was flagged deleted as well.

**Comment by ayushdamani** [comment]
Tested and confirmed:
- Delete button appears in the 'submitted forms' tab.
- Delete button removes the record.


![Screenshot 2023-05-01 143759.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/741a7657-e2a6-4926-a839-8c3942771525)

**Comment by ayushdamani** [comment]
Working in the Dev environment as well.
![Screenshot 2023-05-01 144445.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/3f390684-b063-4963-b142-c6281e183cd9)

**Comment by Stella-Archer** [comment]
yes! this worked perfectly ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/2fe56241-a856-4c2d-ae43-2f5f4d1972b8)
PO approved & Closing tix

**Comment by Stella-Archer** [comment]
I've checked in with Heather and have her approval to close
