### ISSUE TITLE
Cold/Flu: User Friendly Output on Report

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#1116]
**User Story**
As a business owner I want to easily understand the whether a clinic is open or closed, and if a team is relocating or not, so that there is no chance of error when passing the report to the contractor.
![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/61e5c6ccd594602905c8af04/95f6bd54-3a39-419b-ad79-8437ccf3a350)

**Tasks**
- [x] Replace 0s and 1s in the Open/Closed column.
- [x] Replace 0s and 1s in the Relocating column with Yes and Nos. 
- [ ] Replace data in the Deleted_Ind field with a date. 

**Acceptance Criteria**
- [ ] Client is able to read the report without interpreting the column entries.

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
You need to update schema to support string value in above mentioned columns and let me know, so I can start sending string value again.
Let me know if you have any query here.

**Comment by DonMoffatt** [comment]
Hi @mikeshi-bcgov I consulted Karla (our data architect) and the rest of the DIO team before talking to @Stella-Archer yesterday. I will update the schema table in a moment. We'd prefer it to be changed on the form side. Hopefully this is the last change. Thanks for your patience.

**Comment by mikeshi-bcgov** [comment]
@DonMoffatt  Thanks, Just see your updates. Wondering if the values will be YES/NO, TRUE/FALSE, would varchar(10) enough instead varchar(50)-:))?

**Comment by DonMoffatt** [comment]
@mikeshi-bcgov  I changed the table entries for these fields to varchar(10).

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw @DonMoffatt

Sounds good, thanks both. Will make the change, and will let you know once done.

**Comment by mikeshi-bcgov** [comment]
@DonMoffatt 
Schema updated on DWH DEV, data transferred from ODS too.

@bhumin-fw 
Endpoints refreshed to sync with schema changes. No format change for post, however better to test scenarios in case something off-:)).

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
I did update type of field on form. boolean to string for both field.
you can change post format from boolean to string for both fields is_closed and relocating.

Let me know your thought here. (on form it reduce some script to convert value to boolean)

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 
data type has been changed to "string" on Endpoints.

**Comment by MeghanStothers** [comment]
Bhumin to move to test.  Mike can confirm the test is successful and ask Don to send a final screenshot of the final report.

**Comment by bhumin-fw** [comment]
@Stella-Archer 
Setting "No" as default value for "relocating" here. 
let me know your thought here?

Note: In ticket [#1103](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1103) we have tested it with default blank value.



cc: @mikeshi-bcgov

**Comment by Stella-Archer** [comment]
@Bhumin relocation should be either "Yes" or "No"
@DonMoffatt could you please met with Heather and confirm the report is now meeting her needs

**Comment by bhumin-fw** [comment]
@Stella-Archer correct relocation will be "yes" or "no" only.
I have setup "no" as default value in it (earlier it was blank so). that's the only point which I want to share with you for this ticket. 
because earlier in ticket 1103 we have set that value to blank ("").

**Comment by Stella-Archer** [comment]
we don't want a default value for users as they usually don't relocate in the time span but we do want them to notice & specify

**Comment by bhumin-fw** [comment]
@Stella-Archer In that case no change need to update from Form side. we are good.
Relocate field will have "Yes" or "No" as value and it is a required field. that's perfect.

**Comment by MeghanStothers** [comment]
Bhumin to check the values on the PSA side to verify this has been fixed and report to Mike if successful.

**Comment by DonMoffatt** [comment]
Good morning - there is still the matter of the Deleted_Ind field. I can change the column name in the report, but we need to populate it with dates (where appropriate). I will then run the report and we can sign this off.

**Comment by MeghanStothers** [comment]
Waiting for Bhumin and mike - they're working on change

Next steps:
1) Heather will need to sign off on a final report
2) Don to submit ticket to Telus on Thursday

**Comment by Stella-Archer** [comment]
Oh and @DonMoffatt  could you update this one too? THX

**Comment by Stella-Archer** [comment]
Heather says this it looking great
PO Approved and closing 
Thanks All!
