### ISSUE TITLE
Cold/Flu: Closed (Admin ONLY) period July 14 - December 31

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1119]
**User Story**

“As a Cold and Flu form administrator I want close the form to users after July 14 so I can be aware of and manage last minute clinic requests

**Tasks**
* [ ] Closed form in Digital Journeys on July 14 to all users except those in the ADMIN group
* [ ]  ADMIN can access or edit/add/delete
* [ ]  Regular users can view their existing submission
* [ ]  Regular user can NO longer edit, add or delete their forms #1071

**Comment by fazil-ey** [comment]
Dev work required for AC 2 & 3.

**Comment by fazil-ey** [comment]
All AC is completed. No further work required
