### ISSUE TITLE
Cold/Flu: Only allow a user to select one ministry UX/UAT Testing feedback

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1144]
**User Story**
“As a user registering for a clinic I want to be sure the Ministry I first selected in the "Your ministry or organization" field (1) appears in the 'Registration information' (2) section so I can not send conflicting information to the contractor booking my clinic.” 

**Tasks**
* [x] pre-populate the  "Select Ministry" (2) field in the 'Registration information' section with selection from "Your ministry or organization" field (1)
* [x] 'grey out /make un-editable the pre-populated information in  "Select Ministry" field
* [x]  change the label on the "Select Ministry" field to "Ministry or organization" 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/f4ea2169-4495-4f92-b9e0-395633a2e027)

**Acceptance Criteria**
users can not book under 2 different ministries/orgs

**Comment by bhumin-fw** [comment]
@Stella-Archer 
Deploy this to DEV and TEST.

**Comment by Stella-Archer** [comment]
@bhumin-fw  Sweet this is working great just the very last point could we change the label on the "Select Ministry" field to "Ministry or organization"
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/e8a19c96-35a4-4299-97db-b6fec5f61729)

**Comment by bhumin-fw** [comment]
@Stella-Archer It is updated on all env.

**Comment by ayushdamani** [comment]
Thank you, Bhumin!
Tested and verified working in both environments.

![Screenshot 2023-05-26 094116.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/aa201ed4-2697-4fff-93a6-6195aadcd16b)

**Comment by Stella-Archer** [comment]
Sweet this worked perfectly PO Approved and Closing tix! :)
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/b96151c7-6486-452a-a143-37ea01753db9)
