### ISSUE TITLE
Cold/Flu: Add users for UAT/UX testing 

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1146]
“As a <the UAT?UX test organizare I want ensure the following user can access the cold and flu form in the  TEST environment  so I be sure any issue are identified , fixed and we are ready for launch on June 12 

**Tasks**
add the following users to the TEST environment so they can test the cols and flu form:

* [ ] Nass Nassreen.Noorizadeh-Kollou@gov.bc.ca
* [ ] Caleb Liu Caleb.Liu@gov.bc.ca
* [ ] Natasha Jackson (PSA) Natasha.Jackson@gov.bc.ca
* [ ] Karysa Koshey (PSA) Karysa.Koshey@gov.bc.ca
* [ ] Nataliya Reade (PSA)Nataliya.Reade@gov.bc.ca
* [ ] Dana Askew (PSA)Dana.Askew@gov.bc.ca
* [ ] Christopher Matei (PSA)Christopher.Matei@gov.bc.ca
* [ ] Claudette Kolarich Claudette.Kolarich@gov.bc.ca
* [ ] Ian Brownlie
* [ ] Moira Lee Moira.Lee@gov.bc.ca

**Comment by MeghanStothers** [comment]
@Stella to add email addresses

**Comment by Abuchana** [comment]
Users have been added into the UAT environement
