### ISSUE TITLE
SL Review: Update to final email - Alchemer Link

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1176]
**User Story**
Update to final email to add survey link and tweak language to align with direction from communication team

**Tasks**
 Email with PDF copy
* [x]	Just before the last sentence, add as paragraph:
“Please take a few minutes to respond to the **SLR Survey** on your experience with the process, form and related materials. Your feedback will help us improve the next review process.”
* [x]	Link the words **SLR Survey** to: 
https://survey.alchemer-ca.com/s3/50193895/2023-Senior-Leadership-Review

* [x]	Last sentence, change to “Thank you for participating in the Senior Leadership Reviews. If you have any questions, please contact the SLR Team. (delete process, plural review**s**)
* [x]	SLR Team links to mailto:PSA.SeniorLeadershipReview@gov.bc.ca

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/03928497-512d-48d7-abc7-41c0dc58addd)

**Acceptance Criteria**
link works language updated

**Comment by Andrew-Vargas-bcgov** [comment]
complete, moving to test

**Comment by ayushdamani** [comment]
Tested and confirmed - acceptance criteria has been met ✅


![Screenshot 2023-06-06 085215.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/73c8c69b-e497-4dca-9fa9-ccdaa4aaea8a)

**Comment by Stella-Archer** [comment]
Perfect - Great Job everyone good to move to PROD
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/c12d0f2a-a20d-4667-80ff-7eb916972f43)
