### ISSUE TITLE
Telework: Updates, realign PDF to new form contents 

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1208]
**User Story**
“As a an employee requesting a telework agreement, I want to makes sure all the new location details are captured in my PDF of the Agreement so I can have a legal record  with accurate and complete information.” 

**Tasks**
* [ ] After new contact information is added to the telework form review the PDFs, both compiled and downloaded versions to be sure the new information is captured
* [ ] If information is missing adjust PDF to ensure it's included

**Acceptance Criteria**
* [ ]  All information collected in the Telework form appears on both the compiled and the downloaded PDF

**Comment by MeghanStothers** [comment]
May not need this ticket - for investigation
