### ISSUE TITLE
Documentation for program area team

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1210]
**User Story**
As a program area, we need to have a clear and transferable documentation and knowledge transfer system, so that we can manage changes in staff and multiple people preforming core tasks, maintain changes to forms at any time in the future an know where to make the changes in Digital Journeys complex technical environment.

**Tasks**

- [ ] Map out each form we've done (front and back end) (e.g. include Chris' #ing system) include Camunda workflow, use Visio, BPMN in Miro DMN (?)
- [ ] explore options
- [ ] Steps needed to achieve this processes
- [ ] break this down into smaller tasks project for each piece of collateral
- [ ] confirm team members easily Identify where to make changes as updates to any form in the DJ environment

Acceptance Criteria

* [x] Team members easily find Job aids and documentation for program area tasks

**Comment by Stella-Archer** [comment]
More details in #745

**Comment by Stella-Archer** [comment]
look at documentation of a single form Project document thoroughly enough for knowledge transfer pe=adoption
who will be reading and maintaining who is responsible how often (tix 1)
onboarding documentation
knowledge base
where we put things so people can find things
OneNote: research pre-Adoption (tix 2)

**Comment by Stella-Archer** [comment]
@chriscaldwell-psa to close this ticket for special sprint I'd like you to start the OneNote documentation by building out the Mailbox maintenance piece.
Then you should be able to Demo this for the team at the Special Sprint Retro

**Comment by Stella-Archer** [comment]
This is starting to look reallly great team can get in find documentation and edit things the are SME of
PO approved and closing this tix 
future documentation project ate in the EPIC #1211
Process Improvement: Developing Processes/Best Practices for program area
