### ISSUE TITLE
Reporting dashboard for program area/dev team

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1212]
**User Story**
As a program area, I would like to start mapping out a digital journeys internal dashboard that might be of value to our team as well as the clients
For example - what ministry they belong to?

**Tasks**

- [ ] Analysis: Identify what metrics do we as a program area to see and track for reporting or insights to gaining efficiencies
- [ ] Design: how would we best lay out and access pieces of information
- [ ] Build: separate estimate to build this technically

**Acceptance Criteria**
how can we be sure this is done and works for the program area

**Comment by Stella-Archer** [comment]
#525 is this also seems related to this epic 
TOOL: "Metrics" dashboard inside the tool

**Comment by Stella-Archer** [comment]
how many stop and abandon
serve logs for basic tracking
Where are they coming from
Patterns traffic
when is it best to do a deploy
how many are in the tools
how long in draft before submission - inform retention policy
approve form times

**Comment by Stella-Archer** [comment]
Closing ticket it will be acted on in ticket #1165
