### ISSUE TITLE
TOOL: DMN workflow simplification

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1213]
**User Story**
As a developer, I want to a way to simplify super complex BPMN diagrams ;like telework or Mat/Pat so that they will be much easier and efficient to main tian in the future

Camunda workflows offer two interesting features that can help improve our forms: DMN and custom forms.

DMN simplifies workflow and automation. For instance, a Telework workflow with many branches for various conditions can be challenging to maintain. Replacing some of these branches/conditions with DMN can enhance the workflow and make it more understandable and maintainable. Even more complex workflows like Mat/Pat can benefit from DMN.

Custom forms in a workflow also make it easier for reviewers to view only the relevant fields. This eliminates the need for a giant form like Mat/Pat, where reviewers would have to scroll or page to the section they want to review and sign.

templating reusable pieces of forms

AOT can help us in understanding DMN and how to apply it to particular forms
simplify work flows

**Tasks**
* [x] independent review of recorded materials (videos and documentation) 
* [x] session with AOT about tools, strategies to map the Digital Journeys’ forms processes, application diagrams and more.
* [x] rework existing app flow to DMN
* [x] knowledge sharing with rest of DEV team
* [x] demo
* [x] Documentation

**Acceptance Criteria**
Understanding of DMN and Integration into new development

**Comment by Andrew-Vargas-bcgov** [comment]
Ready to test:
Create a telework on the Test environment.
Approve/deny the request and check the e-mails are being sent with the different conditions (occasional, 3 or less,  more than 3, approved, denied).

**Comment by ayushdamani** [comment]
Tested and confirmed working - received emails for all the different conditions.

Thank you for the instructions @Andrew-Vargas-bcgov

**Comment by Stella-Archer** [comment]
This works, has ben tested Andrew will build tix new workflows built. Amazing Job PO approved & Closing tix
