### ISSUE TITLE
[Tool]: Diagraming forms processes (Developing Processes/Best Practices)

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1214]
**User Story**
“As a Digital Journey  team member I want document of all functionalities/processes of a form coming from UX/BA/Discovery in a diagram(BPMN) so I can have a reference for whole team(DEV/BIZ/BA/UX/Clients/Executive) to understand what we are attempting to build.” 
Benefits: 
* [ ]  everyone has a clear view of a process from start to finish.
* [ ] Supports process management and understanding for both business and technical users.
* [ ] create efficiencies in processes allowing DEV to take it to the next level of simplification with DMN
sub project of Developing Processes/Best Practices for program area ticket #1211

**Tasks**
Steps needed to achieve this feature. 

**Acceptance Criteria**
A template or process for how to take outputs form UX /BA and describe them as a diagram that is useable by the DEV team

**Comment by Stella-Archer** [comment]
Work with Andrew and Chris to learn integration and maintenance of the DMN

**Comment by ayushdamani** [comment]
Meghan, Stella & team reviewed. Closing ticket.
