### ISSUE TITLE
SL Review: Ministry admin role

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1235]
**User Story**
As a ministry administrator I want access to individual SL Review forms from my ministry so I can to print them for our validation process.

**Tasks** 
Send an additional email (in addition to the email to the person who submit/validate a submission) with the PDF attached to an admin (an email address) upon every submission. 
This field should not be mandatory

---

* [ ] 1. Add text  "I would like to send a copy of my submission to my ministry administrator to prepare for our ministry validation meeting"
* [ ] 2. Add info box with "Ministry SLR key contact reference  (Link= https://bcgov.sharepoint.com/teams/06164/SitePages/Ministry-Validation.aspx?xsdata=MDV8MDF8fGVkYTM4MjAwNTMxYzQ3NDFlMTYzMDhkYjdkOWM4NTRmfDZmZGI1MjAwM2QwZDRhOGFiMDM2ZDM2ODVlMzU5YWRjfDB8MHw2MzgyNDE4ODM0MDgwMzIwOTl8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPbTFsWlhScGJtZGZUbFJLYTFscVVtMVpWRlYwVFRKTmVVNXBNREJPYW1NMFRGZEtiVTlYU1hST2JWa3hUa1JvYkUxSFZYcGFWRTB3UUhSb2NtVmhaQzUyTWk5dFpYTnpZV2RsY3k4eE5qZzROVGt4TlRNNU56VXh8ZDBhMzc5ZjRlMTYyNGM5MWUxNjMwOGRiN2Q5Yzg1NGZ8OGQyYjQ4Mzk3NTkwNGJiZWI5MGNjYWNlZGYwZDJkODM%3D&sdata=VmtnMFlmV1ZIQkVqS0hYR1pUWmJBektPSnlPN1BNT0pqbUJrQVR5d3M5QT0%3D&ovuser=6fdb5200-3d0d-4a8a-b036-d3685e359adc%2CStellaAnne.Archer%40gov.bc.ca&OR=Teams-HL&CT=1688592177176&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA2MDQwMTE2MSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D
* [ ] 3. Text= "Select administrator" Add  'employee look up field (same as 'select senior leader)
* [ ] 4. When employee is selected, populate this field with their email  Text= "Administrator email"
* [ ] 5.  Send copy,  PDF to that admin on submit for validation
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/5efc94fc-437c-4c42-a34f-6e15d32c87f9)
---
 Alternatively, 
* [ ] Create an admin role that can access and print PDFs for all users’ submissions. 
* [ ] Set up permissions in multiple components (Keycloak, Formio, Camunda, and the API). 

**Acceptance Criteria**
ministry admins can access and print contents of submissions from their ministries for validation processes/meetings

**Comment by Stella-Archer** [comment]
list from SharePoint: ​​​​​​​Ministry SLR Contacts

Agriculture and Foods: Shawna Lyttle, Manager Executive Operations & Planning, DMO
Attorney General: Kayla McKeown, Executive Director, Strategic Human Resources
BC Public Service Agency: Genevieve Racine, Executive Director, Strategic Human Resources
Children and Family: Soji Bryant, Executive Director, Strategic Human Resources
Citizens' Services: Celeigh Applebaum, Executive Director, Strategic Human Resources
Crown Agencies Secretariat: Brianne Kober, Director, Corporate Engagement, Planning & Operations
Declaration Act Secretariat: Lisa Gibbs, Director, Executive Operations & Corporate Priorities
Education & Childcare: Kim Russell, Executive Director, Resource Management & Operations
Emergency Management & Climate Readiness: Christine Fraser, Executive Director, Strategic Human Resources
Energy, Mines & Low Carbon Innovation: Ryan Clarke, Corporate Planning & Engagement, DMO
Environment & Climate Change Strategy: Jennifer Meadows, Director, Executive Operations
Environment & Climate Change Strategy (EAO Office): Chrystal Fenton, Manager, Human Resources Services
Finance: Jennifer Michell, Director, Executive Operations at Ministry of Finance
Forests: Andrea Wood, Director, Executive Operations
Government Communications & Public Engagement: Sharon Moss, A/Executive Director, Planning, Performance & Workforce Development
Health: Jordan Will, A/Executive Director, SMPO
Housing: Kayla McKeown, Executive Director, Strategic Human Resources
Indigenous Relations & Reconciliation: Geoff Bridge, Executive Director, DMO
Intergovernmental Relations Secretariat: Karen Milne, Manager, Executive Operations
Jobs, Economic Development and Innovation:  Rhonda McGinnis, Executive Director, Strategic Human Resources
Labour: Sveah Hourston, Manager Executive Operations
Mental Health and Addictions: Kimberley Gardner, Executive Director, Human Resources & Communications
Municipal Affairs: Rhonda McGinnis, Executive Director, Strategic Human Resources
Post Secondary Education & Future Skills: Deborah Schwartz, Executive Director, Governance & Corporate Planning
Public Safety & Solicitor General: Kayla McKeown, Executive Director, Strategic Human Resources
Public Sector Employers' Council Secretariat: Briana Smith, Senior Executive Assistant
Social Development & Poverty Reduction: Heather House, Executive Director, Strategic Human Resources & Communications
Tourism, Arts, Culture & Sport: Rhonda McGinnis, Executive Director, Strategic Human Resources
Transportation & Infrastructure: Vanessa Gedney, Executive Director Executive Operations
Water, Land and Resource Stewardship: Sandra Roe, Director, Executive Operations

**Comment by fazil-ey** [comment]
@iman-jamali-fw  to review and estimate

**Comment by iman-jamali-fw** [comment]
@Stella-Archer

I see three different ways we can approach this:

Option one involves allowing ministry-specific roles for SL forms, which would enable the users to view and print all submissions from their respective ministries. However, implementing this feature would require significant development effort and ongoing maintenance due to the changing permission system in AOT's upcoming versions. It may be best to avoid this option unless we can reuse the same feature in other forms.

The second option, as mentioned in the ticket, is to let users search for and select the ministry admin. Once selected, the ministry admin will receive an email with a PDF attachment. This option should be relatively straightforward to implement (estimated effort: 5) and would require less maintenance, even if there are changes in ministry names or admin emails.

Lastly, we can automate the process at the Camunda/workflow level based on the selected ministry name in the submission. To achieve this, we can maintain a DMN table that maps ministry names to a list of ministry admin email addresses. Then, in the background, we can automatically send an email with a PDF attachment to those admins. This option is relatively easy to implement (estimated effort: 3), but it requires maintaining the DMN table in Camunda.

Please let me know if you have any questions or if there's a specific option you'd like to explore further.

**Comment by fazil-ey** [comment]
Decision - go ahead with option 3. Since SL will end in sept we dont expect too many changes to the list.

**Comment by Andrew-Vargas-bcgov** [comment]
@Stella-Archer Should we add an email to the submitter on the initial submission and also revalidation? There is currently only an e-mail to the submitter upon final submission.

If we do decide to add the email to the submitter upon initial submission, I will need the email copy for what it should say.

**Comment by Andrew-Vargas-bcgov** [comment]
Received emails and will add them to the DMN today. Editing workflow to incorporate new submission/revalidation emails for submitter and SL admin.

Disabling manual input for Ministry, Division and Branch fields to align these fields accurately with the autopopulated ODS data to align with the reporting team. Discussing with Stella/Meghan/client before making these changes.

**Comment by MeghanStothers** [comment]
To test today to move to deployment - Andrew to check email content

**Comment by MeghanStothers** [comment]
@Andrew-Vargas-bcgov Howdy - is this one ready to go for deployment tonight?

**Comment by Andrew-Vargas-bcgov** [comment]
@Stella-Archer I have added the following text to the first bullet in the slreview form:
"A copy of your submission will be sent to the senior leader's ministry administrator to prepare for the ministry validation meeting."

Would you check with Jodi to see if this is okay language?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEk0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--227d95fc136d1fa1155a9867ec1593394b4471e8/image.png)

I have moved the dmn to test. If you select a senior leader in the PSA, it will send the ministry copy to the digitaljourneys mailbox for testing purposes. All other have their real ministry contact as a recipient.
I will be adding the final 3 remaining ministries that have updates (just have to look up their identifiers).

**Comment by iman-jamali-fw** [comment]
Tested on TEST with [`forms-flow-client` + `sl-review-adm`] roles assigned to my user account:
- Initial/resubmit/final submissions were all successful
- I got the email with the PDF for the submitter for the initial/resubmit/final submissions
- Email to the ministry admin needs to be verified by @Andrew-Vargas-bcgov as I don't have access to that mailbox
- There are some logs that need to be removed from the `forms-flow-bpm` container. Probably has something to do with the DMN.

@mikeshi-bcgov Can you verify applicationId of `2979` at ODS, please? Thank you

@Stella-Archer I suggest someone with real IDIR also test out this ticket before going to PROD.

**Comment by Andrew-Vargas-bcgov** [comment]
@iman-jamali-fw received the following submissions last night:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1U5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4f40db3bcf709c6bd923ae2924cc3218303824ae/image.png)

**Comment by ayushdamani** [comment]
Received the 3 emails for submission, resubmission and final submission.
Confirmed the same in the Digital Journeys Inbox.

**Comment by mikeshi-bcgov** [comment]
@iman-jamali-fw sorry missed this thread. Confirm we received those 2 submissions 2979 and 2982 in ODS.

**Comment by MeghanStothers** [comment]
@Andrew-Vargas-bcgov - is there anything else we need to do before closing this ticket?
