### ISSUE TITLE
[SL Review]: Updates to Ministry contact - time sensitive

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1326]
**User Story**
“As a ministry contact I want receive emails with copies of all SLR nominations form my ministry so I can get prepare them for the validation meeting.” 
Some contacts in the ministries have, or will change roles please soon update the following"

**Tasks**

Date: **September 18, 2023**	
Contact: **Lori MacDonald**
**Action** 
**Remove Access for:**		
* [ ] Agriculture and Food
* [ ] Energy, Mines and Low Carbon Innovation
* [ ] Environment and Climate Change Strategy
* [ ] Indigenous Relations and Reconciliation	
**Grant Access for:**
* [ ] Post-Secondary Education and Future Skills

Date: **September 18, 2023**	
Contact: **Caroline Birnie**
**Action** 
**Grant Access for:**
* [ ] Agriculture and Food
* [ ] Energy, Mines and Low Carbon Innovation
* [ ] Environment and Climate Change Strategy
* [ ] Indigenous Relations and Reconciliation	

Date: **September 30, 2023**	
Contact: **Deb Schwartz**
**Action** 
**Remove Access for:**		
* [ ] Post-Secondary Education and Future Skills

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by MeghanStothers** [comment]
Andrew will update the DMN and he'll need help from Bhumin.

**Comment by Andrew-Vargas-bcgov** [comment]
added Caroline to slreview group.
Waiting to hear back from slreview team on post secondary education and future skills pdf recipient before updating dmn.

**Comment by Stella-Archer** [comment]
Lori will be the contact
