### ISSUE TITLE
Mat/Pat: Measuring Success

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1347]
**User Story**
“As a product owner/Business lead I want make sure the new Map/Pat digital Journey is a success so I can redirect CRM tickets from The HR service reps to the Payroll group after pilot.” 

We assume the new process will:

- Reduced number of calls/service request to HR Service Centre
- Most Mat/Pat leave requests should go direct from Digital Journeys into CRM
- Reduced time on calls to HR Service Centre
- Eliminate ‘math’ errors
- Eliminate call backs over wrong start date
- Eliminate call backs over incorrect calculations of estimated pay/leave lengths
- Reduced calls requesting info on external services (EI)

Lets confirm this with real post launch data

**Tasks**

- [x] Meet with HR Service, CRM and BI people to explore how best to track DGJ tickets
- [x] Decide on what success looks like before we can divert tix to payroll
- [x] Look at what we'd like to measure (the hypothesis)
- [x] Design and build 'monitoring system'
- [ ] test, test, test!
- [ ] Training with service reps

**Acceptance Criteria**

- We have a method in place before launch to track leave requests going form the digital journeys platform to CRM
- Criteria for 'success' confirmed and system in place to identify when this is met

**Comment by Stella-Archer** [comment]
**DONE**
* [ ] Met with HR service center, CRM expert from PSA and BI experts to explore possibilities
* [ ] Met with TES CRM experts gathered their advice to look at 'canned analytics with in the CRM app

**TO DO**
* [ ] Work with DGJ team develop KPI
* [ ] Review KPI with Client and HR Service reps
* [ ] Run KPI by TES 
* [ ] TES recommends suitable analytical reports
* [ ] Develop list of users to explore suitable reports
* [ ] Confirm
* [ ] Test with team and HR Service Rep
* [ ]  Implement
* [ ]  Test 
* [ ]  Monitor

**Comment by Stella-Archer** [comment]
Discussed with TES Nancy who recommended canned analytics form the CRM,  KPI we'd like to monitor have been sent to Nancy as well as request for access for team & BI people

**Comment by Stella-Archer** [comment]
Report is work for Chris
Nancy it moving it to PROD and update the API name to remove “test”.

**Comment by fazil-ey** [comment]
@chriscaldwell-psa to book a meeting with Nancy to resolve the data mismatch issues
