### ISSUE TITLE
BIZ Process: Onboarding New DEV

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1403]
**User Story**
“As a new developer I want to onboard efficiently so I can get to work  ASAP :).” 

**Tasks**
Technical Orientation  

* [ ] Getting to know background skill set of new dev so we can work strategically to onboard 

* [ ] Intro/ new dev meets the current ones; orients with the processes 

* [ ] Demo some of the forms 

* [ ] Intro on form flows platform 

* [ ] Intro on high level components that help build form flow  

* [ ] Share useful links and guides 

- AOT's playlist  

- https://formsflow.ai/ 

- https://aot-technologies.github.io/forms-flow-ai-doc/ 

- https://github.com/AOT-Technologies/forms-flow-ai/tree/v5.2.0 

- https://help.form.io/userguide/introduction 

- https://github.com/formio/formio.js 

- https://docs.camunda.io/docs/guides/ 

* [ ]  Show test, dev & prod environments 

* [ ] Setup local environment 

* [ ] Review DevOps side of things - OpenShift and where the platform is deployed, CI/CD 

* [ ] ​Orientation to  peer reviews developer collaboration process 

* [ ] Review our customization/ standardize work flow - 'how we do form design' 

* [ ] customization changes/biz logic 

  

Business Area Orientation  

* [ ] Review project purpose and goals - Brief BCPSA Org structure, HR service & how PSA and Digital Journeys fits in (Product Owner/Program Lead)  

* [ ] Digital Journeys roadmap (Product Owner)  

* [ ] Demo of an existing form(s) for reference (Program Lead)  

* [ ] Focus on projects currently under way, review issues and accomplishments, expectations 

Scrum Elements  

* [ ] Share SCRUM-framework_2020.pdf (Scrum Master)  

* [ ] Share Scrum in 3 minutes (Scrum Master)  

* [ ] Digital Journeys Team channel access (Scrum Master)  

* [ ] Teams as preferred communications tool (Scrum Master)  

* [ ] GitHub and ZenHub access (Product Owner)  

* [ ] ZenHub board navigation (Product Owner)  

SL Scrum Team_ Walk-through the ZenHub-20220808_150434-Meeting Recording   

* [ ] Creating ZenHub tickets (Scrum team member)  

  

Scrum Events (include participation and purpose)  

* [ ] Schedule a kick-off meeting with new form owner and team (introductions, initial MVP overview/vision)   

* [ ] Send Scrum event invites to form owner and team (Scrum Master)  

- Scrum (Daily Mon-Fri 8:45 am - 9:00 am)  
- Sprint Review (3-week cycle Wed 10:00-10:30)  
- Sprint Retrospective (3-week cycle Wed 10:30-11:00)  
- Sprint Backlog Grooming (Weekly Thurs 10:30-11:30)  
- Sprint Planning (3-week cycle Thurs 11:30-12:00)

**Comment by MeghanStothers** [comment]
I closed two other tickets about onboarding #1314 and #1346 to avoid duplication.

**Comment by MeghanStothers** [comment]
We're connecting with AOT folks on Monday about the namespace - l'll ask about a separate session for J so we can cross this one off the onboarding list: 1-2 hours training with AOT that explains various components 1:1 (Expansion of AOT Playlist)

**Comment by MeghanStothers** [comment]
<img width="1307" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50fdc8ae4fe133a81c6f5529a375bfad6864fb35/image.png" alt="image.png" />

**Comment by MeghanStothers** [comment]
Before changing team tools, this ticket is definitely a resource we should keep/archive in our Teams channel.

**Comment by Stella-Archer** [comment]
most of this has been captured here> https://bcgov.sharepoint.com/teams/03991/_layouts/OneNote.aspx?id=%2Fteams%2F03991%2FShared%20Documents%2FProcess%20Documentation&wd=target%28Onboarding.one%7CF150E25D-8B12-442C-96FD-1D9BE1A4480C%2FChecklist%20Template%7CE38C5264-11EC-4D22-B22C-8544C5B6BD9D%2F%29
onenote:https://bcgov.sharepoint.com/teams/03991/Shared%20Documents/Process%20Documentation/Onboarding.one#Checklist%20Template&section-id={F150E25D-8B12-442C-96FD-1D9BE1A4480C}&page-id={E38C5264-11EC-4D22-B22C-8544C5B6BD9D}&object-id={95047F3C-84FA-0946-37FB-CA4758743B17}&12 **but it would be good to check against this**
