### ISSUE TITLE
Epic Sustainment Plan

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/digital-journeys#1413]
We will need to identify all the activities and projected resources to maintain the project on a monthly and yearly basis.

This will include, but may not be limited to:

```[tasklist]
### Project Sustainment Tasks
- [ ] Determine upgrade cycles and scope (Devs)
- [ ] Monitoring Snyk / Dependabot and related Pull Requests (Devs)
- [ ] Monitoring ACS Dashboard and remediation of vulnerabilities with a status of High or greater (DevOps)
- [ ] Monitoring Sysdig alerts (DevOps)
- [ ] Monitoring and triage user support channels (Devs, DevOps, Call Centre, Team)

Recommendations to determine effort and scope from historical documents: 

Snyk PR's / month / year, with previous implementation tickets / efforts (currently 32 open, 68 closed).

Call centre stats and previous tickets (and related effort)  relating to issues with forms, authentication, etc.

Monthly/yearly uptime (currently 99.42%), and related support efforts. This could include cluster monitoring and notifications from #devops-alerts in Rocket.Chat, etc.). We should have a method to alert the team to upcoming or unforeseen issues that may impact users. This should be considered when deciding on release dates, user messaging, etc.

Projected time and resource allocation for handling changes to integrated systems, such as adding EMPLID or other KeyCloak / authentication changes, PeopleSoft, CDATA or BI data requirement changes, updating SSL certificates, security scans / remediation, etc.

FormsFlow.ai upgrade cycles and projected path (9 upgrades between July '22 and July '23), including one major. Five the year before. Some effort should be committed to reviewing and testing future upgrades for security patches, features, bug fixes, and other relevant information to be reviewed to consider future upgrades. A monthly and/or yearly report may be an effective way to ensure these are considered. Or we can limit upgrades to security patches only, however, there will be a limit to the support for each version, so major version upgrades will most likely be required to maintain security at some point. In this regard, it may be effective to implement all updates in a continuous fashion. Possibly even automatically at some point. This could include automating (or streamlining/scheduling) updates from AOT and/or Snyk / Dependabot.

How much time will we need to dedicate to testing and verification of updates, and who will do it? This may differ between security patches and version upgrades or SSL certificate validation. Can we automate? If not, create test scripts / stories and assign team members? Or allow user-testing / reporting of incidents to identify issues with automated or scheduled updates (minimal effort)?

If anyone has any ideas, suggestions or recommendations, please add them bellow.
