### ISSUE TITLE
Mat/Pat - Before production checklist

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1469]
- [ ] ~~The initial submission shows the success page even if there is an error in the Camunda workflow or if Camunda cannot start the workflow. Improve the error handling to ensure proper error message is shown if any of the components (API, formio and Camunda) fails.~~ This was moved to [#1484](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1484)
- [x] Before moving the Mat/Pat form to production make sure the name, IDs for the form and process definition (Camunda workflow) are correct and follow the same pattern. All the related components to name/id should also updated (like success pages).
- [x] Ensure, unnecessary tabs in the form are deleted. Check (confirmation, summary and other tabs).
- [x] There were lots of improvements to form field validation and syncing fields/dates. It's worth devs reviewing the form frontend logic/validations and ensuring those global fields are leveraged in the validations/logic.
- [x] Camunda permissions should be tested and make sure only necessary Camunda permissions should be assigned to the form's workflow in Camunda.

**Comment by iman-jamali-fw** [comment]
@MeghanStothers @fazil-ey 
This checklist has a few actions items that I think is necessary to get done before Mat/Pat go to production. Especially the first one, in my opinion is MVP. Please review this ticket and if you're agree move it to this sprint work.

This should be around 5 story point worth of effort. The first item, 3 and more important than others.

**Comment by iman-jamali-fw** [comment]
The first item has moved to a separate ticket [#1484](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1484)

**Comment by MeghanStothers** [comment]
@Stella-Archer When we test after the deployment on Dec 4, we will need to check that the Telework front-end updates (made in August 2023) have NOT been pushed to production.

**Comment by iman-jamali-fw** [comment]
A 2-hour meeting (Monday 10-12) was book for devs to go through the checklist and do cleanup and refactoring Mat/Pat for production.

**Comment by iman-jamali-fw** [comment]
This was done by colaboration of all the devs. We found a few more improvements for post-production that I'll write down in separate tickets.

This is ready to move forward
