### ISSUE TITLE
[TOOL]: TESTING: "Kitchen Sink" test form

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1527]
**User Story**
“As a development team I want to test all custom components in one place each time we deploy so I can be sure all custom work is still functional in the new deployment.” 

**Tasks**
- [ ] Work with dev team to identify all custom components we have created in Digital Journeys (not part or core forms flow)
- [ ] Create a new form with the following component:
- [ ] Name selection field from SL Review see ticket #1523
- [ ] test with this 'Kitchen Sink' form each time we deploy

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by MeghanStothers** [comment]
Suggestion to connect with Steffi for her lens on this work (how do we keep this up-to-date) and assist with our QA

**Comment by fazil-ey** [comment]
this work is being done as part of #1548
