### ISSUE TITLE
Checklist: Onboarding New DEV - Jerry

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#1611]
**User Story**
“As a new developer I want to onboard efficiently so I can get to work  ASAP :).” 

Resources/linkages : 
AOT consulting hours - see ticket #1361
[Onenote:](https://bcgov.sharepoint.com/teams/03991/_layouts/15/Doc.aspx?sourcedoc=%7B6f028f9f-6cf7-4828-98b6-9f8a532f3b29%7D&action=edit&wd=target%28Onboarding.one%7Cf150e25d-8b12-442c-96fd-1d9be1a4480c%2FProcess%20Roles%20and%20Activities%7C3c0d55e4-97f4-4e48-95ed-3354e4214a1f%2F%29&wdorigin=Navigation) 
[Teams Digital Journeys external channel](url)

**Tasks**
**Technical Orientation**  

* [x] Getting to know background skill set of new dev so we can work strategically to onboard (Iman/Bhumin/Andrew)

* [x] Intro/ new dev meets the current ones; orients with the processes (Iman/Bhumin/Andrew)

* [x] Demo some of the forms (Iman/Bhumin/Andrew)

* [x] Intro on form flows platform (Iman/Bhumin/Andrew)

* [x] Intro on high level components that help build form flow  (Iman/Bhumin/Andrew)

* [x] Share useful links and guides (Iman/Bhumin/Andrew)

- [AOT's playlist](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutube.com%2Fplaylist%3Flist%3DPLJT6neowTxHQFrbbOyFRBLmZ_RQA_xhKf&data=05%7C01%7CBhumin.Patel1%40ca.ey.com%7C1e4a5333eaaa4012ec1108db30a892b2%7C5b973f9977df4bebb27daa0c70b8482c%7C0%7C0%7C638157272826343038%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HQDwp1dWp3zrhIPNDPV%2FdzI8igpZUcjJi2b1bGRVlKk%3D&reserved=0)  
- https://formsflow.ai/ 
-  Formflow.ai
    - https://formsflow.ai/

- https://aot-technologies.github.io/forms-flow-ai-doc/ 
- https://github.com/AOT-Technologies/forms-flow-ai/tree/v5.2.0 
- https://help.form.io/userguide/introduction 
- https://github.com/formio/formio.js 
- https://docs.camunda.io/docs/guides/ 
- https://docs.camunda.org/get-started/quick-start/
- https://help.form.io/
- 
https://mvp.developer.gov.bc.ca/

link to the form.io user guide: https://help.form.io/userguide/forms/form-components
On the left-hand menu, you will find different topics to get more information about.

Here is formsflow youtube channel which contains helpful content:
https://www.youtube.com/channel/UCRXqdVDjDjxWFgdwhE-Ll6A

Some info on how to start off with Camnuda workflows:
https://docs.camunda.io/docs/0.25/components/zeebe/getting-started/create-a-workflow/

1)	OpenShift onboarding new project and teams: https://docs.developer.gov.bc.ca/provision-new-openshift-project/
2)	OpenShift architecture (see slide https://docs.google.com/presentation/d/1UcT0b2YTPki_o0et9ZCLKv8vF19eYakJQitU85TAeD4/edit#slide=id.g930443f34a_0_72

3)	OpenShift responsibilities: Slide 8: https://docs.google.com/presentation/d/1UcT0b2YTPki_o0et9ZCLKv8vF19eYakJQitU85TAeD4/edit#slide=id.g930443f34a_0_72
OpenShift security/devOPs: https://docs.google.com/presentation/d/18al9LPI6hE4oSVDPwUPZP77qhmplZQjFWxn9baiUPt8/edit#slide=id.g13d03bd0c90_0_745

* [x]  Show test, dev & prod environments (Iman/Bhumin/Andrew)
* [x] Setup local environment (Iman/Bhumin/Andrew)
* [x] ​Orientation to  peer reviews developer collaboration process (Iman)
* [x] OpenShift 101 Optional (See links above)
* [x] Managing Repo GitHub tickets
* [x] Deployment Overview

**Developer's Orientation Task List**  
* [x] Review Technical components [FormsFlow.ai](https://formsflow.ai/), [Camunda](https://camunda.com/) (Jerry)
* [x] Access GitHub read Digital Journeys customized documents on GitHub (Jerry)
* [x] Review Front end API, Camunda understand how it is set up and how data flows between pieces (Jerry)
* [x] Review How to set up repo on local environment (Jerry)
* [x] Confirm Open shift access, review log to see issues (Jerry)
* [x] Set up docker (Jerry)

**Business Area Orientation**  
* [x] Review project purpose and goals  (Meghan/Stella)
- Brief intro to BCPSA Org structure, HR service improvement/modernization
- How PSA and Digital Journeys fits in to larger BC gov
- Alignments with corporate plans
- Development principles
- Focus on projects currently underway, review issues and accomplishments, expectations   

* [x] Digital Journeys roadmap (Meghan)  

* [x] Demo of an existing form(s) for reference (Stella)  

See Teams channel: "Digital Journeys External"  Resources/Onboarding ppt deck that can be updated: https://bcgov.sharepoint.com/:f:/r/teams/03991/Shared%20Documents/General/Orientation%20for%20Business%20Areas?csf=1&web=1&e=0JU6JF

**Scrum Elements**  

* [x] Share [SCRUM-framework_2020.pdf](https://bcgov.sharepoint.com/:b:/t/02050/EeghsjuFF2tMtGJ2bLQX4ugBsSx1ikpts_L8XQK10qYJ5A?e=T5YRP4) (Scrum Master)  

* [x] Share [Scrum in 3 minutes](https://www.youtube.com/watch?v=iJ_sl6J8PRg) (Alison)  

* [x] Digital Journeys Team channel access  (Alison)  

* [x] Teams as preferred communications tool (Alison)  

* [x] GitHub and ZenHub access (Chris)  

* [x] ZenHub board navigation (Chris)  

[SL Scrum Team_ Walk-through the ZenHub-20220808_150434-Meeting Recording  ](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbcgov-my.sharepoint.com%2Fpersonal%2Fmeghan_stothers_gov_bc_ca%2FDocuments%2FRecordings%2FSL%2520Scrum%2520Team_%2520Walk-through%2520the%2520ZenHub-20220808_150434-Meeting%2520Recording.mp4%3Fe%3D4%253a91785817a34c4e5882f6e5122e4a22fc%26web%3D1%26at%3D9&data=05%7C01%7CAlison.Buchanan%40gov.bc.ca%7C0540a97bb77c493570be08dac29002dc%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638036221133626438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=FSbJvguSVvcgllmW93AeBl62xB1HJtfWV3Cx8ZdUiXs%3D&reserved=0) 
* [x] Creating ZenHub tickets (Chris)  

**Scrum Events (include participation and purpose)**  
* [x] Schedule a kick-off meeting with new form owner and team (introductions, initial MVP overview/vision)   (Alison)
* [x] Send Scrum event invites to form owner and team (Alison)  
- Scrum (Daily Mon-Fri 8:45 am - 9:00 am)  
- Sprint Review (3-week cycle Wed 10:00-10:30)  
- Sprint Retrospective (3-week cycle Wed 10:30-11:00)  
- Sprint Backlog Grooming (Weekly Thurs 10:30-11:30)  
- Sprint Planning (3-week cycle Thurs 11:30-12:00)
