### ISSUE TITLE
Cold and Flu: Issue Update confirmation Emails

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1614]
**User Story**
“As a clinic registrant, I want to see '2024' in my email message (NOT 2023) so I can feel confident I've registered for the current cold season clinics, and the dates are accurate and up to date. 

<img width="707" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1k4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--878d6c99724f55cf3e0c0f977d66b5494b59fa14/image.png" alt="image.png" />

**Tasks**
- [ ] 1/ Change 2023 to 2024
- [ ] 2/ Change 2023 to 2024
- [ ] 3/  "July-August" is the correct time frame NO ACTION needed here
- [ ] 4/ Update dates for the registration period to June 10-28, 2024 
- [ ] 5/  Update Registration Period end date to June 28, 2024
- 
**Acceptance Criteria**
Task Check list is accurate and complete

**Comment by Stella-Archer** [comment]
Hidden field in FF so not part of workflow. AND designers could then edit it

**Comment by Andrew-Vargas-bcgov** [comment]
ready for testing @ayushdamani

**Comment by ayushdamani** [comment]
Tested in TEST - working great! Thanks, Andrew :)
<img width="807" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXhPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3acdbfbe26e323c042a29eec830cf3e54f3204f0/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
This looks really great @Augusteen-myeong you should be able to get in and see the updates in TEST, Heather should also be able to get in to the TEST environment now too > https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form/641b44c5bddb37f24587dcf3
I can walk you through the form if you'd like.
The links on the email will not work yet as the web page is down until registration is open.

<img width="673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHBqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a391b1c149413ad6254c3353f7d82ae0f7399f87/image.png" alt="image.png" />

**Comment by Augusteen-myeong** [comment]
Hi @Stella-Archer  Thanks for the link. I've tested the form and I see this pop up with 2023 on it. 
![image](https://github.com/bcgov/digital-journeys/assets/159492049/34404669-c374-4691-bf04-1e036e2088dd)

Also, I wasn't able to test the registration parts. 
- 4/ Update dates for the registration period to June 10-28, 2024
- 5/ Update Registration Period end date to June 28, 2024

**Comment by Stella-Archer** [comment]
Oh this is super interesting -  so grateful you are in testing @Augusteen-myeong -  I'll create a new ticket for this and have the dev team look into it as I don't thing anyone should see this old message now!

**Comment by Stella-Archer** [comment]
Looking good live reclosing
<img width="1010" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ecbd80a9cc7eec9dce850d9685620bec52b3b60c/image.png" alt="image.png" />
