### ISSUE TITLE
TOOL: Deployment in Silver/d89793-dev automatically scaled down

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1629]
**User Story**
“As a product owner/developer I want know how scaling down the files in DEV impacts me so I can be prepared and develop a mitigation strategy.” 

> **DeploymentConfig/forms-flow-files in the namespace d89793-dev on the Silver cluster has not been updated in over a year. As it is likely not being maintained, it has automatically been scaled to zero to maintain cluster health.**

**Tasks**
- [ ] Investigate implications of DEV files being scaled down
- [ ] develop a remediation plan for any potential negative impacts

**Acceptance Criteria**
- [ ] PO, DevOps and Dev clearly understand the implications of DEV files being scaled down
- [ ] there is a plan in place for any potential negative impacts

**Comment by warrenchristian1telus** [comment]
When we implement JFrog Artifactory into our deployment workflows we should be able to incorporate an DeploymentConfig annotation trigger each time the namespace is updated from GitHub. This should cause the last-updated date to be consistent with the latest development update and/or security patch, and eliminate the risk of deployments getting stagnant if they don't directly receive updates from developers.

**Comment by Andrew-Vargas-bcgov** [comment]
look at this and develop long term plans for how to trigger (manually?) so we don't get shut down.
This should be combined with security patching going forward. -warren
would be nice to have automated security patching with testing if possible.
Might be able to utilize built in formsflow testing suite.

**Comment by MeghanStothers** [comment]
I chimed in at the latest OpenShift platform meeting and they sent this link to more info and who to contact: https://docs.developer.gov.bc.ca/platform-automation/

**Comment by Stella-Archer** [comment]
need stateful config in code base

**Comment by warrenchristian1telus** [comment]
This is still an issue, and we will need to investigate the best policy to update our images on a regular basis. At least once per year to avoid this particular issue.

The recent upgrades should make this easier, but we will need to ensure that ALL pod images are updated during either normal updates (when code is deployed) or on a schedule (possibly largely set by AOT update availability).

We may need to investigate the options for (re)building all images from GitHub Actions, as we're currently doing for Moodle and eventually all the other OpenShift projects as well.

I think this will likely factor in with measures to better align our repo with AOT and [hopefully] streamline and/or automate updates from FormsFlow.ai.

**Comment by fazil-ey** [comment]
This is only an issue in the dev environment for file upload. The risk is if we upload a bunch of files in dev for testing, they might fail. If this happens we should contact Warren and figure out a solution. 

@bhumin-fw to confirm with warren and close if its not an immediate or major risk to production

**Comment by fazil-ey** [comment]
This is only an issue in the dev environment for file upload. The risk is if we upload a bunch of files in dev for testing, they might fail. If this happens we should contact Warren and figure out a solution. 

@bhumin-fw to confirm with warren and close if its not an immediate or major risk to production

**Comment by warrenchristian1telus** [comment]
Just to be clear, this affects **any** pod in dev and test. It will not affect production deployments.

**Comment by fazil-ey** [comment]
Some pods like the file pos used for telework attachments are not being used because we do not upload files in test and dev usually. We also do not change the codebase usually. So the system automatically optimizes by scaling down some pods. 

If this happens we get a notification - and we can scale up if needed. So we have a plan of action if this would happen. So we can close.
