### ISSUE TITLE
TOOL: OCI testing

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1666]
**User Story**
“As a data consumer, I want ensure the data endpoints which are moving to the Oracle cloud work, as expected in all my applications so I have no unexpected interruptions when we transition from the TES servers” 

**Tasks**
- [x] Testing in DEV, all applications
- [x] Reporting any errors
- [ ] develop plans for fixing or mitigation
- [ ] more TBD

**Acceptance Criteria**
migration to OCI for all Digital journeys apps is smooth and seamless as possible

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
We have point DEV testing environment to new OCI API endpoint. Here employee demographic, demo and telework endpoint works fine.
But influenza endpoint return blank data and we not able to start testing on influenza form. 

New OCI endpoint domain is https://bi-api.tssi.ca/

Request URL:  **https://bi-api.tssi.ca/apiserver/api.rsc**/ods_datamart_influenza_ministries
response Object: {"@odata.context":"http://bi-api.tssi.ca/apiserver/api.rsc/$metadata#ods_datamart_influenza_ministries","value":[]}

**Comment by Stella-Archer** [comment]
As with the upgrade testing, please look at the form assigned to you  and confirm the new OCI end points work
Test the dev environment:
https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form
Tasks

1/ Mat/Par - @fazil-ey 
2/ Cold/Flu - @Augusteen-myeong *wait till @bhumin-fw or @mikeshi-bcgov  confirms the C&F data has moved to the cloud
3/ 1.10 - @ayushdamani @Andrew-Vargas-bcgov 
4/ Telework - @chriscaldwell-psa 
5/ SL Review - @Andrew-Vargas-bcgov 
leave comments in this ticket to confirm you have tested and if there is any issues
