### ISSUE TITLE
Cold and Flu: Deploy form to PROD and HIDE from all users except team and ADMIN

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1677]
**User Story**
“As a form owner I want test the 2024 form in PROD so I can be sure everything, including data is working as expected from login to report creation in BI.” 

**Tasks**
- [ ] create or revive cold and flu ADMIN security group
- [ ]  Deploy 2024 from to Prod on March 20 or 21
- [ ]  Form in prod should be visible, and fully functional ONLY to the Admin group, or team
- [ ]  Form in PROD should be made available to testing subjects when we are given their information
- [ ]  On June 10 form is visible and accessible to all employees

**Acceptance Criteria**
After deployment March 20/21:
- [ ]  Admin and dev team can see use a2024 form
- [ ]  Invited test subjects can access and submit form

**Comment by jerry-ey** [comment]
Bhumin and I created a new group `cold-flu-test` on production. And assigned this new group to our Team(Stella, Ayushi, Mike and devs).
@Stella-Archer could you let me know who else should I assign to? and who should be admin? Thanks

**Comment by Stella-Archer** [comment]
Waiting for list from Heather

**Comment by Stella-Archer** [comment]
We've got a list @jerry-ey https://bcgov.sharepoint.com/:w:/r/teams/03991/Shared%20Documents/Cold%20and%20Flu/2024%20Cold%20and%20Flu/Testers%20for%202024%20cold%20and%20flu%20form%20security%20group.docx?d=w60a5579e49554a05bfccdeea9213e6e2&csf=1&web=1&e=SN1KPH

**Comment by jerry-ey** [comment]
Tested on PRD, working fine.
Without the group `cold-flu-test` (except for `cold-flu-admin`, use can not see the cold/flu form.

<img width="1038" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb1d37647766ce2b890b0314ec1257776913df2a/CleanShot%202024-03-25%20at%2017.41.14%402x.png" alt="CleanShot 2024-03-25 at 17.41.14@2x.png" />

**Comment by jerry-ey** [comment]
Added two people to admin group.

**Comment by Stella-Archer** [comment]
team member who is not in the admin group could not see it (YAY) so I'm PO approving & closing
