### ISSUE TITLE
Cold/Flu: Worksite drop down list needs to display Unit#

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1683]
**User Story**
“As a user registering a worksite clinic I want to see the unit numbers of available worksites so I can confirm I am picking the correct one.

EXAMPLE: In the worksite drop down there is 2 entries for **"700 W Pender"**
<img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkwvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--baa1210a307a2ea9d958328b384024ce57b8c7b7/image.png" alt="image.png" />

Only after selection can you see the unit number and differentiate between the 2.
<img width="1567" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlAvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90497929204e54a5d824f2bf29ebbb5e707a3aa7/image.png" alt="image.png" />

**Tasks**
- [ ] Display the unit number in the worksite selection dropdown
- [ ] Display as "Unit# dash Street Number  Street Name City" EXAMPLE: "1301 - 865 Hornby Vancouver"
- [ ] Remove "Canada'/country from the worksite selection dropdown display

**Acceptance Criteria**
Worksite selection Dropdown displays
- [ ] Unit #
- [ ]  Street # 
- [ ]  Street name
- [ ]  City
  
DOES NOT display
- [ ]  Country

**Comment by jerry-ey** [comment]
@Stella-Archer 
There is tech limitation of displaying dash "-". It will always display "-" even if there is no unit.
Are you ok with this?

<img width="629" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzB4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dce6ee302c42c703aa1945f4353bc294dd21b088/CleanShot%202024-04-03%20at%2013.05.59.png" alt="CleanShot 2024-04-03 at 13.05.59.png" />

**Comment by fazil-ey** [comment]
Solution - remove the dash and only have a space between unit number and street address

**Comment by ayushdamani** [comment]
Tested in TEST, all dash has been removed

**Comment by Stella-Archer** [comment]
<img width="1184" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHREQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af294bb78737d853e6a4fa862bb939412d1acfb6/image.png" alt="image.png" />
