### ISSUE TITLE
Cold/Flu: Display order of worksite Information

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1684]
**User Story**
“As a Admin or user I'd like to quickly scan and see worksite information so I can confirm all details are correct 
Currently Unit # is at the bottom where as as a user I read information Unit #, street #, Street Name and City
<img width="1569" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1QvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1cc761927f5a6b98333ed932512ebce691d8487/image.png" alt="image.png" />

**Tasks**
- [ ]  Move Unit Number to the first item In display
- [ ]  Arrange other values as shown: 

<img width="1569" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2ovQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c89bf6d2a97da34ca8015227d8f0b8005481a71f/image.png" alt="image.png" />

**Acceptance Criteria**
- [ ] Worksite address information is display in a conventional pattern in alignment with UX best practices

**Comment by ayushdamani** [comment]
The component has been moved ✔️

<img width="1167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmd3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9e69f5de954d12a5992da0a59e2e1576b30c2ca/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Looks good live!
<img width="1413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19faf67f74cc4c806b8ecfbc8cbc95f66160a01e/image.png" alt="image.png" />
[Uploading... image.png]

**Comment by Stella-Archer** [comment]
PO - Closing
