### ISSUE TITLE
COI: Building Front-end (employee pages)

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1698]
**User Story**
As an employee I want to see the Conflict of Interest have these pages so I can get fill out the form and submit it successfully.

**Tasks**
1. Build the first two pages of the form
2. Hyperlinks for Page 1:
- "Conflict of Interest Guidelines" - https://www2.gov.bc.ca/assets/download/91C81FC2530F4FE89A07A18961793F13
- "Review the Standards of Conduct" - https://www2.gov.bc.ca/gov/content?id=0F130A55BFDD4DA1B0ED7FA0AC8D3041
- "Third Party Authorization for Collection and Use of Personal Information" - https://www2.gov.bc.ca/assets/download/70F57B797A4341CE81B5E3DDC78907CE
- "ethics advisor" - https://www2.gov.bc.ca/gov/content?id=83A2B60ACB024A9EA47C5ABC89F709E6#EthicsAdvisors
- "Disclosing a Conflict of Interest: Political Staff Guideline & Disclosure Form." - https://www2.gov.bc.ca/assets/download/CF9B86A5567E40E5B541345F64D64B66
3. Hyperlinks for Page 2:
- "Standards of Conduct" - https://www2.gov.bc.ca/gov/content?id=0F130A55BFDD4DA1B0ED7FA0AC8D3041%20
- "Public Service Oath Regulation" - https://www2.gov.bc.ca/gov/content?id=CBF57D6FE75F4133A387C726DC0A8792
- "Standards of Conduct" - https://www2.gov.bc.ca/gov/content?id=0F130A55BFDD4DA1B0ED7FA0AC8D3041
4.  The three checkboxes on the second page needs to be checked before the employee moves to the next page - please make them a required field.

**Acceptance Criteria**
- [ ] Build the pages of the form, as per the screenshots below
- [ ] Make sure hyperlinks are working
- [ ] Make the three checkboxes on the second page mandatory 

<img width="852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzQ0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7feb93bd744a1551bba985891fd26612f90dec8/image.png" alt="image.png" />
____________________________________________________________________________________________________________________________________________________________________
<img width="783" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzg0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1623d8c924cecb01117560cbf1688e7792b61002/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
Please test

**Comment by ayushdamani** [comment]
@fazil-ey, I have reviewed the content on these two pages - I guess only a couple changes in periods are needed. Can you please confirm?

**Comment by ayushdamani** [comment]
Jerry can you remove the periods from the bullet points please?

**Comment by jerry-ey** [comment]
Reminder to myself: to enable showing this form as a normal user

**Comment by jerry-ey** [comment]
Reminder to myself: to enable showing this form as a normal user

**Comment by jerry-ey** [comment]
@ayushdamani  sorry, I am not sure what do you mean. Could you give me a screenshot and highlight it?

Do you mean this?
<img width="1398" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUJtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--728f42a684fe83c9dbea1d1d55ec744ddfa5c617/CleanShot%202024-04-16%20at%2009.53.03.png" alt="CleanShot 2024-04-16 at 09.53.03.png" />

**Comment by ayushdamani** [comment]
Yes, you're correct @jerry-ey

**Comment by jerry-ey** [comment]
Thanks, periods have been removed.

**Comment by ayushdamani** [comment]
<img width="1166" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkJ6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cdd7d6f545adc56c01c7d8c1dd18dc26f0d5912/image.png" alt="image.png" />

Jerry, could you please remove the period from this bullet point too?

**Comment by jerry-ey** [comment]
done

**Comment by ayushdamani** [comment]
Thanks, Jerry!
Over to you @fazil-ey

**Comment by fazil-ey** [comment]
looks good

**Comment by MikePSA** [comment]
In the COI Employee Acknowledgements tab, if I try to progress without ticking any of the checkboxes, it provides this error message at the top. The first part "employee acknowledgements select:" should be removed.
<img width="1376" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9sQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f36d3c6b6822d4f37eb2ad5be7700c76ed94c57e/image.png" alt="image.png" />
