### ISSUE TITLE
[Tool]: Testing PVC Storage Capacity Issue

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1728]
**User Story**
“As a Dev Ops expert I want understand the size and severity of issues with the PVC storage so I can am better informed on how to mitigate the issues.” 

**Tasks**
Steps needed to achieve this feature. 
- [ ] Step up on new name space
Get data analytical about: 
- [ ] load issues
- [ ] forms #

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] End-to-end functional testing 
- [ ] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team

**Comment by Stella-Archer** [comment]
@warrenchristian1telus could you flesh out this ticket withh details on what all you need for data and how you will proceed?

**Comment by warrenchristian1telus** [comment]
@Stella-Archer I think we'll need to expand this beyond PVC storage to get the environment into better shape, and allow for any scaling. It may confuse things to break it out into multiple tickets in this case (PVC's, memory, CPU).

# Cluster Sizing Strategy

To determine the right size for our pods / services,
we will need to document and review the information available,
to create a plan for future sizing / scaling. This is intended
to optimize resource usage, and increase reliability.

## Current Sizing

@bhumin-fw Can you assist with details for #1?

1. What has traffic been like over the past year?
  - How many forms submitted per month?
    - Busiest days / months
  - Issues related to high traffic (Cold/Flu form release)
    - What and when were the Issues?
    - How many users were affected?
2. What is the current infrastructure?
  - How many pods are currently running (16)?
  - What is the current size of the pods (request / limit)?
  - What is the current size (request / limit)?
    - Databases (Mongo: 715 of 8192 x3, Patroni: 1557 of 5120 MiB x2)
    - Files (3809 of 10240 MiB)
    - Backups (55 of 5120, 144 of 5120 MiB)
    - Cache/Redis (2.56 of 512 MiB)
3. What is the current performance of the pods?
  - Are they running at capacity?
4. Identify any bottlenecks or resource creep
  - Are there any pods that are using more resources than they should
  - Are there any pods that are not being used?
  - Are any pods continuously growing in size / resource use?

The following table shows current resource usage, and will help
to identify and reallocate underutilized resources.

Sizing will be based on production usage statistics,
including PVC volumes, CPU and Memory usage.

I've started with a few pods, to establish the data points required,
and will add more as I gather the information.

Note that this the below tables are copied from a spreadsheet,
which will be updated as I gather more information.

### Capacity in Production

| Production           | Pod Count | Deployment Type  | Scaling | PVC Capacity (MiB) | PVC Used (MiB) | PVC Unused (MiB) | CPU Request (m) | CPU Limit (m) | Memory Request (M) | Memory Limit (M) | Max Used CPU (m) | Max Used Memory (M) | Unused Memory (M) | Unused CPU (m) |
|----------------------|-----------|------------------|---------|--------------------|----------------|------------------|-----------------|---------------|--------------------|------------------|------------------|---------------------|-------------------|----------------|
| forms-flow-documents | 1         | DeploymentConfig | None    | 10240              | 3809           | 6431             | 600             | 1400          | 3072               | 3072             | 325              | 2900                | 172               | 1075           |
| forms-flow-bpm       | 1         | DeploymentConfig | None    | 0                  | 0              | 0                | 100             | 400           | 1024               | 2048             | 13               | 850                 | 1198              | 387            |
| hamongo              | 3         | StatefulSet      | None    | 8192               | 716            | 22428            | 125             | 400           | 512                | 2048             | 27               | 689                 | 4077              | 1119           |
| TOTAL                | 5         |                  |         | 18432              | 4525           | 28859            | 825             | 2200          | 4608               | 7168             | 365              | 4439                | 5447              | 2581           |

# Projected Capacity

This table will be used to adjust sizing to better fit the needs of the project,
based upong recorded usage history in Sysdig, and projected requirements based on
shared load after scaling up deployments

| Projected            | Pod Count | Deployment Type  | Scaling |                    |                |                  | CPU Request (m) | CPU Limit (m) | Memory Request (M) | Memory Limit (M) | Max Used CPU (m) | Max Used Memory (M) | Unused Memory (M) | Unused CPU (m) |
| forms-flow-documents | 3         | DeploymentConfig | None    | 4000               | 3809           | 191              | 600             | 800           | 2048               | 2900             | 975              | 2900                | 0                 | -525           |
| forms-flow-bpm       | 3         | DeploymentConfig | None    | 0                  | 0              | 0                | 10              | 25            | 512                | 850              | 39               | 850                 | 0                 | -42            |
| hamongo              | 3         | StatefulSet      | None    | 1024               | 716            | 924              | 10              | 25            | 512                | 689              | 27               | 689                 | 0                 | -6             |
| TOTAL                | 9         |                  |         | 5024               | 4525           | 1115             | 620             | 850           | 3072               | 4439             | 1041             | 4439                | 0                 | -573           |

**Comment by warrenchristian1telus** [comment]
Update to the recorded and projected resource use:

| Production           | Pod Count | PVC Count | Deployment Type  | Scaling   | PVC Capacity (MiB) | CPU Request (m) | CPU Limit (m) | Memory Request (MiB) | Memory Limit (MiB) | PVC Used (MiB) | CPU Used (m) | Memory Used (MiB) | PVC Unused (MiB) | Memory Unused (MiB) | CPU Unused (m) |
|----------------------|-----------|-----------|------------------|-----------|--------------------|-----------------|---------------|----------------------|--------------------|----------------|--------------|-------------------|------------------|---------------------|----------------|
| forms-flow-bpm       | 1         | 0         | DeploymentConfig | None      | 0                  | 100             | 400           | 1024                 | 2048               | 0              | 400          | 820               | 0                | 1228                | 0              |
| forms-flow-documents | 1         | 0         | DeploymentConfig | None      | 0                  | 600             | 1400          | 3072                 | 3072               | 0              | 1970         | 2007              | 0                | 1065                | -570           |
| forms-flow-forms     | 1         | 0         | DeploymentConfig | None      | 0                  | 100             | 200           | 100                  | 2048               | 0              | 220          | 240               | 0                | 1808                | -20            |
| forms-flow-files     | 1         | 1         | StatefulSet      | None      | 10240              | 300             | 500           | 512                  | 1024               | 3840           | 530          | 200               | 6400             | 824                 | -30            |
| forms-flow-redis     | 1         | 1         | StatefulSet      | None      | 512                | 25              | 100           | 64                   | 256                | 3              | 80           | 76                | 509              | 180                 | 20             |
| forms-flow-web-api   | 1         | 0         | DeploymentConfig | None      | 0                  | 50              | 250           | 256                  | 1024               | 0              | 110          | 400               | 0                | 624                 | 140            |
| forms-flow-web       | 1         | 0         | DeploymentConfig | None      | 0                  | 100             | 200           | 100                  | 2048               | 0              | 20           | 69                | 0                | 1979                | 180            |
| hamongo              | 3         | 3         | StatefulSet      | None      | 24576              | 125             | 400           | 512                  | 2048               | 2121           | 70           | 615               | 22455            | 4299                | 330            |
| keycloak             | 2         | 0         | StatefulSet      | HPA (2-4) | 0                  | 100             | 400           | 1024                 | 1024               | 0              | 480          | 910               | 0                | 228                 | -80            |
| patroni              | 2         | 3         | StatefulSet      | None      | 15360              | 250             | 400           | 512                  | 512                | 4608           | 420          | 361               | 10752            | 302                 | -20            |
| mongodb-backup       | 1         | 1         | DeploymentConfig | None      | 5120               | 50              | 125           | 128                  | 256                | 144            | 260          | 256               | 4976             | 0                   | -135           |
| patroni-backup       | 1         | 1         | DeploymentConfig | None      | 5120               | 50              | 125           | 128                  | 256                | 144            | 150          | 24                | 4976             | 232                 | -25            |
| TOTAL                | 9         | 5         |                  |           | 60928              | 1850            | 4500          | 7432                 | 15616              | 10860          | 4710         | 5978              | 50068            | 12769               | -210           |
| USED %               |           |           |                  |           | 93%                | 46%             | 56%           | 45%                  | 48%                |                |              |                   |                  |                     |                |
| Projected            | Pod Count |           | Deployment Type  | Scaling   | PVC Capacity (MiB) | CPU Request (m) | CPU Limit (m) | Memory Request (MiB) | Memory Limit (MiB) | PVC Used (MiB) | CPU Used (m) | Memory Used (MiB) | PVC Unused (MiB) | Memory Unused (MiB) | CPU Unused (m) |
| forms-flow-bpm       | 3         | 0         | DeploymentConfig | HPA (3-6) | 0                  | 100             | 400           | 512                  | 850                | 0              | 1200         | 2460              | 0                | -4830               | -2400          |
| forms-flow-documents | 3         | 1         | DeploymentConfig | HPA (3-6) | 5120               | 600             | 1500          | 1024                 | 2048               | 0              | 5910         | 6021              | 5120             | -11919              | -13230         |
| forms-flow-forms     | 3         | 0         | DeploymentConfig | HPA (3-6) | 0                  | 25              | 200           | 150                  | 256                | 0              | 660          | 720               | 0                | -1392               | -1380          |
| forms-flow-files     | 3         | 1         | StatefulSet      | HPA (3-6) | 5120               | 25              | 500           | 165                  | 256                | 3840           | 1590         | 600               | 1280             | -1032               | -3270          |
| forms-flow-redis     | 3         | 3         | StatefulSet      | HPA (3-6) | 50                 | 50              | 80            | 64                   | 96                 | 9              | 240          | 228               | 141              | -396                | -480           |
| forms-flow-web-api   | 3         | 0         | DeploymentConfig | HPA (3-6) | 0                  | 25              | 110           | 384                  | 512                | 0              | 330          | 1200              | 0                | -2064               | -660           |
| forms-flow-web       | 3         |           | DeploymentConfig | HPA (3-6) | 0                  | 10              | 20            | 64                   | 96                 | 0              | 60           | 207               | 0                | -333                | -120           |
| hamongo              | 3         | 3         | StatefulSet      | HPA (3-6) | 1024               | 50              | 70            | 512                  | 650                | 6363           | 210          | 1845              | -3291            | -3585               | -420           |
| keycloak             | 3         | 0         | StatefulSet      | HPA (3-6) | 0                  | 250             | 450           | 900                  | 1024               | 0              | 1440         | 2730              | 0                | -5118               | -2970          |
| patroni              | 3         | 3         | StatefulSet      | HPA (3-6) | 2048               | 250             | 350           | 250                  | 400                | 13824          | 1260         | 1083              | -7680            | -2049               | -2730          |
| TOTAL                | 27        | 11        |                  |           | 13362              | 1385            | 3680          | 4025                 | 6188               | 24036          | 12900        | 17094             | -4430            | -32718              | -27660         |
| DIFFERENCE           |           |           |                  |           | 47566              | 465             | 820           | 3407                 | 9428               | -13176         | -8190        | -11116            | 54498            | 45487               | 27450          |
| CLUSTER CAPACITY     |           |           |                  |           | 65536              | 4000            | 8000          | 16384                | 32768              |                |              |                   |                  |                     |                |
| USED %               |           |           |                  |           | 30%                | 35%             | 46%           | 25%                  | 19%                |

**Comment by fazil-ey** [comment]
Cluster right sizing - https://bcgov-my.sharepoint.com/:x:/r/personal/warren_christian_gov_bc_ca/Documents/OpenShift%20Cluster%20Right-Sizing.xlsx?d=wc236a0748a5c4b2fae7c9f2f393af8ce&csf=1&web=1&e=quuzyQ
OpenShift Cluster Right-Sizing.xlsx

**Comment by MeghanStothers** [comment]
@warrenchristian1telus Hi there - can you add the latest notes here so I can keep an eye on this issue.
