### ISSUE TITLE
[All Forms]: Communication about OCI production cut over (July 18-22)

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1794]
**User Story**
“As a from owner I want know and be prepared for the OCI public deployment so I can make sure my users are prepared for any interruption in service” 

**Tasks**
- [x] Connect with communications for the larger project to confirm consistent messaging
- [x] Inform each form owner of the cut over weekend dates, what to expect
- [x] Develop mitigation strategies that will work best for each form/process
- [x] Mar Par - Alert on Careers and MyHR site (mat/Par page) articles in compass
- [x] Telework - Alert on Careers and MyHR site
- [x] Cold and Flu
- [x] 1.10 Bullying & Harassment - Alert on Careers and MyHR site
- [x] CoI
- [x] ERIP (Maybe not impacted)
- [x]  Alert message on Digital Journeys PROD
- [x]  Follow up with all clients and stakeholder on migration status, testing submitted their way

**Acceptance Criteria**
All form owner are aware and have had input into mitigation of service interuptions.
- [x] End-to-end functional testing 
- [x] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team

**Comment by Stella-Archer** [comment]
Mat/Par is looking for messaging on topic pages in 'Careers and MyHR' site as well as DJ home

**Comment by Stella-Archer** [comment]
Telework, CoI and "1.10 Bullying & Harassments" have no concerns with being down for this short window.
they are also looking for messaging on topic pages in 'Careers and MyHR' site as well as DJ Alerts for supervisors going directly into DJ to approve requests

**Comment by Stella-Archer** [comment]
https://bcgov.sharepoint.com/:w:/r/teams/03991/Shared%20Documents/General/Communication%20and%20Change%20Management/Digital%20Journeys%20OCI%20Messaging.docx?d=w1b8e1e39373843338e70fa7f851c09f6&csf=1&web=1&e=eiTts2

**Comment by Stella-Archer** [comment]
Message for alert banner is in ticket #1847

**Comment by Stella-Archer** [comment]
Alert Banners are now live on these Career & MyHR pages:
Maternity: https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/leave-time-off/maternity-parental-pre-placement-adoption/maternity
 
Parental leave: https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/leave-time-off/maternity-parental-pre-placement-adoption/parental
 
Telework: https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/work-arrangements/flexible-workplaces/get-started-with-flexible-work-in-the-bc-public-service/submitting
 
B/H: https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/working-with-others/address-a-respectful-workplace-issue/launch-a-formal-complaint
