### ISSUE TITLE
Telework: Selenium Scripts

### ISSUE THREAD

**Issue by MikePSA** [bcgov/digital-journeys#1796]
**User Story**
As a tester, I want to use Selenium to automate testing so I can increase test coverage and efficiency.

**Tasks**
1. Choose between Selenium IDE vs WebDriver 
2. Determine Telework test scenarios
3. Create test scripts for scenarios
4. Test the scripts

**Acceptance Criteria**
- [ ] Selenium application is chosen
- [ ] Telework test scenarios are determined
- [ ] Scripts function as designed

**Comment by MikePSA** [comment]
After discussing with Andrew and Fazil, Telework test scenarios were determined as below:

1. Submission with less than 3 days
2. Submission with more than 3 days Approved (file upload required)
3. Submission with more than 3 days Denied (No file upload required)
4. Draft submission to success page
5. Supervisor delete button 
6. Date (if edited, should revert to current date)
7. Mandatory fields
8. Prepopulated fields

If there are other Telework scenarios anyone would like tested, please let me know.

**Comment by MikePSA** [comment]
After team discussion, the current goal is for scripts to be used for pre-deployment testing in the TEST environment. Post deployment scripts is a great idea but will take extra steps and may be looked at later down the line. 

Stella will look into dummy accounts for testing.

I am figuring out the best approach to provide access to Selenium scripts and how others can use them.

**Comment by MikePSA** [comment]
Selenium setup test with Ayush went fairly well. We could run scripts, but not get pass the login section. IDIR SSO would redirect to login page, requiring username and password.

**Comment by ayushdamani** [comment]
Fazil or Stella will also test the scripts - Mike is available for help!

**Comment by Stella-Archer** [comment]
Testing - these are web Driver file look at manual for webdriver - install Python to test

**Comment by Stella-Archer** [comment]
@MikePSA I'm having some difficulties with getting the scripts running - oddly enough I can see it open up the cold and flu form not Telework - what am I doing wrong here?
<img width="314" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6716a10c2d1f704b6b8f291d53964354074f79cc/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
@Stella-Archer  to continue test this ticket

**Comment by Stella-Archer** [comment]
https://bcgov.sharepoint.com/:f:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Telework/Telework%20WebDriver?csf=1&web=1&e=Og7PDQ
