### ISSUE TITLE
[Cold and Flu]: JUNE 8 - Data clean up in prep for Launch

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1797]
**User Story**
“As a Cold and Flu program administrator, I want to clean up all the test data in PROD so I can be sure all the data received after June 10 is from real clinic applicants.” 

**Tasks**
- [ ] Clean out all test data on the production environment on June 8
- [ ] June 10, just before site goes live check and confirm there is no remaining test data
- [ ] If testing happens during deployment remove that data as well

**Acceptance Criteria**

- [ ] Confirm there is no cold and flu data in DJ PROD environment 
- [ ] Confirm data has been cleaned out of the BI environment with the BI/DIO team

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Cleaning up test data on June 8**
  - Given the Cold and Flu program administrator is responsible for cleaning up test data
  - When they clean up all test data in the production environment on June 8
  - Then there should be no cold and flu data left in DJ PROD environment
- [ ] **Scenario: Confirming no remaining test data on June 10**
  - Given the site is going live on June 10
  - When the program administrator checks for any remaining test data before launch
  - Then there should be no cold and flu data left in DJ PROD environment
- [ ] **Scenario: Removing testing data during deployment**
  - Given testing happens during deployment
  - When the program administrator removes that data as well
  - Then there should be no cold and flu data left in DJ PROD environment
- [ ] **Scenario: Confirming data clean up with BI/DIO team**
  - Given the Cold and Flu program administrator is working with the BI/DIO team
  - When they confirm that data has been cleaned out of the BI environment
  - Then there should be no cold and flu data left in the BI environment

**Comment by MikePSA** [comment]
@mikeshi-bcgov to clean out ODS data in production

**Comment by mikeshi-bcgov** [comment]
@MikePSA To confirm we only need to clean up test records in "Registrations", leave records in "Contacts", "Minitries", and "WorkSites" as is now?

**Comment by ayushdamani** [comment]
@Stella-Archer can you please check in with Heather to understand what needs to be cleaned up?

**Comment by mikeshi-bcgov** [comment]
Records in table "Registrations" has been cleaned up with today's change.
