### ISSUE TITLE
[tool]: OCI testing

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1851]
**User Story**
“As a platform we want tp makes sure our data migrates to the OCI successfully so we do not have error in any of our forms.” 

**Tasks**
- [x] end to end 'smoke' testing on July 21
- [x] login to Production environment as before, confirm Login success
- [x] See new User Interface of OCI​ note any issues or impact top DJ app
- [x] Navigate through all aspects of applications​, drafts, PDF, 
- [x] Confirm Application Functionality is working as Expected​
- [x]  log results in [OCI TEAMS planner board](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_1504532429?context=%7B%22channelId%22%3A%2219%3AQToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1%40thread.tacv2%22%7D&tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc)

Planner has Scripts/scenarios for each form :
- [x] [Telework](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:QToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1@thread.tacv2_p_8UlhXgtoGUaGboeDfEuJYWUAGQlQ_h_1719432989136?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2F8UlhXgtoGUaGboeDfEuJYWUAGQlQ%2Ftask%2FjBud108S4EW0onNjfxV8R2UALC64%22%2C%22channelId%22%3A%2219%3AQToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1%40thread.tacv2%22%7D) 
- [x]  [Maternity Parental Leave](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:QToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1@thread.tacv2_p_8UlhXgtoGUaGboeDfEuJYWUAGQlQ_h_1719432989136?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2F8UlhXgtoGUaGboeDfEuJYWUAGQlQ%2Ftask%2FhyzlxewevEasAUTU37s_rmUAPupX%22%2C%22channelId%22%3A%2219%3AQToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1%40thread.tacv2%22%7D)
- [x]   [1.10 Bullying and Harassment](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:QToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1@thread.tacv2_p_8UlhXgtoGUaGboeDfEuJYWUAGQlQ_h_1719432989136?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2F8UlhXgtoGUaGboeDfEuJYWUAGQlQ%2Ftask%2FaU0V3Y1OhkeaVaSybev_a2UAM4dZ%22%2C%22channelId%22%3A%2219%3AQToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1%40thread.tacv2%22%7D)
- [x] [Cold and Flu](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:QToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1@thread.tacv2_p_8UlhXgtoGUaGboeDfEuJYWUAGQlQ_h_1719432989136?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2F8UlhXgtoGUaGboeDfEuJYWUAGQlQ%2Ftask%2FzdBrcwc7d0iCXlunSEy2c2UANKW-%22%2C%22channelId%22%3A%2219%3AQToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1%40thread.tacv2%22%7D)
- [ ] [SL (https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:QToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1@thread.tacv2_p_8UlhXgtoGUaGboeDfEuJYWUAGQlQ_h_1719432989136?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2F8UlhXgtoGUaGboeDfEuJYWUAGQlQ%2Ftask%2Foc8r6ceYrUyYdRMfn065HmUAO8m_%22%2C%22channelId%22%3A%2219%3AQToQ8MfLzxGD0FByUjLSzpVMB3sNdwljT1aQ-DBOL9Q1%40thread.tacv2%22%7D)
- [x] executed scenarios
- [x] log results 
- [x] coordinate and confirm test results delivered to BI 
- [x] confirm test result delivered to CRM

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [x] End-to-end functional testing 
- [x] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team

**Comment by Stella-Archer** [comment]
@bhumin-fw  will check with Patrick to confirm the URL change, which will determine if we need developers at the test

**Comment by fazil-ey** [comment]
split the remaining work here to #1865. We can close this
