### ISSUE TITLE
[Tool]: OCI cutover weekend 'closing'

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1852]
**User Story**

“As a platform we want to put the platform in a 'close for maintenance' state so clients do not work on forms while cData is being redirected to OCI.” 

**Tasks**
- [x] Confirm with all clients close window will work for them
- [x] set up alert messages on the DJ platform
- [x] set up alert messages in Careers and MyHR where client access DJ forms
- [x] explore what the closed platform will look like - _testers: Meghan, Mike Stella + core team will need access to PROD for testing, Regular employees should not see anything in forms, drafts, submitted or Review and process tabs_
- [x] 'close platform' end of day July 18
- [x] 're-open' platform noon July 22

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [x] End-to-end functional testing 
- [x] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team

**Comment by Stella-Archer** [comment]
@patrick what changes to make on our end
make form public checked 'no'

**Comment by Stella-Archer** [comment]
@bhumin-fw do we need to do any config on saturday for cut over? YES!!
Afte Patrick is done
start server with new config
check
check with Kanal or Warren
can't get into OCI team channel 
if there is a roll back Bhumin can reconfig on Monday AM
