### ISSUE TITLE
[CoI]: PIA

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1862]
**User Story**
“As a Product, and Form Owner I want to a Privacy Impact assessment so I can ensure the privacy of my for users is secure>.” 

**Tasks**
Steps needed to achieve this feature. 

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] End-to-end functional testing 
- [ ] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team

**Comment by Stella-Archer** [comment]
Sean has share current PIA https://bcgov.sharepoint.com/:b:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/PIA/PIA%20re%20COI%20disclosure%20form_%20signed.pdf?csf=1&web=1&e=tRxcdX
and ammendment with us https://bcgov.sharepoint.com/:b:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/PIA/Scan_20180525%20(002).pdf?csf=1&web=1&e=AjwIRg
It does not describe the digital for at all so we will have to:
- [ ]  document digital form process
- [ ]  - supply screen shots of new version
- [ ]  send it back to program area to update

**Comment by Stella-Archer** [comment]
Discovered a more recent PIA 'PAS18006' may have digital reference - connected with Raman about this

**Comment by Stella-Archer** [comment]
Contacted Jenn O to get a digital copy of 18006

**Comment by Stella-Archer** [comment]
Edited update suggestions and screenshots, sent back to Sean & Raman
