### ISSUE TITLE
ERIP: PIA for Early Retirement Incentive Form

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1863]
**User Story**
“As a Product, and Form Owner I want to a Privacy Impact assessment so I can ensure the privacy of my for users is secure>.” 

**Tasks**
A PIA is required to be signed off before go-live, I don't see a PIA attached to the current Orbeon form 

Tasks

 - [x] Check with form owner to see if there is an existing PIA for the ERIP form
 - [x] Update any pre-existing ERIP PIA for Digital Journeys process
 - [x] If there is not an existing PIA for ERIP, use Digital Journey PIA template to create https://bcgov.sharepoint.com/:f:/r/teams/03991/Shared%20Documents/General/PIA?csf=1&web=1&e=XOJwj4 
 
PIA with things we need to change highlighted - https://bcgov.sharepoint.com/:b:/r/teams/03991/Shared%20Documents/Early%20Retirement/PIA/Gaps%20Highlighted%20-%20PSA23019%20-%20ERIP%20Program%20and%20Digital%20Form%20%20-Final.pdf?csf=1&web=1&e=H3Yz9p

- [x]  Submit PIA to Privacy team
- [ ]  Get PIA sign off

Acceptance Criteria
- [ ] PIA is signed off by privacy team to move forward with go-live.

**Comment by Stella-Archer** [comment]
Original, signed ERIP PIA is here > https://bcgov.sharepoint.com/:b:/r/teams/03991/Shared%20Documents/Early%20Retirement/PIA/PSA23019%20-%20ERIP%20Program%20and%20Digital%20Form%20-Final.pdf?csf=1&web=1&e=E46r64 
we will need to review and make updates reflecting Digital Journey Process

**Comment by Stella-Archer** [comment]
- [ ]  Review Darin's PIA for changes in process/tech 
- [ ]  update areas indicated this new procedure/technology descriptions
- [ ]  Add screens to replace Orbeon material
