### ISSUE TITLE
[CoI]: Set up UX testing for LDB

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1873]
**User Story**
“As a LDB employee I want be sure I can access Digital Journeys and the CoI form sso I can get report my conflict and the LDB team receives them.” 

**Tasks**
- [ ] Confirm access 
- [x] move to PROD 
- [x] make key cloak group for LDB users
- [ ] confirm flow to DJ box
- [ ] switch flow to final recipient
- [ ] test recipient receives submissions successfully

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] End-to-end functional testing 
- [ ] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team
