### ISSUE TITLE
[Tool]: Selenium Validation of Mat/Par pages

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1885]
**User Story**
“As a Selenium Test builder I want have scripts that test the validation on individual pages so I can isure pages are validating correctly.” 

**Tasks**
- [ ] Identify pages that need validation
- [ ] Id items on each page needing validation
- [ ] make ticket to coversituation as works best for builder

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] End-to-end functional testing 
- [ ] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team
