### ISSUE TITLE
[Tool]: SSL Certificate tracking

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1902]
**User Story**
“As a Product owner I want keep track of all SSL certificates for Digital Journey properties so I can be sure they do not accidently expire.” 

**Tasks**
The service management team has created a 1st draft list of all PSA SSL Certificates they need to keep track of. 
https://bcgov.sharepoint.com/:x:/r/teams/03991/Shared%20Documents/General/SSL%20Certificates/WP_PSAtest1710946974_1kconcepc_WP.xlsx?d=waf7437794ab44d919f8e9ca59a3fa042&csf=1&web=1&e=OJ3ToC

- [x] review list 
- [x] note any DJ SSLs that are not on list 
- [x] Add to draft
- [x] create separate page in xl doc with just DJ certs so we can keep an eye on/schedule reminders for our own certificates
- [ ] document procedure for certificate renewal 
- [ ] create team back ups/delegates to follow up on or process renewals o we do not have a single point of failure
- [ ] create how to/knowledge transfer guide

**Acceptance Criteria**
- [ ] SSL certificate process and schedule is transparent and visible to the whole team
- [ ] PSA service partners are informed
- [ ] The team is aware of what needs to happen & when
- [ ] reminders for action are sent in a timely manner

**Comment by Stella-Archer** [comment]
@warrenchristian1telus could you help get at list to us so we can start on this
I'l like to get notifications too

**Comment by warrenchristian1telus** [comment]
Sure @Stella-Archer - the first [free] option would be to just set calendar reminders, but of course those could be neglected down the road, and may not be so reliable with changing teams, etc..

- [UptimeRobot](https://uptimerobot.com) offers SSL monitoring with their paid subscriptions (starting at $7/month).
- [TrackSSL](https://trackssl.com) offers monitoring for 2 certs for free, or $17/month for up to 20

I am also looking at integrating this into our GitHub Actions / deployments, along with Rocket.Chat notifications. This way, we should be able to notify the relevant group all at once. It should also be somewhat easier to manage team adjustments/subscriptions this way. This may also let us automatically create/assign an issue to handle the update (and escalation if required) at the appropriate date/time.

The main certificate will expire: **Sun, 08 Sep 2024 16:52:28 GMT**

For now, I've setup a reminder in my calendar with a notice a week ahead.

I would like to caution that alerts may get a bunch of people searching for a solution, when we usually get the certificates delivered just ahead of expiry, so we may want to take some care and planning to avoid escalation if there is no [real] issue. Although this is largely what we tried last time, and didn't get them in time. Maybe we should coordinate / document proper escalation procedures / timings with the appropriate groups.

**Comment by warrenchristian1telus** [comment]
I just realized that date above is wrong [08 Sep 2024]... but that's what I copied from the live site. Investigating...

**Comment by warrenchristian1telus** [comment]
Somehow it seems to have been cached in my browser. Actual expiry will be: Tue, 09 Sep 2025 22:26:36 GMT

**Comment by Stella-Archer** [comment]
Thanks for looking into this @warrenchristian1telus I see they've noted keycloak and silver devops in the spread sheet and the Sept 9/10 2025 expiry date but I'm wondering if this covers all our sites (test/dev/ new namespace) and if there is other certificates I'm not see we should be documenting and monitoring
<img width="888" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmNXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b016de8f553afdbba8f9a26c65d794de2f1391dc/image.png" alt="image.png" />

**Comment by warrenchristian1telus** [comment]
@Stella-Archer Here is the full list, with expiration dates. Most of them are Sept. 9th, but there are a couple of outliers. At least they are all in the same week. Hopefully we can get them all in time to update at once anyway.

digital-journeys-analytics-prod.apps.silver.devops.gov.bc.ca: Tue, 09 Sep 2025 22:39:55 GMT
digital-journeys-camunda.apps.silver.devops.gov.bc.ca: Tue, 09 Sep 2025 22:23:49 GMT
digital-journeys-files.apps.silver.devops.gov.bc.ca: Tue, 09 Sep 2025 22:20:57 GMT
digital-journeys-forms-flow.apps.silver.devops.gov.bc.ca: Tue, 09 Sep 2025 22:34:43 GMT
digital-journeys.apps.silver.devops.gov.bc.ca: Tue, 09 Sep 2025 22:34:43 GMT
digital-journeys-keycloak.apps.silver.devops.gov.bc.ca: Tue, 09 Sep 2025 22:34:43 GMT

digital-journeys-forms-flow-docs.apps.silver.devops.gov.bc.ca: Wed, **10** Sep 2025 18:04:22 GMT

digital-journeys-forms-flow-api.apps.silver.devops.gov.bc.ca: Fri, **12** Sep 2025 22:18:02 GMT

**Comment by ayushdamani** [comment]
How do we make this a transparent process?

**Comment by Stella-Archer** [comment]
Thanks @warrenchristian1telus  I've updated the spreadsheet with this info, they are asking about contact info , who to send notification to and Cert name, any info about this?
Aslo the 2 cert they did have had C Brown and D Vinkal as contacts on TES side I don't know them should they there, how do they fit into the process? 
<img width="1392" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtiQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--172ddc369cd0d838a9ec0f73953f156d21d106da/image.png" alt="image.png" />

**Comment by warrenchristian1telus** [comment]
Sure thing @Stella-Archer - Chris Brown is the primary contact for all things SSL on our side. I believe we should likely keep it this way, at least for now. There are many certificates to manage in total, so if we are to diversify the primary contacts, we'd need a reliable way to manage it all and keep things up-to-date.

I wonder if anyone on Rocket.Chat #devops-how-to can give us any recommendations? I've posted in inquiry, and will update here if we get any interesting responses.

**Comment by Stella-Archer** [comment]
I've sent back our completed SSl domain list to Sarah K group, asking about their role, and expectations of us in the processes moving to closed
