### ISSUE TITLE
[CoI]: Supervisor Email update

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1916]
**User Story**
“As a supervisor I want understand the steps required of me so I can processes the disclosure quickly and easily.” 

**Tasks**
- [x] Change the language in the Supervisors advice email to :

This is to inform you that a new Conflict of Interest Disclosure form has been submitted by <Name of disclosing employee> and is ready for your review. 
The form can be found in the "Review & Process" tab on **Digital Journeys**. After you review the employee’s disclosure, make a decision regarding how it will be addressed, summarize this decision in the disclosure form and then submit, the completed disclosure form will be automatically sent to AskMyHR for inclusion on the employee's personnel file. After submission you will receive a confirmation from AskMyHR that the service request has been created.

- [x] Link "Digital Journeys" to the review and process tab >  https://digital-journeys.apps.silver.devops.gov.bc.ca/task

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] End-to-end functional testing 
- [ ] End-to-end UX testing

**Comment by ayushdamani** [comment]
Thanks Andrew!
<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUZiQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d1b33d2197a8eb639deaaee6e05bb909de8a2af/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
