### ISSUE TITLE
Mat/Par: Communication about supervisor date amendments

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1924]
**User Story**
“As a supervisor, I need instructions on how to amend dates so I can easily change them in a submitted form, without contacting the Contact Centre.

**Tasks**
The current email has the following instructions:
"As the supervisor you can make limited changes to the form on behalf of the employee. You can update the leave start date, length of leave and parental leave allowance dates. You can access the form in the "Review & Process" tab on Digital Journeys."
- [x] Take screenshots to illustrate the above
- [x]  Write out instructive text
- [x]  Run the screenshots by Connie & Fazil
- [ ] Work with Karen's knowledge base team to update RG 4345

**Acceptance Criteria**
- [ ] Complete and test all tasks - test with contact centre
- [ ] RG 4345 updated and approved by Connie
- [ ] meets Contact centre/Users needs

**Comment by Stella-Archer** [comment]
1st Draft of supervisor instructions complete
https://bcgov.sharepoint.com/:w:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Supervisor_ChangeInstructions.docx?d=w1c39491e46a54c40890b09ecb6ee68fd&csf=1&web=1&e=iwAPlx
messaged Connie and @fazil-ey  to review

**Comment by Stella-Archer** [comment]
1st draft has been reviewed, updated and sent back for approval

**Comment by Stella-Archer** [comment]
@Stella-Archer Connie is working on this. Reassign the CRM ticket & Close?

**Comment by Stella-Archer** [comment]
Finished final screen shot and drafts reassigned CRM # 241101-000598 to Connie to update Guide RG 4345 updates
