### ISSUE TITLE
TELEWORK: Re-Name Task Tab

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#322]
**User Story**
As a manager/reviewer I want know where I am and what actions are expected of me, so I can  process an employee telework agreement efficiently as possible

**Tasks**
- [x] Change the label on the 'Task' tab to 'Review and Process Applications"

in all environments

**Acceptance Criteria**
- [x] tab now reads 'Review and Process Applications"
- [x] visible to manager/reviewer role
- [x] visible in TEST and PROD environments

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/51115a5f-edbc-44b9-8b50-1698e9cde2c8)

**Comment by iman-jamali-fw** [comment]
The logic for which tab is displayed to which roles will be implemented in #343. The estimate in this ticket only covers the text change.

**Comment by iman-jamali-fw** [comment]
Based on my discussion with @HasanSifat, the Reviewer/supervisor will see both the "Review and Process Applications" and "Forms" tabs.

**Comment by HasanSifat** [comment]
Slight change on this one, Reviewers/supervisors AND Submitters will both NOT have access to the Forms tab and will also NOT be able to see the tab once inside the formsflow tool/dashboard interface.

**Comment by david-sabadash** [comment]
Quick question about this ticket; What should be done about the text inside the previously named 'Tasks' tab? In the attached image, i'm referring to the text still showing 'Tasks'.
![image.png](https://images.zenhubusercontent.com/62b33d00d955ad0dc2151a98/7deafb1d-9cec-470c-ada0-9e6baa47bc7f)

**Comment by HasanSifat** [comment]
Hi David! Is it possible to take this popup box out completely? The tab name at the top is sufficient information for users. 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/8c3ff210-1df6-4d6b-95bc-90a157880b96)

**Comment by david-sabadash** [comment]
@HasanSifat definitely, i'll make the changes and note this conversation in the PR description

**Comment by HasanSifat** [comment]
thank you!

**Comment by Stella-Archer** [comment]
I don't see this in any environment
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/900fa08a-e547-446a-9901-2b92925a1e38)

**Comment by HasanSifat** [comment]
Tested successfully in TEST environment. ready to be deployed to PROD

**Comment by HasanSifat** [comment]
Tested successfully in PROD. Closing ticket!
