### ISSUE TITLE
TELEWORK: Documentation

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#323]
Draft copy of Document- https://bcgov.sharepoint.com/:w:/t/03991/EbrefQyeiq1BtLPmVn0jKMkBIe5eDzCUG4vculIYa78LSQ?e=Hba3ax

**User Story**
As an employee, manager, or ADM I may need additional instructions beyond what is available on the landing page and on the form itself. I would like to be able to access a PDF that provides more detail.

**Task List**
- [x] Determine a timeline for this project
- [x] Determine where we would like to post these instructions.
- [x] Check with the developers about the feasibility of posting them in the desired location.
- [x] Determine what employees, supervisors, and ADMs may need extra help on.
- [x] Write instructions for to expand on these areas. Include examples.
- [x] After drafting the instructions, have the writing team ensure they meet our communication standards.
- [x] Do final vetting of instructions.
- [x] Load the instructions

**Acceptance Criteria**
- [x] Instructions are posted for employees
- [x] Instructions are posted for supervisors
- [x] Instructions are posted for ADMs
- [ ] All three sets of instrutions are sent to Knowledge Management Team to help them with the creation of Topic Guides.

**Comment by MeghanStothers** [comment]
I check with the Karen's knowledge management team to advise them of launch date - Jana confirmed they do not link directly to the Telework form, but  rather we link to the Flexible workplaces for BC Public Service employees page.

I said we/team would advise her team once we have more details about which page the form will link from based on recommendations that are in progress for the Policy/PI team.

**Comment by MeghanStothers** [comment]
We/our team will look to see how and where we use this information developed by Alex:
Especially the ADM information, which will give them a sense of what is required of them

Possibilities 
- In Careers & MyHR web pages and/or FAQs
- An internal document for our team
- something for the Contact Centre and/or the Knowledgebase team/reports

**Comment by HasanSifat** [comment]
Updated document to add PSA branding and formalized the content. it is now ready to be shared to all stakeholders- https://bcgov-my.sharepoint.com/:w:/g/personal/hasan_sifat_gov_bc_ca/ESXWlASTH11CgI-CaGMmf8gB2Osr_QnLf8yNkVmolDKeYQ

**Comment by HasanSifat** [comment]
Here is a stakeholder analysis of this instruction manual- 
![Telework - Telework Instructions Manual Stakeholder Analysis.jpg](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/41de2182-d97c-4072-afec-cc4ef7a199fd)

**Comment by MeghanStothers** [comment]
@HasanSifat @Stella-Archer I have edited this doc (lightly) and offered it to PIE/policy team for their thoughts about where to post this, I propose we keep this as an internal document for now and share more broadly if we get feedback this technical info is useful for ADMs and/or users.

I will close this ticket for now and re-open if needed

**Comment by MeghanStothers** [comment]
I made further edits and Josh has also identified edits needed for consistency. 
This is a good resource t have on hand, we'll keep as an internal reference for now and modify  and distribute based on any client and/or user feedback.

closing ticket for now
