### ISSUE TITLE
TELEWORK: Improvements to Landing Page on Careers & MyHR

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#324]
**User Story**
As an employee, I will need additional information beyond what is currently on the landing page in order to be ready to complete the form. I also need to be warned about limitations of the system and problems under some circumstances. 

**Tasks**
- [x]  Messaging around the type of pre-work (approvals, costs) that should be done prior to filling out the form
- [x] Warning box that the form does not save and that it times out after an hour, and that using the back button or browsing away  causes you to lose content.
- [x] A note that you should discuss your proposed work schedule / duties with your supervisor before filling out the agreement. 
- [x] That you will need to know the name and email address of who the form will be sent to if it is not your supervisor. 
- [x] Your supervisor must be available to complete it within 30 days of you submitting it or you will lose your submission. 
- [x] Improve messages:
- [x] a. Warn that the employee portion is not yet optimized for mobile phones
- [x] b. Checklist before going to the form about what you need to have ready and what you need to do, such as discuss it with your supervisor
- [x] Information about how/what to obtain the ADM approval (ADM instructions) to sign off an application

**Acceptance Critera**
- [x] All tasks listed above are added to the Careers & MyHR Landing Page

**Comment by alexandralloyd** [comment]
Meeting with writer's team on Monday to discuss the proper landing page for the Telework form.

**Comment by MeghanStothers** [comment]
In progress - On July 20 Meghan emailed sent list of to-dos to Sean/Policy about the FAQs, Careers and MyHR web page, and recommendations to remove the links to the WORD form etc.

**Comment by HasanSifat** [comment]
Page is finalized. CMS Page still in QA

Ready to be closed once page goes live

**Comment by MeghanStothers** [comment]
Content has been reviewed and approved by PIE/Sean - okay to close this ticket.

FAQs are already live.
