### ISSUE TITLE
TELEWORK: Confirmation Page for Supervisor

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#326]
**User Story**
As a supervisor, I want to be taken to a confirmation page when I approve or reject a telework form so I can know my sign-off was successful.

**Tasks**

- [x]  Create confirmation page in all three environments

- [x] Redirect confirmation page after the supervisor clicks 'Submit' button in all three environments

- [x] Work with content team to write confirmation message for page

**Acceptance Criteria**
- [x] Confirmation page automatically appears when supervisor presses submit in all three environments

![SupervisorConfirmationPAge.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/7b6362dd-fa4a-4791-8433-3bfb752d2eb1)

**Comment by MeghanStothers** [comment]
Similar to ticket #327 - see details

**Comment by MeghanStothers** [comment]
Iman to look at Formsflow

**Comment by HasanSifat** [comment]
Hi @david-sabadash this one you can start looking at to solve

**Comment by MeghanStothers** [comment]
HERE IS THE STANDARD MESSAGE FOR THE CONFIRMATION PAGE: 
- please use BC Sans font if possible with a point size or 11 or larger


Thank you for submitting reviewing and completing this telework agreement request. 

The employee has been notified by email of your decision and has received a pdf copy of the completed telework agreement. 

You will receive by email a pdf copy of the Telework Agreement, as well as an attachment with ADM approval if the request was for three or more Telework days. 

The attachments can be stored in your personal files or according to your ministry's record-keeping policy.

For questions or feedback about the Telework agreement or other PSA forms, please [contact the Digital Journeys team](mailto:DigitalJourneys@gov.bc.ca).

**Comment by HasanSifat** [comment]
Hi @david-sabadash we had a review of the messaging on this confirmation window and wanted to make an update to the content. The updated messaging will be-

Thank you for reviewing and completing this telework agreement request.

The employee has been notified by email of your decision and has received a pdf copy of the completed telework agreement.

You will receive by email a pdf copy of the Telework Agreement, as well as an attachment with ADM approval if the request was for three or more Telework days.

The attachments can be stored in your personal files or according to your ministry's record-keeping policy.

For questions or feedback about the Telework agreement or other PSA forms, please [contact the Digital Journeys team.](DigitalJourneys@gov.bc.ca)

You may now close this window

**Comment by HasanSifat** [comment]
Also the "Application" tag on the top right needs to be removed as well @david-sabadash 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/01d9cbf6-def9-4e9f-b9db-3a8996a71a23)

**Comment by HasanSifat** [comment]
Tested Successfully in TEST! 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/c2c24fca-5208-4c4b-ad08-1c513ec6da7f)

Ready to be transferred in PROD!

**Comment by HasanSifat** [comment]
Tested successfully in PROD!
