### ISSUE TITLE
TELEWORK: Confirmation Page for Submitters/Employees

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#327]
**User Story**
As a an employee, I want to be taken to a confirmation page (rather than the Forms tab) after submission of my telework form so I know that my submission was successful.

**Tasks**

- [x] Confirmation page created in all three environments

- [x] Redirect to confirmation page when employee clicks 'Submit' button in all three environments

- [x] Confirmation page should include: a thank you message; a mention of forms timeline; instructions to contact supervisor if they have questions; mentions of the PDF that will be emailed to them; and a mention that supervisor has to approve submission.

**Acceptance Criteria**

- [x] Confirmation page appears after employee clicks 'Submit' in all three environments

- [x] Confirmation page mentions all necessary information seen in task 3

**Comment by MeghanStothers** [comment]
Iman: will look at component in Formflow that might work for this requirement

**Comment by alexandralloyd** [comment]
As per closed duplicate ticket #315:

The message could show something like this:
"Thank you for submitting for Telework Agreement, which has been emailed to your manager/delegate."

Optional wording? "You can check on the status of your submission by....?"

**Comment by Stella-Archer** [comment]
this should replace the green validation message after client submits

**Comment by HasanSifat** [comment]
Hi @david-sabadash another similar one for you to start looking at

**Comment by MeghanStothers** [comment]
For now, I suggest creating a generic request that will work with all approvals (rather than one requiring dev work/programmatic logic):

Please use BC Sans font at least 11 point size

Here is the standard message:

Thank you for submitting a telework agreement request. Your supervisor/delegate has been notified by email of your request. 

This email does not confirm approval of your telework request.

You will receive another email after your supervisor/delegate submits their decision. 

If you have not received an email confirming their decision within 15 days, please discuss the status of your telework agreement with them. 

Your request expires in 30 calendar days. If your request has not been processed within 30 calendar days you will need to submit a new request.

If you have any questions about the status of your telework agreement request, please check with supervisor or delegate.

For questions or feedback about the Telework form or other PSA forms, please [contact the Digital Journeys team](mailto:DigitalJourneys@gov.bc.ca).

**Comment by HasanSifat** [comment]
Hi @david-sabadash  we had a review of the messaging on this confirmation window and wanted to make an update to the content. The updated messaging will be- 

Thank you for submitting a telework agreement request. Your supervisor/delegate has been notified by email of your request.

This message does not confirm approval of your telework request.

You will receive another email after your supervisor/delegate submits their decision. with a pdf attachment of the completed submission. The pdf can be stored on your personal file or according to your ministry's record-keeping policy.

If you have not received an email confirming their decision within 15 days, please discuss the status of your telework agreement with them.

Your request expires in 30 calendar days. If your request has not been processed within 30 calendar days you will need to submit a new request.

If you have any questions about the status of your telework agreement request, please check with your supervisor or delegate.

For questions or feedback about the Telework form or other PSA forms, [please contact the Digital Journeys team.](DigitalJourneys@gov.bc.ca)

**Comment by HasanSifat** [comment]
Tested successfully in TEST! 

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/ec9ceaec-f5e0-43aa-949f-22690811ad6b)

Ready to be transferred to PROD!

**Comment by HasanSifat** [comment]
tested successfully in PROD 

ready to be closed
