### ISSUE TITLE
TELEWORK: Add Status of Application to Left-Hand Panel in Tasks

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#328]
**User Story**
As a supervisor, I want to see the status of the applications that have been assigned to me in the Tasks tab instead of my own email, so I can quickly see which applications I still have to approve. 

**Tasks**

- [ ] Removed supervisor/reviewer email from the from the left-hand panel in the Tasks tab in all three environments

- [ ] Add the status of the application (pending/approved/rejected) to the left-hand panel in the Tasks tab in all three environments 

**Acceptance Criteria**

- [ ] Supervisor/reviewer unable to see their own email in the left hand panel in the Task tab in all three environments

- [ ] Supervisor can see the status of the application, without clicking on the application, in the left hand panel in the Task tab in all three environments![StatusinTab.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/1ee70a5a-2b61-4b59-b7d6-1e422d6244ce)

**Comment by iman-jamali-fw** [comment]
@alexandralloyd Please note that the current behavior is that completed forms (Rejected/Approved) are disappeared from the Task list. Does this ticket want to keep all the submissions (for that supervisor) at any status (new/approved/rejected) in the Task list and instead add a status label to them?

**Comment by alexandralloyd** [comment]
@iman-jamali-fw I think we should keep the current behavior and only keep pending applications in the left hand panel. Just update them to only say "Pending".

**Comment by HasanSifat** [comment]
With technical complications to add this feature and also because the tool currently only holds pending applications in the left hand panel, it has been decided to not include this feature for launch. 

Removing MVP tags and transferring to product backlog pipeline to be looked at after soft-launch
