### ISSUE TITLE
TELEWORK: Change "Supervisor Reviews Submission" in Tasks Tab

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#330]
**User Story**
As a superviser/reviewer, I want each item to review in the left-hand panel in the Task tab to have a personalized title, so I quickly see which employee sent me an application to review. 

**Tasks**

- [x] Remove standard text of "Supervisor Reviews Submission" from each submission in the left-hand panel of the Tasks tab

- [x] Replace with "Review <Employee's Name> Request"

**Acceptance Criteria**

- [x] Supervisor/reviewer is able to see the customized title of "Review <Employee's Name> Request" in the left-hand panel of the Task tab for all the applications assigned to them in all environments![Reviewemployeesname.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/1690c538-e92f-43f4-b3dc-9055338b12e4)

**Comment by MeghanStothers** [comment]
Will this left hand column be visible to supervisors or will we be hiding this? If they can see the names, will they only see their reports (according to PPLsoft info?)

Looks like a useful addition - is this work critical launch?

**Comment by alexandralloyd** [comment]
@MeghanStothers Epics #335 and #331 address the left hand panel and the manager's task tab in general. At the moment we are working on the assumption that the left-hand panel will be visible for launch, but if it's easier to just hide it all we may have to do that. They should in theory only see the names of the employees who sent them tasks.

**Comment by simensma-fresh** [comment]
@david-sabadash I found that the Camunda task names accept variables, so we could do this by just updating the task name in the Camunda workflow to something like `Review ${name} Request`, which in turn will populate the name in that response. ![image.png](https://images.zenhubusercontent.com/61df28f84562db4e4d8e63d1/da444f4b-4b26-45a3-8728-a10771a7416c)

**Comment by HasanSifat** [comment]
Tested Successfully in TEST. 

All new submissions have an updated bolded header with the employees' name present in the title of the request. 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/4ebd9c2b-7666-47ed-a3cc-80e3cc1e8f32)

Ready to be transferred to PROD

**Comment by Stella-Archer** [comment]
Yaas this looks good
could we remove the email and the '#50' as well?
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/af9d33ae-c11a-43e8-9091-64ad807b89f2)

**Comment by david-sabadash** [comment]
@Stella-Archer Updated as per your previous comment! All changes should now be in DEV and TEST.

**Comment by alexandralloyd** [comment]
Changes working in TEST and DEV, ready to be pushed to PROD

**Comment by HasanSifat** [comment]
Tested successfully in PROD! 

Ready to be closed
