### ISSUE TITLE
TELEWORK: Remove Assignee from Top-Right of Tasks Area

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#333]
**User Story**
As a supervisor/reviewer, I want to only see information and options that are relevant to me in the Tasks tab, so that I can quickly and easily sign-off on forms.

**Tasks**

- [x] Remove the ability to change the assignee of the form from view for all environments (see picture)

- [x] Remove "Set follow-up date" and "Set due date" features from view for all environments (see picture)

**Acceptance Criteria**

- [x] Supervisor no longer sees an email address in the top right hand view of the Tasks tab for all environments

- [x] Supervisor no longer sees"Set follow-up date" and "Set due date" features in Tasks tab for all environments![remove.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/90174ee4-c084-49fc-aecc-89fd3b5acf35)

**Comment by HasanSifat** [comment]
Hi @david-sabadash all the changes are looking great! One small thing. Is there a way to remove the "Groups" button as well? We may not have specified this in the ticket but it needs to be removed along with all the changes you made related to this ticket. screenshot below- 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/4312846d-e133-442a-a4d8-387ba47d98fd)

**Comment by david-sabadash** [comment]
@HasanSifat absolutely, I can fix that. Thanks for pointing it out.

**Comment by david-sabadash** [comment]
@Stella-Archer the changes are now in TEST

**Comment by HasanSifat** [comment]
Tested successfully in PROD. Closing ticket!
