### ISSUE TITLE
TELEWORK: FormsFlow PIA

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#339]
**User Story**
As an employee, I want my completed form to be purged from the Formsflow system so I know my personal information is protected. 

**Tasks**

- [x] Investigate privacy implications of storing completed applications within Formsflow

- [x] Write business rules for when completed and incomplete applications should be purged from the system

- [x] Get approval from client for these business rules

- [x] Liaison with PMO to make sure business rules met legal standards

- [x] Update PIA (if need be) 

**Acceptance Criteria**

- [x] All above tasks are complete

- [ ] Business rules met legal security and privacy requirements

**Comment by iman-jamali-fw** [comment]
@alexandralloyd Sure, can you please give me more details before I can estimate? Thank you

Are we deleting the submissions **as soon as** the workflow ends (Rejected/Approved for Telework)? Or it is a batch delete after a certain time interval? 

What involves in terms of UI/UX for deletion? things such as showing a notification on TOOL that says it is deleted or any plan to send email to users?

**Comment by alexandralloyd** [comment]
@iman-jamali-fw We'll be notifying employees that once they finish the application and it is approved/rejected that the application will be automatically deleted via the front end of the form, the landing page, and the email after submission. 

For the pending applications that don't get approved/denied, tentatively we wanted to have these batch deleted after 30 days. This information will be communicated to managers in their notification email. 

We don't anticipate the need for any in tool notification of the deletion of the form to the users (manager/employee).

**Comment by iman-jamali-fw** [comment]
So dev work for this ticket would be:
- Delete completed submissions (On complete)
- Delete pending submissions after 30 days ( supervisor will be notified by an email)

**Comment by MeghanStothers** [comment]
Hi Alex, I believe we will need to update/amend the PIA (and or FOIPPA statements?) with some language such as.... 

Completed Telework forms are those that have an approved or rejected status. Completed Telework forms will be deleted/nor stored in the formsflow Application.  

Incomplete/pending applications that don't get approved or are denied will be batch deleted after 30 days. (Where would these one get stored until then?)

I don't believe we need the client's approval about the 30 days, but I will check with Sean/Policy. 

Suggestion only: The email language say something like: Your Telework submission was not completed and is no longer available. Please resubmit a new Telework agreement...."

**Comment by Stella-Archer** [comment]
PIA with Jennifer, will need to be resigned but doesn't anticipate it will impact timeline.

**Comment by Abuchana** [comment]
@alexandralloyd, once the MPO signs it, do we have to get Rueben to resign it? If so, we should leave the ticket open, if not, I think we can close it.

**Comment by Stella-Archer** [comment]
waiting for Dwayne/Reuben signature before closing

**Comment by MeghanStothers** [comment]
@alexandralloyd Can you share an update where the PIA is now - is it with Jennifer/Privacy?

**Comment by alexandralloyd** [comment]
@MeghanStothers Still waiting for MPOs signatures

**Comment by MeghanStothers** [comment]
Confirmed with Igor it is okay to change Indy's name to Rueben Bronee. Meeting arranged by Nass

**Comment by MeghanStothers** [comment]
Updated PIA signed by Rueben and will be saved to the Teams folder .

Our team is waiting for OCIO approved list of gov't domains from Nic Berry and Igor Krasnov about approved gov’t email addresses/domains for sending personal information – captured in pdf versions of the digital telework form – across the internet. They confirmed we are clear to launch on August 2. 

Our team has one further piece of technical work to do before launch to potentially restrict some email domains outside the gov’t network. Our goal is to make as many email addresses available as possible within the digital form, in addition to all “gov.bc.ca” ones. 

Meghan/Alison to advise Rueben and Sean know of any groups that might be restricted from completing the digital Telework form.  

Igor and Nic noted further PIA/STRA updates will likely be requested post-launch.
