### ISSUE TITLE
TELEWORK: Add Preamble to Form

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#342]
**User Story**
As an employee, I want to see warnings about the inability to save unfinished forms so I know that I have to finish the form in one sitting. 

**Tasks**

- [x] Add warning box to the top of form in all three environments

- [x] Preamble in warning box should include: when the system will kick you out; that users cannot save forms; that the form is a legal document; the form's expiry date. 

**Acceptance Criteria**

- [x] Preamble is visible to all users in all three environments

- [x] Preamble includes everything from task 2

**Comment by alexandralloyd** [comment]
Just add a text box to the top of form from the front end.

Need to connect with @LeeAnnYearley and @brookeish about writing the preamble.

**Comment by alexandralloyd** [comment]
Preamble will read:

Before you begin this form, please be aware:

- Be prepared to spend 30 minutes to complete and submit the digital telework agreement
- This request must be finished in one session, you cannot save your progress
- The session will timeout after one hour of inactivity
- This form is a legal document
- Y

our telework agreement will be valid for one year after the date it is signed

**Comment by alexandralloyd** [comment]
Added to DEV

**Comment by MeghanStothers** [comment]
We previewed this "preamble" box at our July 4 meeting with Jill Bryant/PIE. We agreed on a few changes to rename the box "Before you begin" etc. We make these changes and run the content by Sean/PIE for approval and then close this ticket (after making sure the content appears in all three environments.) Thanks

**Comment by alexandralloyd** [comment]
Made changes and sent to Sean to review on 07/05

**Comment by HasanSifat** [comment]
All changes present in DEV, TEST & PROD
