### ISSUE TITLE
TELEWORK: Establish Logic to assign roles to users coming into PROD & TEST (client/employee vs reviewer/manager/supervisor)

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#343]
**User Story**
As a user coming into the TEST & PROD Environment, I should be getting 2 separate interfaces depending on the role assigned to my profile in the tool. The tool needs to be able to differentiate between users coming in as Clients/submitters/employees vs coming in as reviewers,/managers/supervisors.  This will help so that I am not confused with seeing unnecessary information in the tool interface and also as a client/submitter I am not able to see the tasks tab. 

**Tasks**

- [x] Create a logic within the tool so that it can differentiate users between clients and reviewers using the IDIR as the unique identifier. 
 A discussed solution during the grooming session was to apply the logic that- If one or more submissions are assigned to a specific idir, then that idir coming into PROD & TEST will be given a reviewer role. If not then a client. 

**Acceptance Criteria**

- [x] This issue will be defined as done when the formsflow tool is able to dynamically assign roles to users based on IDIR

- [x] Users, based on their roles, are able to see a separate interfaces in the tool

**Comment by iman-jamali-fw** [comment]
Thank you @HasanSifat for capturing this core requirement.

Please let me know if I understand this correctly:
- All the users will have a `client` role therefor can submit new forms.
- If a user (client/employee), is assigned to submissions, then that user will have both `client`+`reviewer` roles. In other words, a reviewer will be able to submit a new form and also can review submissions that are assigned to him/her. 

**In terms of UI in TOOL:**
- Client (employees) will see forms
- Reviewers (supervisors) will see forms and tasks tabs.

**Comment by HasanSifat** [comment]
Hi @iman-jamali-fw,

After discussing with the team, we can confirm that your understanding is correct. 

In terms of UI in the tool, following are the views that we have in mind- 
1. Clients/Submitters can see both Forms and Tasks tab. However, the tasks tab will have no items in there for them to review.
2. Reviewers/Managers will also have both the Forms and Tasks tab. In this case, the tasks tab will have ONLY the submissions assigned to them available to be viewed and reviewed.

**Comment by iman-jamali-fw** [comment]
Thank you @HasanSifat 
Ticket #322 says the Task tab is only visible to the Reviewer/supervisor. Can you see if there is a conflict here?

**Comment by HasanSifat** [comment]
Hi @iman-jamali-fw, Ticket#322 is referring to renaming the tasks tab so that it reads "Review & Process". The plan is to keep the "Forms" and "Tasks" tab available both for clients and reviewers. Clients will have no items to review in Tasks tab and only be able to see available forms. Reviewers will have "forms" tab available with available forms and "tasks" tab with available applications to be reviewed.

**Comment by Stella-Archer** [comment]
can test by assigning roles manually

**Comment by Stella-Archer** [comment]
Ser up session
assign roles User & Reviewer
document environments that they see in DEV/TEST/PROD

**Comment by Stella-Archer** [comment]
I can't see this in any environments or roles 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/d4cca4c0-4b53-4afd-a39d-e68d542a5d2d)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/3f64a6dd-fb7c-407c-b63f-fd1de634049e)

**Comment by iman-jamali-fw** [comment]
@HasanSifat This feature is deployed to TEST and ready for testing :)

**Comment by alexandralloyd** [comment]
Tested in PROD with Lee-Ann and Josh, working.
