### ISSUE TITLE
TELEWORK: Find Style Guide Inconsistencies

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#344]
**User Story**
As an employee, I want an accessible experience when filling out the telework form so I am able to complete the form. 

**Tasks**

- [ ] Liaison with Content Team to record all Web Style Guide inconsistencies. 

**Acceptance Criteria**

- [ ] All style guide inconsistencies have been found

- [ ] A ticket is made that records all the fixes for the inconsistencies

**Comment by LeeAnnYearley** [comment]
https://miro.com/app/board/uXjVOWapt1w=/
