### ISSUE TITLE
TELEWORK: Add Checkbox for "Work Duties and Responsibilities"

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#345]
**User Story**
As an employee, I want the option to select "same duties as in the office" when responding to the Work Duties and Responsibilities question, so I don't have to waste time typing out my work duties. 

**Tasks**

- [x] Add "same as" check box with conditional logic to Work Duties and Responsibilities section to all environments

- [x] Add conditional logic that when a user clicks "same as" check box, the Work Duties comment box disappears in all environments 

- [x] Add disclaimer to the header of this section to mention "as discussed with your supervisor"

**Relates to Ticket #346**

**Acceptance Criteria**

- [ ] "Same as" check box is visible to all users in all environments

- [ ] Conditional logic is working for all users in all environments - once you click the "same as" checkbox the comment box for Work Duties disappears

**Comment by alexandralloyd** [comment]
All tasks working in Dev, need to be pushed to Test and Prod. Needs content owner approval. 

![WorkDuties.PNG](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/23f5ee0c-45a8-4439-9de4-1ad708037cbe
)
