### ISSUE TITLE
TELEWORK: Add Placeholder Text to "Work Duties"

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#346]
**User Story**
As an employee, I want an example of what to put into the Work Duties and Responsibilities comment box so I know what type of information to put there. 

**Tasks**

- [x] Add placeholder text to the Work Duties comment box in all environments

- [x] Add the same information to the tooltip in all environments

**Acceptance Criteria**

- [x]  Placeholder text is visible to all users in all environments

- [x] Tooltip is visible to all users in all environments

**Relates to Ticket #345**

**Comment by alexandralloyd** [comment]
Add Radio button: "My work duties and responsibilities are the same at home as in the office" 
Yes or No
If no show, "If work duties and responsibilities are not the same at home as in the office, please list the differences here."

**Comment by MeghanStothers** [comment]
Not essential for launch, but would be a good usability improvement
