### ISSUE TITLE
TELEWORK: Add Comment Box to "Schedule" Section

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#347]
**User Story**
As an employee, I want the ability to account for my flex-days when inputting my telework schedule so I can ensure that my supervisor is taking my flex-days into account when reviewing my telework days for approval. 

**Tasks**

- [x] Add comment box to Teleworking Schedule section in all environments

- [x] Include wording that employee's can include their flex-days or any other comments they have about their schedule specifically

**Acceptance Criteria**

- [ ] Comment box is visible and usable in all environments
