### ISSUE TITLE
TELEWORK: Edit Careers and MyHR Link 

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#350]
**User Story**
As an employee, I want Careers and MyHR links to be accessible so I utilize the links.

**Tasks**

- [ ] Liaison with Content Team to see how to edit Careers and MyHR link in all environments to fit with Web Style Guide

- [ ] Edit Careers and MyHR link

**Acceptance Criteria**

- [ ] Careers and MyHR links are corrected to fit with WSG in all environments

**Comment by Stella-Archer** [comment]
Related to issue #344 'TELEWORK: Find Style Guide Inconsistencies'

**Comment by alexandralloyd** [comment]
![MyHR link.PNG](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/b163c4ee-5c57-4c6d-a097-b33bb38e9717)

Fixed in Dev, new version just needs to be pushed to TEST and PROD.
