### ISSUE TITLE
TELEWORK: Autopopulate Date Field in Signature Section

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#352]
**User Story**
As an employee, I want the date field in the Signature to auto-populate to today's date so I don't have to worry about choosing the right date.

**Tasks**

- [x] Investigate auto-populating dates in Formsflow

- [x] Implement auto-population of the current date in the date field in the Signature section in all environments

**Acceptance Criteria**

- [x] Date auto-populates to current date for all users in all environments

**Comment by DonMoffatt** [comment]
I just had to add 
value = moment(); 
in the calculated javascript area for the data![image.png](https://images.zenhubusercontent.com/61e5c6ccd594602905c8af04/dd5272b3-9a8d-45b7-9c7f-7e2ffb20cbda) tab. 
![image.png](https://images.zenhubusercontent.com/61e5c6ccd594602905c8af04/a27deada-6eca-4862-b906-79e57bccae8b)

**Comment by DonMoffatt** [comment]
I am checking this for the supervisor signoff date.
