### ISSUE TITLE
TELEWORK: PDF Name Generation

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#353]
**User Story**
As a supervisor, I want the name of my employee in the name of the PDF I'm emailed so I can tell from the title of the PDF that it's my employee's telework form.

**Tasks**

- [x] Personalize the name of PDF attachments for both employees and supervisors

- [x] Name of the PDF should be FORM NAME_SUBMITTER NAME_DRAFT for PDFs of forms that need to be still be approved, and FORM NAME_SUBMITTER NAME_APPROVED/DENIED for the final form

**Acceptance Criteria**

- [x] Employees and supervisors receive the draft Telework form (without supervisor sign-off) as a PDF with the following title format: FORM NAME_SUBMITTER NAME_DRAFT

- [x] Employees and supervisors receive the draft Telework form (without supervisor sign-off) as a PDF with the following title format: FORM NAME_SUBMITTER NAME_APPROVED/DENIED

- [ ] The above can be performed in all three environments

**Comment by alexandralloyd** [comment]
Related to ticket #157

**Comment by alexandralloyd** [comment]
Currently not working in TEST![telework name generation.PNG](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/a70cde6c-5688-4f9d-b91f-cbd637d7da9e)

**Comment by Stella-Archer** [comment]
[Uploading... PDF Copy of Telework agreement.msg]

**Comment by simensma-fresh** [comment]
@alexandralloyd @Stella-Archer @HasanSifat This has now been resolved, and should be ready for a re-test

**Comment by HasanSifat** [comment]
Tested successfully in TEST again.

1. Manager Notification email has an attachment with updated name-
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/5c3fbee8-2377-4508-b1ab-c607b5c78bf0)

2. Manager final confirmation email has attachments with updated name-
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/3738bc91-36bf-4d8c-9987-3872d6e403e1)

3. Employee final confirmation email has an attachment with updated name-
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/e855145c-d783-45f0-bd17-658a285a7190)

Ready to be transferred to PROD

**Comment by alexandralloyd** [comment]
Working in TEST.

**Comment by HasanSifat** [comment]
Tested successfully in PROD

Ready to be closed
