### ISSUE TITLE
TELEWORK: Employee Email Messaging after Submission

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#354]
**User Story**
As an employee, I want a copy of my submission before my supervisor signs it so I have a copy of my telework schedule.  

**Tasks**

- [x] Modify the workflow so that the the employee is emailed a PDF of their application (without supervisor approval) upon submission their application

- [x] Update the body of the email to include: thank you message; important timelines about the form; explains that this is not the approved form; and a call to action for the employee to check with their supervisor about the status of their application.

- [x] Ensure tasks 1 and 2 work in all environments

**Acceptance Criteria**

- [x] Employee gets a PDF emailed to them upon submission of the form in all environments

- [x] Email body is formatted correctly and includes all information listed in task 2

- [x] The above is true in all three environments

**Comment by HasanSifat** [comment]
Tested successfully in PROD

Ready to be closed

**Comment by DonMoffatt** [comment]
Tested in Prod.

**Comment by DonMoffatt** [comment]
@simensma-fresh It worked in PROD for Hasan but when the three of us retested around 10 a.m. none of us got emails as either employee or manager.
