### ISSUE TITLE
TELEWORK: Supervisor Notification Email

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#355]
**User Story**
As a supervisor, I want more comprehensive email when an employee submits a new telework form for my review so that I don't get confused about the telework approval process. 

**Tasks**

- [x] Add who submitted the form (with proper formatting) in the notification email

- [x] Have the number of requested telework days in the body of the notification email

- [x] Explain why the draft telework agreement is included in the email as a PDF

- [x] Have explicit next-steps for when the employee is asking for three or more days (need attachment with ADM approval, expectation of what they'll need with them to approve the form)

- [x] Suggested wording for if they have to send a request to the ADM (how to send request, procedure for supervisors -- could just be pointing them to the 'for more info' document) 

**Acceptance Criteria**

- [x] All tasks are included in the body of the email sent to the supervisor in all three environments

**Comment by alexandralloyd** [comment]
Confirmation on how the process really works before we draft directions.

**Comment by HasanSifat** [comment]
Successfully tested in PROD

Ready to be closed

**Comment by DonMoffatt** [comment]
Tested in Prod.
