### ISSUE TITLE
TELEWORK: Confirmation of Decision Email for Employees and Supervisors

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#356]
**User Story**
As an employee, I want to know about what to do now that my telework form is complete so I can get 

**Tasks**

- [x] Employee and supervisors are notified in the confirmation of decision email that the agreement is valid for one year

- [x] Employee and supervisors are notified in the confirmation of decision email that if there is any change that needs to be made to any part of the agreement, the client will have to submit a new application

- [x] The confirmation of decision email states that the employee's information will be deleted from Formsflow per the business rules decided by ticket #339

- [x] The confirmation of decision email instructs the employee and manager to save the attachment for record keeping purposes

**Acceptance Criteria**

- [x] All the above criteria are met within the confirmation of decision email for both managers and supervisors in all three environments

**Comment by HasanSifat** [comment]
Tested successfully in PROD

ready to be closed

**Comment by DonMoffatt** [comment]
Tested in PROD.
