### ISSUE TITLE
TELEWORK: Restrict email domains allowed to gov.bc.ca and other OCIO accepted domains

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#360]
**User Story**
As the product owner, I want the employee to only be able to change the supervisor email field to a BC Government domain. This is for security and process reasons (clarity of who is signing off).

**Tasks**
- [x] Collect the range of domains we wish this to be restricted to. It will naturally include gov.bc.ca but there are other government domains such as crtbc.ca (the Civil Resolution Tribunal). 
- [x] Apply this filter to the "Manager/Employer Email" field (variable name = managerEmail.
- [x]  Create text next to the field saying that it is restricted to government email addresses.
- [x] Give the range of accepted domains in the supporting documentation.

**Acceptance Criteria**
- [x] This filter should not exclude any potential users of this form
- [x] The filter must function

**Comment by DonMoffatt** [comment]
I can assist in collecting the domain addresses.

**Comment by DonMoffatt** [comment]
This is a duplication of #215.

**Comment by DonMoffatt** [comment]
I asked for a list of domains today on Yammer on in the Digital Government group.

**Comment by DonMoffatt** [comment]
I asked Colin Newell today and he referred me to Danton Remacle. I am awaiting a response. Alex also asked Steven Jones.

**Comment by DonMoffatt** [comment]
-We have collected a list of possible domains from the Messaging and Communications group. 
- We have also collected a list of applicable organizations from Policy. 
- The next step is to match the two.

**Comment by simensma-fresh** [comment]
@DonMoffatt @MeghanStothers @Stella-Archer @Abuchana 
I added an example on what this could look like on the telework form in dev. The List of domains / messaging can be updated in the Validation Tab of the field (custom validation section).

![image.png](https://images.zenhubusercontent.com/61df28f84562db4e4d8e63d1/2436177d-5b
43-4666-b595-4c7c5369df79)

![image.png](https://images.zenhubusercontent.com/61df28f84562db4e4d8e63d1/ad4e0bd2-6b9c-4696-bc32-885050b07b30)

![image.png](https://images.zenhubusercontent.com/61df28f84562db4e4d8e63d1/431917c7-30c2-456f-ab4c-b159f5357f5d)

**Comment by DonMoffatt** [comment]
Thanks - yes,  this looks simple.

**Comment by Stella-Archer** [comment]
yes this looks great thansk!
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/c65b28ca-090b-4f02-8e71-922064295c46)

**Comment by MeghanStothers** [comment]
I've had a reply from Igor and OCIO that they have received our request for the latest list. I have asked for a deadline of tomorrow at the latest as we'll need Simen's time to add the domains. @simensma-fresh can you let us know if getting the list on Tuesday will give you enough time?

Also, we'll want to adjust the message to show "BC" in caps but that is low-priority item. I will share this informati
on with the client/Sean/PIE at our meeting this afternoon.

**Comment by MeghanStothers** [comment]
Action: I have been given a contact name Aaron Leskiw, ED Network, to help us with this request. I will loop in Stella and Igor to the thread.

**Comment by DonMoffatt** [comment]
I can add the domains, @MeghanStothers. Simen has already added the code and it is very simple.

**Comment by DonMoffatt** [comment]
I added the following approved domains to both the employee and manager email validation. Employee is also necessary as copies of confidential information could otherwise be sent there if it was changed from the default.

"inbcinvestment.ca",
"bcassessment.ca",
"bc-ebc.ca",
"bcehs.ca",
"bcest.bc.ca",
"bcfarmreviewboard.ca",
"BCFerryCommission.ca",
"bchumanrights.ca",
"bciif.ca",
"bcldb.com",
"bcliquorstores.com",
"bcrcf.ca",
"bcspp.org",
"bcucipp.org",
"crtbc.ca",
"cullencommission.ca",
"cupsa-aspc.ca",
"destinationbc.ca",
"destinationbc.travel",
"eaat.ca",
"elections.bc.ca",
"healthlinkbc.ca",
"iiobc.ca",
"justicebc.ca",
"lrb.bc.ca",
"obcctc.ca",
"paab.bc.ca",
"patientcarequalityreviewboard.ca",
"ptboard.bc.ca",
"robsonsquare.ca",
"seniorsadvocatebc.ca",
"surfacerightsboard.bc.ca",
"tourismbc.com",
"ticorp.ca",
"workbc.ca",
"royalbcmuseum.bc.ca",
"rcybc.ca",
"lngbuybc.ca", 
"eabtribunals.ca"

**Comment by HasanSifat** [comment]
Tested successfully in DEV!

Ready to be pushed to TEST and PROD!

**Comment by HasanSifat** [comment]
Tested successfully in PROD! 

Ready to be closed
