### ISSUE TITLE
Ability to search government Email addresss for Manager/Supervisor Name from within the Supervisor Email Field

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#361]
**User Story**
As an employee, I want to be able to find the person who is delegated to sign off on my Telework Agreement by searching for it in the Gal, just like we do in Outlook. 

**Tasks**
 - [ ] Implement the GAL functionality from within the manager name and email fields so that employees can be assured they are sending it to the right person. 
- [ ] Once populated, it should populate the other, corresponding field. 

- [ ] Create drag and drop form components for front-end forms designers. so that this can be a reusable component. 
       - One drag and drop field for selecting a SINGLE approver
       - One drag and drop field for selecting MULTIPLE approvers. 

**Acceptance Criteria**
- [ ] This functionality should work from both the "Manager/Employer Name" and "Manager/Employer Email" field. Once selected, it should populate the other field with the matching information.  

- [ ] 2 form components created so that SINGLE?MULTIPLE approvers field can be put in any form

**Comment by DonMoffatt** [comment]
@warrenchristian1telus Stella suggested this for phase 2.

**Comment by DonMoffatt** [comment]
@warrenchristian1telus Stella suggested this for phase 2.

**Comment by MeghanStothers** [comment]
Can this situation/requirement be put into Rocketchat (Devops, Dev exchange) assuming that some other areas of govt have worked in this issue

**Comment by warrenchristian1telus** [comment]
@MeghanStothers I have made a form with similar functionality before, for TL Forms. Rather than searching for an approver, it provides a list to select from available approvers. To get this to work, we just need the relevant data in CDATA. In the other system, we queried PeopleSoft directly, so we should be able to mimic that without too much effort. Just not sure if it already exists in there. I'll reach out to the ODS/CDATA team to see if they have any recommendations.

**Comment by HasanSifat** [comment]
@warrenchristian1telus ticket updated with acceptance criteria that we discussed in our scrum today.

**Comment by T854236** [comment]
There is an endpoint that may already contain the information requested:https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demo/.  Shared information to Warren.

**Comment by T854236** [comment]
I believe this is known but sharing again.  The API endpoints have a few options: it can be filtered, options to retrieve subset of properties and group by functions.  More information can be found in the help file: https://cdn.cdata.com/help/BWG/odata/Filtering-Resources.html

**Comment by DonMoffatt** [comment]
> I believe this is known but sharing again. The API endpoints have a few options: it can be filtered, options to retrieve subset of properties and group by functions. More information can be found in the help file: https://cdn.cdata.com/help/BWG/odata/Filtering-Resources.html

Thanks Patrick. I am checking against other sources today.

**Comment by warrenchristian1telus** [comment]
I think this should do the trick @DonMoffatt (if we want supervisor name and email). Just need to decide what to do with empty ones. Not sure how common that is for our target audience, but there are 2,931 records with empty emails in the current dataset.

`https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demo/?$select=supervisor_name,supervisor_email&$filter=GUID eq 'INSERT_GUID_HERE'`
