### ISSUE TITLE
TELEWORK: fraud Awareness and Prevention course requirement

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#386]
**User Story**

“As a employee, manager and/or ADM I want be aware of the fraud Awareness and Prevention course as a training prerequisite so I cant be sure I'm meeting all requirements for the telework agreement compliance.” 

**Tasks**

- [x] Identify appropriate area on form to add text (first section  of form?)
- [x] Add text to telework form: In addition to the above longstanding criteria, effective July 2022 the following requirements must also be met:  

• Current employees must have completed all mandatory corporate training prescribed by the Public Service Agency before a telework agreement can be approved. This includes IM 117, the Fraud Awareness and Prevention Course and the annual review of the Standards of Conduct/Oath of Employment. New employees, especially those hired as teleworkers, must complete the Oath, IM 117 and the Fraud Awareness and Prevention Course as soon as possible after they begin working. The Public Service Agency may prescribe additional training in the future.  

 - [x] Confirm with client addition and position is appropriate

**Acceptance Criteria**

- [x] Above content is added to form in all environments
- [x] client has reviewed and approved of position and content of new text content

**Comment by alexandralloyd** [comment]
Added to the DEV version

**Comment by Stella-Archer** [comment]
looks really great in DEV Alex, Did Sean OK the final wording? If so we should be good to push this to test ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/6f4e6ba6-1ad0-45db-ac7c-a09bf1d18056)

**Comment by HasanSifat** [comment]
All requirements met and changeS present in DEV, TEST & PROD.
