### ISSUE TITLE
APP: Instructions for uploading JSON of Form to Formsflow.ai

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#409]
**User Story**
As a forms designer, I want the ability to upload a copy of a form to formsflow.ai so that I know I can quickly and easily restore a deleted form.

**Tasks**

- [x] Write out instructions for saving and uploading a copy of a form in formsflow.ai

- [x] Save instructions somewhere (Teams, GitHub, etc.)

**Acceptance Criteria**

- [x] Above tasks are completed

**Comment by iman-jamali-fw** [comment]
Instructions can be found [here](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#uploading-a-form)

**Comment by alexandralloyd** [comment]
Thanks Iman, this looks great! I'll close this ticket now.
