### ISSUE TITLE
TELEWORK: Customize email messages

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#425]
**User Story**
As a user, either as an employee or supervisor, I want customized messages to fit the options requested by the employee.

**Tasks**
- [x] Work out logic to match the new email messages specified.
- [x] Augment the existing workflow with new decision gates to match this logic.
- [x] Modify the email messages for each option (18 in total).
- [x] Format the emails in the requested way - boldfacing.
- [x] Format the emails in the requested say - list items.

**Acceptance Criteria**
- [x] All use cases work
- [ ] All use cases are formatted in the desired way.

**Comment by DonMoffatt** [comment]
Current status: logic is working but the formatting is not.

**Comment by DonMoffatt** [comment]
Hello @iman-jamali-fw - I have tried a variety of ways of adding boldfacing and list items but so far I can't add anything that produces the equivalent to a <strong> or  <li> effect. It all comes out as plain text and includes the markup tags.  I tried escaping to html using a \ and " and neither worked (both showed up in the message). I also tried the asteriks shown here: https://jira.camunda.com/secure/WikiRendererHelpAction.jspa?section=texteffects

Do you have any ideas?

**Comment by DonMoffatt** [comment]
I've applied Iman's suggested method but that method does not appear to allow attachments. We may be limited to a choice of markup OR an attachment. However, I am continuing to investigate and emailed Iman about it at the end of the day in the hope that he has an idea of a workaround.

**Comment by simensma-fresh** [comment]
I've been working with Don to modify our email functionality to allow for email styling. This has now been tested in dev, so it should unblock work on this

**Comment by DonMoffatt** [comment]
@simensma-fresh I emailed  you at 12:40 today to get your assistance on the workflow. While checking the messages we noticed some were not being delivered. It is likely a setting in the workflow. I can reopen the workflow ticket if you prefer.

**Comment by HasanSifat** [comment]
All attachments are present and attached while carrying out tests in PROD.

@DonMoffatt  one issue I noticed is that in the final confirmation email to employees after a decision has been made for 3+ days, the adm attachment is not there with the email, the form is only attached. However, the supervisor's final email has the adm approval attachment.

**Comment by DonMoffatt** [comment]
@simensma-fresh It worked in PROD for Hasan but when the three of us retested around 10 a.m. none of us got emails as either employee or manager.

**Comment by HasanSifat** [comment]
tested successfully in PROD

ready to be closed
