### ISSUE TITLE
BI: Create table of organizations to populate the organization options

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#540]
**User Story**
The user expects to see find their organization listed. Therefore we need to have a complete list of all organizations that for which the Telework Agreement is applicable.  

**Tasks**
- [ ] Create a master list of all applicable organizations.
- [ ] Put this list in a table and populated the dropdown from this table.

**Acceptance Criteria**
- [ ] The list should contain all organizations covered by the Public Service Act.
- [ ] The list must not contain duplicates
- [ ] The organization list must contain only those organizations that are currently active.
- [ ] The list must present the names consistently ("Ministry of Finance" or "Finance" but not both ways of presenting a ministry's name.
- [ ] The subgroups of a ministry will be represented by the Ministry (e.g. if the Civil Resolution Tribunal were part of this it would be represented by the Ministry of Attorney General and Housing) 
- [ ]  The ministry names will match the currently used names (e.g. Ministry of Housing is part of the Ministry of the Attorney General now). 
- [ ] The list should contain only those organizations the are within the BC SPAN network, for email security reasons.
- [ ] The Telework Agreement will be autopopulated from this table (see ticket #484).

**Comment by DonMoffatt** [comment]
Patrick, you have a much better understanding of the tables than I do: we need sources that could be combined to produce the output described. I'm not sure they exist.

**Comment by T854236** [comment]
The BI org. hierarchy is exposed via https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_meta_dept_org_levels/.

If you are looking to build/maintain a different list, it might be easier to have the source tables in the app and if BI needs it, can pull it down for reporting purposes.

**Comment by DonMoffatt** [comment]
I don't yet have access to those tables. I will soon, however (next few days). The team would like wrap this up by next Tuesday but I am not sure that is likely (I may not have access to those tables by then, for example).

**Comment by T854236** [comment]
Are you referring to access to the API endpoint or tables in the form app?

I can share credentials of API DEV if you don't have it.

**Comment by DonMoffatt** [comment]
I'll be clearer: I tried logging in directly to the link you provided and did not have the credentials. I will soon have access to the data warehouse in my new role.

**Comment by DonMoffatt** [comment]
I created a master list of organizations to include from information provide by Sean at Policy, along with a list of names that are either outdated or from organizations that are defunct.  I am using these to vet data sources. I ask Tyler King to look for a table of current Public Service Act organizations. I also asked Amy Lee at the FMO about where the FMO got the information for creating the table used by Policy.

**Comment by DonMoffatt** [comment]
Amy Lee (Manager of Leave and Payroll Accounting, Financial Management Office) confirmed with Nina Moore that the list of Public Service Act organizations did not originate in a table from the BI data warehouse: "Nina confirmed that there is no table that pulls the organizations covered under the Public Service Act that she is aware of. The matrix she originally provided is from CRM ( RightNow) database as Knowledge content.
"

**Comment by DonMoffatt** [comment]
@HasanSifat I've added you as the point of contact from this side. 'Hope that's ok. I will give you some files this week. I hope to stay involved on the other side.

**Comment by Abuchana** [comment]
Moving to the Program board
