### ISSUE TITLE
Telework: Update "ADM" text to "ADM (or delegate)" anywhere it appears on the form

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#543]
**User Story**
As a user, I want it to be clear that my ADM **or a delegate** can action my request, so that my request is not waiting for an ADM specifically.

**Tasks**
- [ ] Confirm with Business (Sean Gadsby) that this change is approved
- [ ] Change text anywhere it says "ADM" to "ADM (or delegate)"
- [ ] Test

**Acceptance Criteria**

- [ ] I can see "ADM (or delegate)" anywhere on the form that was referring to "ADM" previously

**Comment by MeghanStothers** [comment]
Related: Given we want to ensure consistent language in the tool and in the Careers & MyHR content, I have asked Josh/team to:
1) look for any instances of "ADM" in FAQs or content
2) replace as "ADM or delegate"

**Comment by MissionT** [comment]
The wording changes are completed on the form. The pop-up wording on the form generated when the supervisor accepts the telework form however needs to be updated. I've sent the request to Josh to see if he can update the wording. Chris

**Comment by Stella-Archer** [comment]
good catch Chris the confirmation messages where build by DEV/Dave we need to reassign to Bhumin or Iman

**Comment by bhumin-fw** [comment]
@Stella-Archer 
Update text on the confirmation screen.

FYI:
I have updated "ADM" to "ADM (or delegate)" in the form itself too.
In the "manager/supervisor signoff" section -> "agreed by manager" -> "the employee has requested for 3 or more days" -> "Here there are 3 bullet points".
update text in these bullet points.

**Comment by MissionT** [comment]
I tested the communication screen and can confirm the ADM (or delegate) has been updated successfully.
I'm closing this ticket. Chris
