### ISSUE TITLE
TOOL: Drafts Tab | Add delete drafts button under action column

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#601]
**User Story**
As a user, I want the ability to delete draft forms 

**Tasks**

- [x] Add delete button in UI for Drafts tab

- [x] Make sure deleted drafts get wiped from database in back-end

- [ ] A pre-confirmation window/message after the delete button has been clicked on- "Deleting this draft will eliminate the form and all existing information on it from the database. "

- [ ] A confirmation popup should be displayed to confirm the deletion. 

**Acceptance Criteria**
When the users have a delete draft button and it works according to requirements

**Comment by HasanSifat** [comment]
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/7b4b7992-47c7-4b45-82a7-416f4ec3f555)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @HasanSifat 
Could you verify the delete confirmation text, before I deploy this ticket?
`Are you sure you want to delete this draft? Deleting this draft will eliminate the form and all existing information on it from the database.`

![Screen Shot 2022-10-11 at 9.44.49 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/66435489-850d-488a-93ea-28d78f9933dc)

**Comment by HasanSifat** [comment]
still waiting on confirmation from Meghan. But it looks good in DEV for me. I'll move this PO review for now. Ready to be transferred to TEST/PROD

**Comment by Stella-Archer** [comment]
@meghan says this looks great move it to TEST

**Comment by MeghanStothers** [comment]
Looks good - approved Please move to test

**Comment by HasanSifat** [comment]
Tested successfully in TEST

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
