### ISSUE TITLE
SL Review: Final QA on content 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#611]
**User Story**
As a forms designer, I want the SL form to be consistent with web-style standards and accessibility requirements. 

**Tasks**

- [x] Consult the content team

- [x] Get form reviewed 

- [x] Apply final changes

**Acceptance Criteria**
When the form is consistent and standardized

**Comment by HasanSifat** [comment]
Edits were made based on feedback from the Content team, Fazil, Stella, Meghan and Hasan. A couple of outstanding action items- 

1. edit bullet points in the before you begin section for submitted forms instructions 
2. alert box instructions need to be looked at as well

**Comment by HasanSifat** [comment]
Reviewed form with both POs and got approval for all front--end content on form. Ticket ready to be closed once Dev version of form has been transferred to TEST/PROD

**Comment by JodiLittle** [comment]
Changes to the language in the form have been made based on UX test #1. Do we do another accessibility review when we are done the other 4 tests?

**Comment by JodiLittle** [comment]
@MeghanStothers can your team look at it when we are done (style/accessibility) to ensure consistency across the forms?

**Comment by HasanSifat** [comment]
Next steps: Do a final sweep of the form in terms of accessibility after final UX testing in the first week of november

**Comment by HasanSifat** [comment]
QA complete with writing team, Jodi (team lead/PO), Hasan (forms designer), Fazil (UX Researcher)
