### ISSUE TITLE
SL Review: Confirmation page after "Submit for validation" button 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#621]
**User Story**
As an ADM, I want to see a confirmation page after I have clicked on submit for validation button to give me more information about the next steps. 

**Tasks**

- [ ] Currently, users are routed to the telework confirmation page after clicking button 

- [ ] Clicking on submit for validation button in SL review form will take users to this page

- [ ] Copy for page- 

Thank you for your commitment to supporting career development of your Senior Leadership team and for your contribution to executive succession.

- The information you’ve provided will be shared with Executive Talent Management, Corporate Workforce Strategies in the Public Service Agency, as well as ministry Strategic Human Resources (ministry-specific data). Broad themes will be presented to DMCPSR to further the conversation on executive talent and utilized for executive succession and development strategies, programs and activities.
- Please download a PDF copy for your files and share with the senior leader. Continue conversations with the identified senior leader to refine their learning and development plan, goals, and actions in support of their aspirations. Your Ministry Human Resources representative can connect the senior leader with targeted ministry and corporate learning opportunities to ensure they have access to the essential learning and experiences that will set them up for success. Coaching services are also available to senior leaders.
- The information has now been submitted to the database for validation. You can come back and edit the information and resubmit at any point up until 11:59 PM on January 27, 2023.
- If you have any questions, please contact Jodi Little, Leadership Development and Succession Lead at jodi.little@gov.bc.ca 

**Acceptance Criteria**
When the confirmation page has been added

**Comment by HasanSifat** [comment]
@JodiLittle looking into changing the copy. Will update the ticket and pull it back to in progress when new copy received

**Comment by HasanSifat** [comment]
Edit to copy- 
•	Thank you for submitting this form for the ministry to validate 
•	The ministry will communicate the approach you will be using to validate senior leader readiness. Contact the ED of your ministry human resources department or the DMO for further instruction
•	Once the DM/executive team has validated the senior leaders’ readiness, please remember to go back into the system and re-open the draft form to document any additional feedback and adjust the readiness rating as needed
•	**When validated and finalized, all forms must be signed and submitted by you using the ‘Final Submission’ button by 11:59 PM on January 27th, 2023**
•	After January 27, 2023, unsigned forms will be considered incomplete and will not be included in the data captured for corporate reporting. These files will be deleted from the system
•	If you have any questions, please contact [Jodi Little, Leadership Development and Succession Lead](mailto:jodi.little@gov.bc.ca)

**Comment by iman-jamali-fw** [comment]
@HasanSifat Ready for test on DEV

**Comment by HasanSifat** [comment]
@iman-jamali-fw just made a submission and got the previous confirmation page. Please update to new copy in my previous comment. Screenshot for reference 

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/fbf2157b-f491-42f3-8944-a8b04bef2f4f)

**Comment by HasanSifat** [comment]
@iman-jamali-fw change made to copy in my last  comment as of last e

**Comment by iman-jamali-fw** [comment]
@HasanSifat Ready for testing on TEST

**Comment by HasanSifat** [comment]
Almost done! Your Nomination has been submitted for your ministry to validate. Please make sure to come back and complete the final sign-off after discussions with your Deputy Minister (DM). Next Steps: 
1. The ministry will communicate the approach you will be using to validate senior leader readiness. Contact the ED of your ministry human resources department or the DMO for further instruction
2. Once the DM/executive team has validated the senior leaders’ readiness, please remember to go back into the system and re-open the form in the "Submitted Forms" tab to document any additional feedback and adjust the readiness rating as needed
3. When validated and finalized, all forms must be signed and submitted by you using the ‘Final Submission’ button by 11:59 PM on January 27th, 2023
4. After January 27, 2023, unsigned forms will be considered incomplete and will not be included in the data captured for corporate reporting. These files will be deleted from the system
5. If you have any questions, please contact Jodi Little, Leadership Development and Succession Lead

**Comment by HasanSifat** [comment]
@iman-jamali-fw update to copy- 

**Almost done! Your Nomination has been submitted for your ministry to validate. Please make sure to come back and complete the final sign-off after discussions with your Deputy Minister (DM). Next Steps:**
1.	The ministry will communicate the approach you will be using to validate senior leader readiness. Contact the Executive Director of your ministry human resources department or the DMO for further instruction
2.	Once the DM/executive team has validated the senior leaders’ readiness, please remember to go back into the system and re-open the form in the "Submitted Forms" tab to document any additional feedback and adjust the readiness rating as needed
3.	When validated and finalized, all forms must be signed and submitted by you using the ‘Final Submission’ button by 11:59 PM on January 27th, 2023
4.	After January 27, 2023, unsigned forms that have not been submitted as final will be considered incomplete and will not be included in the data captured for corporate reporting. These files will be deleted from the system
5.	If you have any questions, please contact PSA.SeniorLeadershipReview@gov.bc.ca

**Comment by HasanSifat** [comment]
Tested successfully in TEST. Ready to be deployed to PROD
