### ISSUE TITLE
SL Review: Custom button "Submit for Validation"

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#631]
**User Story**
As an ADM, I want to be able to submit information on the SL Review form before the validation process fir reporting purposes. 

**Tasks**

- [x] Create "Submit for validation" button in SL Review 2.0 form 

- [x] Ensure data gets passed onto ODS endpoint once button is clicked

- [x] the validation checks for final sign-off panel does not trigger when clicking on this button

- [x] Users are able to come back, edit the data in the form and finish the last final sign-off section after clicking the button. 

**Acceptance Criteria**
When the 3 tasks above are complete

**Comment by MeghanStothers** [comment]
@iman-jamali-fw The button is there, but is the info being passed to the ODS?

**Comment by iman-jamali-fw** [comment]
@MeghanStothers The data is not yet passed to the ODS, I'll work with Patrick to have the data sent.

**Comment by MeghanStothers** [comment]
Iman to work on this one on his local to avoid interruptions with SL sessions..

**Comment by iman-jamali-fw** [comment]
@HasanSifat The validation of `finalSubmission` button is added to the form. A custom script is added to that button that dynamically makes a list of components that are specified in the `componentKeysToBeRequired` list, **required**. Feel free to modify that list.

For sending data to ODS, I suggest tracking that as part of #570 and moving this ticket forward.

**Comment by HasanSifat** [comment]
@iman-jamali-fw doing some tests on the DEV form. I can't see the final sign-off section visible when i start a new form or go back to the dev form. WOuld it be possible to make it visible from the get go?

**Comment by HasanSifat** [comment]
Also, after submission i can see the "Submit for validation" button is still triggering the validation checks on the 2 checkboxes in the final sign-off section

**Comment by JodiLittle** [comment]
Approved

**Comment by HasanSifat** [comment]
tested successfully in TEST
