### ISSUE TITLE
SL Review: Print as Pdf button to draft forms tab, submitted forms and Review and Process forms tab

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#640]
**User Story**
As an ADM i want to be able to print blank forms, draft forms and submitted forms. I can now only print blank forms. 
**Tasks**

- [x] Add print as pdf button to draft forms

- [x] Add print as pdf button to submitted forms

- [x] Add print as pdf button to Review and Process Forms tab

**Acceptance Criteria**
when the task list above is complete

**Comment by MissionT** [comment]
After submitting for validation, the blue headers are missing on the PDF.  Please see screenshot of live form vs pdf:
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/3840a1d7-0592-4436-86d1-22094562e855)

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/0b6c8255-8401-4676-b167-b174501ff52a)

**Comment by HasanSifat** [comment]
@bhumin-fw I can see the "download as pdf" button available from all 3 tabs now. However, the pdf i downloaded from the "submitted forms" tab has some issues that the pages are breaking. I am attaching the downloaded file here for reference-[https://app.zenhub.com/files/439477060/6af5daa8-a4bf-4000-9020-9e2be5a8a88e/download](https://app.zenhub.com/files/439477060/6af5daa8-a4bf-4000-9020-9e2be5a8a88e/download) 

the 2 other pdfs i downloaded from the Draft forms tab and forms tab did not have this issue. Pages were breaking correcty with no overlap

**Comment by bhumin-fw** [comment]
@HasanSifat @MissionT 
I'm working on fixing this issue. I have downgraded the scale and upgraded the quality to match the existing clarity. Scale is worked based on browser settings and is not able to control by CSS or JS. In the application, we have used html2pdf along with jsPDF to export HTML form in PDF format.

I'm attaching PDF for Telework Agreement and senior leadership review with an updated setting to export PDF. 
[https://app.zenhub.com/files/439477060/395c7e1a-00e4-476b-89ef-69488e278705/download](https://app.zenhub.com/files/439477060/395c7e1a-00e4-476b-89ef-69488e278705/download)
[https://app.zenhub.com/files/439477060/6cf5e7bd-d4e5-4e90-9809-7a970f561438/download](https://app.zenhub.com/files/439477060/6cf5e7bd-d4e5-4e90-9809-7a970f561438/download)

If this looks good I can push changes to DEV.
cc: @simensma-fresh

**Comment by HasanSifat** [comment]
looking good now. Successfully tested in Dev. Ready to move to TEST

**Comment by HasanSifat** [comment]
Here is the pdf I downloaded from the submitted forms section: [https://app.zenhub.com/files/439477060/c9fef37c-6b99-46d2-a966-6911b0ce4498/download](https://app.zenhub.com/files/439477060/c9fef37c-6b99-46d2-a966-6911b0ce4498/download)

**Comment by bhumin-fw** [comment]
@HasanSifat That's the issue. It is there in Telework too. CSS does not apply after page 6.
In the above comment, I have attached PDFs of the Telework and SL review with the latest setting. It seems a little bit down in clarity if you zoom it. But work well with all CSS and page-break settings.
Please do let me know if that seems viable and we can go with it.

**Comment by bhumin-fw** [comment]
@HasanSifat 
I have deployed this ticket on TEST and DEV both environment. Please review on both environments and move it further if it looks good.

**Comment by HasanSifat** [comment]
@bhumin-fw Tested with meghan and Stella. We are all okay with the quality of the generated pdf. Ready to move to PROD!

**Comment by MeghanStothers** [comment]
I reopened this ticket with the SL launch in scope for June 1.  To review earlier work and test to see if if meets business requirements.
In conversation with Jodi, her thoughts are: 
1) form submitter can manually save and print the draft submssion (no need to have a pdf attachment/email sent to the form submitter
2) the requirement is to have a final pdf for the submitter at final submission

**Comment by Andrew-Vargas-bcgov** [comment]
I have added the print pdf flow for the final submission and fixed the fields that were not displaying properly.

**Comment by chriscaldwell-psa** [comment]
QA passed - within all form environments I was able to save, download and print the PDF.  
(Process: added Andrew Vargas a recipient, filled out all fields with data, saved, downloaded and printed the PDF. Went to each form repository, viewed and printed each PDF successfully.

**Comment by Stella-Archer** [comment]
worked great thx PO Approved & CLOSED :)
