### ISSUE TITLE
SL Review: Different color and style for panel headers

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#686]
**User Story**
As an ADM filling out the form, I want a clear distinction between information sections and sections where i need to fill the form. 

**Tasks**

- [ ] Make drop-down outline for search field more visible

- [ ] Explore different style sets/color for panel headers

- [ ] Mockup a couple of options for POs to review 

- [ ] Create a custom CSS style so that forms designers can use this style set for other forms 

**Acceptance Criteria**
When the tasks above are complete

**Comment by Stella-Archer** [comment]
Style > https://developer.gov.bc.ca/Design-System/Callout

**Comment by MeghanStothers** [comment]
Stella noted this one is higher priority that the floating

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/b4661aaf-2a36-4bf1-ac11-add5c140610f)

**Comment by MeghanStothers** [comment]
Simen noted a couple of options for this one 1) select default theme that could be modified "info theme" or 2) introduce a new component

**Comment by simensma-fresh** [comment]
The Panel component in the forms designer has now been updated to display as a callout if the "Info" Theme is selected: 

![image.png](https://images.zenhubusercontent.com/61df28f84562db4e4d8e63d1/add41313-0304-45e2-aec0-607e8c561e00)

**Comment by Stella-Archer** [comment]
Oh that worked really well thanks @simensma-fresh @fazil-ey does this style work for you form the UX POV separating info from actions?
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/eb48e716-720a-445c-b301-3b488e4ecb4c)

**Comment by Stella-Archer** [comment]
Thanks @simensma-fresh  looks great Fazil is happy too moving this to deploy;)
