### ISSUE TITLE
[SL Review]: Update Privacy Statement

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#733]
**User Story**

“As a forms owner I want accurate information in the privacy statement so I can ensure I am in compliance with FOIPPA requirements” 

In the SL Review 2.0 Form: 
**Tasks**
- [x] update FOIPPA statement to read : "This information is being collected under the authority of the Freedom of Information and Protection of Privacy Act (FOIPPA), sections 27(1)(b) **pursuant to** 33(2)(h)(j), 26(c) and 26(e)".
- [x]  hyperlink tagged to this sentence can remain the same > https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96165_02

**Acceptance Criteria**
- [x]  FOIPPA Statement now reads:  This information is being collected under the authority of the Freedom of Information and Protection of Privacy Act (FOIPPA), sections 27(1)(b) pursuant to 33(2)(h)(j), 26(c) and 26(e)".
- [ ]  Hyperlink on **sections 27(1)(b) pursuant to 33(2)(h)(j), 26(c) and 26(e)** goes to https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96165_02

**Comment by Stella-Archer** [comment]
@JodiLittle this has been updated in DEV
https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/631f7d7a3d064f5de7a7a03a
please confirm it's all good and I can move it to TEST
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/462eaf71-55a3-4032-82f9-4ce37ac616cc)

**Comment by JodiLittle** [comment]
All good!

**Comment by Stella-Archer** [comment]
@MissionT could you update this in test?

**Comment by iman-jamali-fw** [comment]
@MissionT The font seems OK to me. I guess you figured it out, otherwise, let me know to look into it.

**Comment by MissionT** [comment]
Iman showed me how to update the CSS code to keep the text all black. All good now. This ticket can be closed. Chris
