### ISSUE TITLE
1.10: Update information and link on Careers& MyHR website

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#760]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a form user I want to know about the complaint form and its place in the process so I can know if it is appropriate for me to use it and when, and how the process will look.” 

**Tasks**
- [ ] review current material on [Careers & My HR](https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/working-with-others/address-a-respectful-workplace-issue/launch-a-formal-complaint)
- [ ] confirm all changes in light of the new agreement
- [ ] engage the Careers and MyHR writing team to coordinate updates with launch

**Acceptance Criteria**
- [ ] information about formal complaints is accurate and up to date
- [ ] page provides link to digital journeys form

**Comment by morezooomm** [comment]
I have answered these questions as best I can for now.  Cheers!
[Response to Agile Team Ticket #760.docx](https://github.com/bcgov/digital-journeys/files/10108127/Response.to.Agile.Team.Ticket.760.docx)

**Comment by MeghanStothers** [comment]
This in depth review should ideally happen after UX testing in January and user feedback is rolled up and implemented.

**Comment by MeghanStothers** [comment]
[https://app.zenhub.com/files/439477060/fdcf71e1-98af-4e9c-9f50-4d83cac7f5c6/download]

**Comment by MeghanStothers** [comment]
Approved and okay to close
