### ISSUE TITLE
[TOOL]: test PROD deployment

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#860]
**User Story**
As a forms designer I want to test The telework form and PROD environment (tab look and functionality) are working as expected so I can  confirm deployment to PROD was successful.

**Tasks**
- [x] End to end test the telework form in PROD https://digital-journeys.apps.silver.devops.gov.bc.ca/form/62c8796e532635532114a70b as user then approver, work in pairs
- [x] Note if the 'print to PDF' work as expected note if anything is missing
- [x] Check emails for PDF confirm they are complete
- [x] Note it the tabs are appearing and functioning as expected (like TEST)
note the 
- [x] Note the application ID # of your submitted form below so we can check the data is submitting correctly with Patrick 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/3749fbdf-0533-470a-873c-3f6f649dae7d)

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] telework form works as expected 
- [ ] data summitted to ODS correctly as confirmed by Patrick @T854236 
- [ ] tabs look and function as expected

**Comment by Stella-Archer** [comment]
Downloaded PDF is rendering really weirdly, broken up >
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/f0c935d6-ad94-4a78-a789-b61cebe65338)

**Comment by Stella-Archer** [comment]
Did not get a confirmation page on submission >
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/c20550b8-b5e0-4aca-b8bd-5da519bce442)

**Comment by Stella-Archer** [comment]
printing the PDF in the 'Review and Process Forms' Tab failed, the process looks like it was woking with the green process bar however nothing downloaded
[Uploading... AFA61998-AE91-40D4-ABDC-78B7C0092B59.GIF]

**Comment by Stella-Archer** [comment]
@T854236 could you check to see if Application ID# 31503 made it to the ODS?
@Andrew-Vargas-bcgov could you approve Application ID# 31501 and then check with Patrick to see if it got to the ODS?

**Comment by Stella-Archer** [comment]
I downloaded the PDF in the 'review & process' tab it rendered really badly again [https://app.zenhub.com/files/439477060/548c14ab-4f17-4c61-828b-30ea54d31906/download](https://app.zenhub.com/files/439477060/548c14ab-4f17-4c61-828b-30ea54d31906/download)

**Comment by Andrew-Vargas-bcgov** [comment]
Attempted 8 downloads. The 1st and 4th PDF I downloaded (with chrome) from the approver screen rendered poorly like Stella's, with the 1st download being the worst. 
The other 6 rendered correctly.
![image](https://user-images.githubusercontent.com/41847072/213099053-b1de2f33-f21f-44ee-afa2-b6f2be0d114f.png)

The downloads took around 15 seconds, long enough after the toast disappeared that I started thinking that the download was broken.

**Comment by T854236** [comment]
@Stella-Archer 

I see submission for 31503 and 31501 in PROD.

**Comment by Andrew-Vargas-bcgov** [comment]
@bhumin-fw @iman-jamali-fw  Prod isn't sending me any e-mails after submission. New form submissions are not appearing in the Review and Process Forms tab. The supervisor is also not receiving them.

**Comment by fazil-ey** [comment]
Tested & noted issues. This can be closed
