### ISSUE TITLE
[TELEWORK]: Security/Privacy Message for Managers

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#894]
**User Story**
“As a Manager processing a 3+day request I want a reminder that I should NOT upload and information with personal information about anyone other than the applicant I am processing so I can be sure there is now possibility of a privacy breach.” 

**Tasks**
- [ ] in the upload area of the managers section of the telework agreement, add a 'warning' style alert ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/59cf5499-f2f7-4931-9eb8-e0c895b6882e)
- [x]  message should say: **To protect personal information, only upload information about the individual applicant in this submission**

**Acceptance Criteria**
- [x] Managers see message at the point they will be uploading ADM approval documents that warns them NOT to upload any other employees personal information

**Comment by MeghanStothers** [comment]
@MissionT - are you able to do this one today?

**Comment by MissionT** [comment]
The alert-info box has been successfully added as per the required acceptance criteria listed above. 

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/d6926df8-ca13-4688-8458-f7c5874d3ef5)

**Comment by Stella-Archer** [comment]
This looks perfect @MissionT we can deploy to PROD

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/8d2085d9-c15c-4302-9145-32b8b69ab004)
