### ISSUE TITLE
TOOL: Issue Remove outdated form submissions in environments 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#973]
As a forms program area, I would like to keep the tool environments uncluttered and remove outdated test forms and any other that are not needed in the workflow. 

**Tasks**
- [ ] Audit each environment
- [ ] Create inventory of current contents/forms
- [ ] identify who last worked on each form and establish status: 
- Permanent
- Test still in use
- Test to delete
- [ ] Develop a way to label status  & label
- [ ] Delete all 'to delete' forms
- [ ] set up a schedule, rinse and repeat

**Acceptance Criteria**
- [ ] establish a regular maintenance cycle (quarterly and pre-launch?).
- [ ] remove outdated/unneeded forms
- [ ] remove outdated/unneeded BPM workflows

**Comment by iman-jamali-fw** [comment]
@Stella-Archer
This has been done recently as part of the cold/flu and SL form launch and all the unused forms, submission, and workflows are cleaned up.

All the cleanup steps are clearly documented [here](https://github.com/bcgov/digital-journeys/blob/main/docs/cleanup-environment.md)

**Comment by Stella-Archer** [comment]
@Iman this looks good I'm noting the link and referencing it when we look at process improvement /documentation in special Sprint but closing this particular ticket - thanks, nice work!
