### ISSUE TITLE
Cold / Flu: We need a data dictionary for the Influenza database

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#986]
**User Story**
As both a front-end and back-end developer I need a guide to the fields available from retrieving and pushing data to and from the data warehouse so that I can build an effective data model and ensure that the field lengths and types are correct in type, name, and length. This will eliminate errors due to misunderstanding the nature of the fields in the database.

**Tasks**
- [x]  Create a spreadsheet (workbook) of all of the tables in the current influenza database with one sheet per table.
- [x]  List the fields in each table
- [x] the field type
- [x] create a description (what it is, and purpose)
- [x] Form team vets content (specify members in the comments below)
- [x] Vet this dictionary with the data currently in the database. 

**Acceptance Criteria**
- [x] Don (author) vets content
- [x] Caleb vets content
- [x] Iman vets content

The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by DonMoffatt** [comment]
I created the first draft of the data dictionary and sent it to Archer, Stella Anne PSA:EX <StellaAnne.Archer@gov.bc.ca>; Noorizadeh-Kollou, Nassreen PSA:EX <Nassreen.Noorizadeh-Kollou@gov.bc.ca>; Liu, Caleb PSA:EX <Caleb.Liu@gov.bc.ca>; 'bhumin.patel1@ca.ey.com'; Ramirez, Eduardo PSA:EX <Eduardo.Ramirez@gov.bc.ca>; Caldwell, Chris PSA:EX <Chris.Caldwell@gov.bc.ca>

It is over to your side to review this and discuss next steps with me. I suggest creating a data model from this to show the relationships between the tables and fields.

**Comment by EduardoRamirezBC** [comment]
Bhumin to reach out Patrick/Don about the end points.

**Comment by ca-liu** [comment]
@mikeshi-bcgov  here is the ERD (V6)

**Comment by mikeshi-bcgov** [comment]
@ca-liu Thanks

**Comment by DonMoffatt** [comment]
We have finalized table and field names but are still adjusting some field lengths, e.g. first_name, last_name to bring them into line with PeopleSoft.

**Comment by DonMoffatt** [comment]
Don is waiting on @mikeshi-bcgov for word that he has completed changes to the tables/fields. Don will complete the final version of the data dictionary by making updates.

**Comment by DonMoffatt** [comment]
Thanks @mikeshi-bcgov: are the fields stable now in terms of type? i.e. is it safe for me to update the documentation?

**Comment by mikeshi-bcgov** [comment]
@DonMoffatt 
Thanks, I would say yes it is safe for now-:)) unless it is asked to adjust from Form developer side.

**Comment by DonMoffatt** [comment]
Almost done: @ca-liu would you please look at the worksites and registration tables and put in short definitions for the few fields there where I have question marks? Also @EduardoRamirezBC  would you like to have a look at https://bcgov.sharepoint.com/:x:/r/teams/03991/Shared%20Documents/Cold%20and%20Flu/3_Design/DD_Influenza_db.xlsx?d=w6314fb159a6b4b2290da8b34af8e6820&csf=1&web=1&e=tOsFbpit? It is located here:

**Comment by ca-liu** [comment]
Hey @DonMoffatt  - thanks for the update! I've added my comments to the dictionary. 

I am not sure about application_id, I think this perhaps is a duplication of registrations_id

**Comment by DonMoffatt** [comment]
Hello @mikeshi-bcgov do we need the application_id in the registrations table? Did add that? We don't have a definition of what it does.

**Comment by mikeshi-bcgov** [comment]
@DonMoffatt 

To add application_id to 2 tables was requested by Bhumin, please refer to task #1000

**Comment by ca-liu** [comment]
Hey @mikeshi-bcgov

I believe the application_id reference din ticket #1000 by Bhuman is the same as registration_id. It is the primary key for the registrations table.

I think Bhuman got it from your POST call example, 🙂
![image.png](https://images.zenhubusercontent.com/63d039ffe477f5df944dbc73/b10f498f-7982-47a6-9f9b-ade134aa7dba)

Hey @iman-jamali-fw for consistent variable naming and to ensure that the id is captured in the backend, could we please update the variable on the FE from application_id to registration_id?

Here is a copy of our [ERD](https://app.zenhub.com/files/439477060/61d84370-1611-4d3c-b40e-fba7e47c3016/download) for your reference (final copy - naming convention changes - to be produced)

Thank you both!

**Comment by DonMoffatt** [comment]
Hi @ca-liu - to be clear, can I drop application_id from the data dictionary?

**Comment by ca-liu** [comment]
> Hi @ca-liu - to be clear, can I drop application_id from the data dictionary? 

Hey @DonMoffatt,

Yes, I think we can drop application_id from the data dictionary.

Just to double check, I'll bring this up at stand-up on Monday for Iman to take a look at the Front End code to make sure that it is a duplicate then we can drop it.

Thanks!

**Comment by mikeshi-bcgov** [comment]
@ca-liu 
the request for application_id is actually before I have shared the post example [#1000](https://github.com/bcgov/digital-journeys/issues/1000#issuecomment-1505730228)

Possibly Bhumin was referencing the same thing, sure need to confirm with them

**Comment by ca-liu** [comment]
> @ca-liu 
> the request for application_id is actually before I have shared the post example [#1000](https://github.com/bcgov/digital-journeys/issues/1000#issuecomment-1505730228)
> 
> Possibly Bhumin was referencing the same thing, sure need to confirm with them

Thank you for the clarification, @mikeshi-bcgov!

Good morning @iman-jamali-fw,

When you get a chance, could you please confirm that application_id and registration_id are the same and that we can change it to registration_id for consistent naming?

Thank you for your help!

**Comment by iman-jamali-fw** [comment]
@ca-liu 
Sure I'll look into it today. I know that `application_id` is the id of submission, not sure if we can rename it.

**Comment by iman-jamali-fw** [comment]
@ca-liu 

I don't think we can merge `application_id` and `registration_id`. They're the primary keys of two different tables one in DGJ and another in the warehouse. I think we should keep both on the registration table.

**Comment by ca-liu** [comment]
> @ca-liu 
> 
> I don't think we can merge `application_id` and `registration_id`. They're the primary keys of two different tables one in DGJ and another in the warehouse. I think we should keep both on the registration table.

Thanks @iman-jamali-fw! That makes sense to me. 

Hey @DonMoffatt, @mikeshi-bcgov 

We can keep `application_id` in the registrations table. This is the form Id generated by FormsFlow and we'll need it to retrieve people's submitted forms (for editting).

Thanks everyone!

**Comment by DonMoffatt** [comment]
Hello @mikeshi-bcgov @iman-jamali-fw I am finalizing the data dictionary and noticed that in the db on dev we have a mismatch between the variable definitions for application_id and what we have in the data dictionary. In the data dictionary we have 
application_id	string		not null	This is the primary key for FormsFlow from each form.	
and in the db we have: 
application_id int null

Which should it be?

**Comment by iman-jamali-fw** [comment]
@DonMoffatt 

It's converted from `int` (in formio) to `string` in Camunda, so `string` will be sent to the warehouse in post/put requests. Please convert it to `string` if that's not too hard. Thank you

**Comment by DonMoffatt** [comment]
@AbhimanyuRaut There is no string type available. I made it varchar(50) with nulls allowed. Is that ok?

**Comment by DonMoffatt** [comment]
Hello @ca-liu @mikeshi-bcgov and @iman-jamali-fw : I have updated the data dictionary on team share and brought it into alignment with what is in the data warehouse in DEV. Iman and Caleb, would you please have a look and if you are satisfied would you tick the boxes above under "Acceptance Criteria" for your respective confirmations and let me know? Caleb, please compare it to the naming in your ERD.  As noted in my previous comment I changed application_id to int (it was already int in one table).

**Comment by DonMoffatt** [comment]
I've also taken Eduardo and Nass off the approval list for the data dictionary: Nass has not been involved with this part of the project and having Eduardo on as an approver was a mistake on my part: I just wanted him to be aware of it for informational purposes for future, similar projects.

**Comment by ca-liu** [comment]
Hey @iman-jamali-fw  (for @bhumin-fw), @mikeshi-bcgov  (cc: @DonMoffatt)

I noticed that there is `application_id` included in the worksite_ministries table. I am going to assume that this was added in error - there is no relationship between the individual registrations and the bridge table.

the registrations will house the `wm_id`, the worksite_ministries table does not / cannot store `application_id` as a record or else a many-to-many scenario is created.

Could you please confirm this? Once confirmed, I will send out a final ERD to the team.

Thanks all!

**Comment by iman-jamali-fw** [comment]
@ca-liu 

I think that's an error. `application_id` should only be added to the registration table if I understand the schema correctly. Maybe @bhumin-fw can confirm.

**Comment by bhumin-fw** [comment]
@DonMoffatt 
For sure. 
application_id should be there in worksite and registration table only. 
As we are having 2 work flow, add worksite-registration and add registration to existing worksite.

**Comment by DonMoffatt** [comment]
Hi @bhumin-fw - I think your note is opposite to what @ca-liu and @iman-jamali-fw said. They said it should only be in the registration but you said it should be in worksite and registration. Just to confirm, are they wrong? It needs to be in both? Can you explain why it needs to be in both?

**Comment by ca-liu** [comment]
> @DonMoffatt 
> For sure. 
> application_id should be there in worksite and registration table only. 
> As we are having 2 work flow, add worksite-registration and add registration to existing worksite.

Hey @bhumin-fw , can you help me understand why we are adding `application_id` to worksites? There can be multiple applications / registrations in one worksite address.

**Comment by bhumin-fw** [comment]
@DonMoffatt @ca-liu 

We have 2 table worksite and registration.

**Case 1: add/update worksite and registration**
On the digital journey side we have form with worksite and registration details.
When we submit form, we will have unique ID (Application_id), and data includes of both table worksite and registrations.
Let's say I did click on edit form on Digital Journey, It will show me full form with same data that I did submit (worksite + registration). So having application_id in worksite and registration table help on ODS endpoint to update both table respectively with updated details.

**Case 2: Add/update only registration in existing worksite.**
Now let's take other path, we have new form where we want to add only registration on existing worksite.
In this case digital journey form only contain registration related fields and worksite_id. So in this case new registration saved with application_id.
In case of edit same submission on digital journey. It will only allow you to update registration related fields.

We do not need application_id in worksite_ministries table(one of Caleb's message about asking for it). 
or any other table except `worksite` and `registration`.

**Comment by ca-liu** [comment]
> @DonMoffatt @ca-liu 
> 
> We have 2 table worksite and registration.
> 
> **Case 1: add/update worksite and registration**
> On the digital journey side we have form with worksite and registration details.
> When we submit form, we will have unique ID (Application_id), and data includes of both table worksite and registrations.
> Let's say I did click on edit form on Digital Journey, It will show me full form with same data that I did submit (worksite + registration). So having application_id in worksite and registration table help on ODS endpoint to update both table respectively with updated details.
> 
> **Case 2: Add/update only registration in existing worksite.**
> Now let's take other path, we have new form where we want to add only registration on existing worksite.
> In this case digital journey form only contain registration related fields and worksite_id. So in this case new registration saved with application_id.
> In case of edit same submission on digital journey. It will only allow you to update registration related fields.
> 
> We do not need application_id in worksite_ministries table(one of Caleb's message about asking for it). 
> or any other table except `worksite` and `registration`.

Hey @bhumin-fw - do you have 10 - 15 mins for a quick chat? I don't think I follow the scenarios described above.

Thanks!

**Comment by bhumin-fw** [comment]
@ca-liu I have one bank appointment at 3:30pm, so need to leave for that. mostly I will be available by 4:30pm onwords.
Does that works for you?
If yes please share meeting invite with me so we can connect at 4:30pm or anytime after that for a quick call.

**Comment by ca-liu** [comment]
> @ca-liu I have one bank appointment at 3:30pm, so need to leave for that. mostly I will be available by 4:30pm onwords.
> Does that works for you?
> If yes please share meeting invite with me so we can connect at 4:30pm or anytime after that for a quick call.

Thanks @bhumin-fw. I'll book a quick meeting with you at 4:30 - 4:45PM.

**Comment by bhumin-fw** [comment]
@ca-liu Sure. Please share meeting invite on teams for the same. find my ms teams email below.
bhumin.patel1@ca.ey.com

**Comment by ca-liu** [comment]
sorry @bhumin-fw - I selected the wrong date. 

If you are free

<div style="margin-top:18.0pt;margin-bottom:15.0pt">
<p class="MsoNormal"><span style="font-size:18.0pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">Microsoft Teams meeting</span><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">
</span></p>
</div>
<div style="margin-bottom:15.0pt">
<div>
<p class="MsoNormal"><b><span style="font-size:10.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">Join on your computer, mobile app or room device</span></b><b><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">
</span></b></p>
</div>
<p class="MsoNormal"><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424"><a href="https://teams.microsoft.com/l/meetup-join/19%3ameeting_MjI3MGMxNjAtMjk0NS00NDgzLWI5ZDQtNTVmNGFmNzU2NDI2%40thread.v2/0?context=%7b%22Tid%22%3a%226fdb5200-3d0d-4a8a-b036-d3685e359adc%22%2c%22Oid%22%3a%2230731348-01c0-4708-90aa-a56c2c9e2741%22%7d"><span style="font-size:10.5pt;font-family:&quot;Segoe UI Semibold&quot;,sans-serif;color:#6264A7">Click
 here to join the meeting</span></a> </span></p>
</div>
<div style="margin-top:15.0pt;margin-bottom:15.0pt">
<div style="margin-bottom:3.0pt">
<p class="MsoNormal"><span style="font-size:10.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">Meeting ID:
</span><span style="font-size:12.0pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">284 525 300 856</span><span style="font-size:10.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">
</span><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424"><br>
</span><span style="font-size:10.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">Passcode:
</span><span style="font-size:12.0pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">nKi6Nu
</span><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424"></span></p>
<div>
<p class="MsoNormal"><span style="font-size:10.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424"><a href="https://www.microsoft.com/en-us/microsoft-teams/download-app"><span style="color:#6264A7">Download Teams</span></a> |
<a href="https://www.microsoft.com/microsoft-teams/join-a-meeting">
<span style="color:#6264A7">Join on the web</span></a></span></p>
</div>
</div>
</div>
<div style="margin-bottom:3.0pt">
<div style="margin-bottom:3.0pt">
<p class="MsoNormal"><b><span style="font-size:10.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">Or call in (audio only)</span></b><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">
</span></p>
</div>
<div style="margin-bottom:3.0pt">
<p class="MsoNormal"><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424"><a href="tel:+17784016289,,223267143#"><span style="font-size:10.5pt;color:#6264A7">+1 778-401-6289,,223267143#</span></a>
</span><span style="font-size:10.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">&nbsp; Canada, Victoria
</span><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424"></span></p>
</div>
</div>
<p class="MsoNormal"><span style="font-size:10.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">Phone Conference ID:
</span><span style="font-size:12.0pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">223 267 143#
</span><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424"></span></p>
<div style="margin-bottom:15.0pt">
<p class="MsoNormal"><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424"><a href="https://dialin.teams.microsoft.com/1d2ee6b0-0212-4b1a-bc91-f2c7e4ecc3be?id=223267143"><span style="font-size:10.5pt;color:#6264A7">Find a local number</span></a>
 | <a href="https://dialin.teams.microsoft.com/usp/pstnconferencing">
<span style="font-size:10.5pt;color:#6264A7">Reset PIN</span></a> </span></p>
</div>
<div style="margin-bottom:3.0pt">
<p class="MsoNormal"><span style="font-size:10.5pt;font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424">Toll-free (audio only): 1-888-600-3289
</span></p>
</div>
<div style="margin-top:15.0pt;margin-bottom:18.0pt">
<p class="MsoNormal"><span style="font-family:&quot;Segoe UI&quot;,sans-serif;color:#252424"><a href="https://aka.ms/JoinTeamsMeeting"><span style="font-size:10.5pt;color:#6264A7">Learn More</span></a> |
<a href="https://teams.microsoft.com/meetingOptions/?organizerId=30731348-01c0-4708-90aa-a56c2c9e2741&amp;tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&amp;threadId=19_meeting_MjI3MGMxNjAtMjk0NS00NDgzLWI5ZDQtNTVmNGFmNzU2NDI2@thread.v2&amp;messageId=0&amp;language=en-US">
<span style="font-size:10.5pt;color:#6264A7">Meeting options</span></a> </span></p>
</div>

**Comment by DonMoffatt** [comment]
@ca-liu If you feel that you have the answer from bhumin please feel free to finish documenting that field and close this ticket. Thanks.

**Comment by mikeshi-bcgov** [comment]
@ca-liu 
Per discussion, to support soft deletion, a new field "deleted_ind"( tinynt(1) ) has been added to table registrations, you may want to update the ERD

**Comment by ca-liu** [comment]
@mikeshi-bcgov : wow! you're too fast!! 

Thank you so much :)

**Comment by ca-liu** [comment]
For: @mikeshi-bcgov  @bhumin-fw  @DonMoffatt @ccoldwell 
cc:  @EduardoRamirezBC  @NassNK  @Karla

Hi everyone,

To ensure consistent naming of the rows across all tables in the RDBMS, please note below name changes the database:

- `application_id `is removed from the worksite_ministries table
- `is_admin `is removed from the contacts table
- `date_updated `is now consistent in all tables (including registrations table)
- `deleted_ind `is added to the registrations table for soft delete

Kindly double check your input and output params to match the new names.

Platforms to check for check:
- MySQL
- MS SQL Server
- API endpoints
- Front end

Please let me know once your concerning platform has been updated with the new variable names and I will close out this ticket

Thanks everyone for your patience while we finalize this document.

Attachments:
ERD:
[https://app.zenhub.com/files/439477060/e7d81952-db87-48b1-be5f-747cf148e42f/download](https://app.zenhub.com/files/439477060/e7d81952-db87-48b1-be5f-747cf148e42f/download)

Data Dictionary
[https://app.zenhub.com/files/439477060/20ae0280-e916-497e-8083-79e37024012f/download](https://app.zenhub.com/files/439477060/20ae0280-e916-497e-8083-79e37024012f/download)

**Comment by DonMoffatt** [comment]
Hi @ca-liu and @iman-jamali-fw : when you are satisfied with data dictionary would you tick your respective boxes in the checklist on this ticket and let me know so I can close it?

**Comment by ca-liu** [comment]
Hey @DonMoffatt , thanks for checking in. I am good with the final data dictionary and ERD, I just want to make sure that the applications have been updated to reflect the final ERD. 

Should I tick off my box?

**Comment by iman-jamali-fw** [comment]
@ca-liu 

Looks good to me.

**Comment by ca-liu** [comment]
> @ca-liu 
> 
> Looks good to me.

Thanks for confirming, @iman-jamali-fw . I'm assuming that the variables in the FE / FormsFlow are in alignment with the table rows on the ERD?

**Comment by iman-jamali-fw** [comment]
As far as I know, they are.

**Comment by ca-liu** [comment]
Perfect!
