### ISSUE TITLE
Cold/Flu: A data model is needed

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#987]
**User Story**
As a front-end or back-end developer I need to understand how the fields and tables work together to ensure I am using them in the correct way to properly retrieve and store data, and to ensure that there is no duplication of fields.

**Tasks**
- [x] Initiate a model in Visio
- [x] Refer to the data dictionary previously created for guidance.
- [x] Show how the tables are connected.

**Acceptance Criteria**
- [x] Does the front end developer understand the relationships between the tables?
- [x] Does the back end developer understand the relationships between the tables?

**Comment by EduardoRamirezBC** [comment]
documentation needs updating.

**Comment by DonMoffatt** [comment]
The table and field names have been finalized.  We still need to complete the following:

- ensure that the ERD matches the final naming 
- ensure that field lengths and types are final
- ensure that the data dictionary is finalized.
- ensure that the aforementioned documentation (ERD and data dictionary) are stored with the other project documentation for future reference. 
- Bhumin / Mike should also supply API information for reference purposes.

**Comment by DonMoffatt** [comment]
We are waiting for Mike to let Don know the that the tables have been updated. Then we can complete the data dictionary and Caleb can complete the final version of the ERD.

**Comment by DonMoffatt** [comment]
We are waiting for Mike to let Don know the that the tables have been updated. Then we can complete the data dictionary and Caleb can complete the final version of the ERD.

**Comment by ca-liu** [comment]
Data model is completed. Pending verification from other applications that the variables are in sync with ERD_Final

**Comment by DonMoffatt** [comment]
Hi @ca-liu Is this ready to close?

**Comment by ca-liu** [comment]
Hey @DonMoffatt good to go from my end. Thanks!
