### ISSUE TITLE
Cold/Flu:  'Registered Clinics for this Worksite'

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#990]
**User Story**
“As a user registering a worksite, I want see all the clinics already registered at my worksite so I can contact and coordinate with colleagues who have already registered.” 

**Tasks**
* [ ] Create grid to contain data fields to be pulled from the DB
Columns:
- Worksite contact <Name>
- Ministry
- Type of Clinic
- Number of employees

* [ ] Logic: When a user selects a ministry and worksite from the drop down, check DB to see if the worksite already has a clinic registered 
- YES display grid populated with existing registration info (Display OPEN clinics ONLY)
- NO  continue to "clinic registration' 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/199fd9a9-32fb-4dc7-962e-fadeba5ed0b0)

**Acceptance Criteria**
* [ ] When a user selects a city and worksite, if a clinic has already be registered at that site, registration information is displayed.
* [ ]  the information display should be tabular allowing for one or many registration entries

**Comment by EduardoRamirezBC** [comment]
Meeting with Mike needed. Caleb/Stella.
Stella will setup.

**Comment by Stella-Archer** [comment]
waiting for API to Fill data

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
We need one API endpoint. which returns clinics/registrations filter by WorksiteID. Once schema fix please prepare this API endpoint on priority.
Please see ticket details for required keys in response for each clinics/registrations. 
(fields are Worksite Contact, Ministry, Type Of Clinic/Registration, Number of Employees)

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 
Sure Bhumin, I will bring this to the team in this afternoon's meeting, to see how to present these fields out of the new schema

**Comment by Stella-Archer** [comment]
Is #1000 blocking this?

**Comment by bhumin-fw** [comment]
@Stella-Archer 
yes #1000 blocking this ticket.

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_worksites/
https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_worksite_ministries/
Above API endpoints only give worksites list or mapping.

**We need below API endpoints:**
1. **Worksite list filter by provided ministry_id.**
(When we pass ministry_id in API endpoint it will only list worksites link to that ministry. Right now I have to fetch worksite ids and then have to trigger worksites API)

2. **Registrations based on provided worksiteID.**
- This API endpoint should accept worksite_id as filter in request and in response it should send registrations under selected worksites.
response should contain at-least below value
worksite-contact: String (name of primary contact)
registration-type: String (value of is_closed key from registration table which contain "open" & "closed" as value)
ministry: String (Name of registration's ministry)
number-of-employee: Int (number of employee value from registration table)

**FYI:** This is priority along side add/update registration API.

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
It did revert blank, do I need to pass filter here? or you are cleaning and reloading tables?
{'@odata.context': 'https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/$metadata#ods_datamart_influenza_vw_worksites_ministries_joined', 'value': []}

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
It did revert blank, do I need to pass filter here? or you are cleaning and reloading tables?
{'@odata.context': 'https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/$metadata#ods_datamart_influenza_vw_worksites_ministries_joined', 'value': []}

**Comment by EduardoRamirezBC** [comment]
Mike: the data was reloaded.

**Comment by EduardoRamirezBC** [comment]
@mikeshi-bcgov to add two entries for registration table.

**Comment by mikeshi-bcgov** [comment]
@EduardoRamirezBC 
Two dummy entries have been added to registrations table

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 

API EndPoint for the item requested #2 ( 2. Registrations based on provided worksiteID.) is available now as well, please test

 https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_vw_registrations_worksites_joined/

**Comment by iman-jamali-fw** [comment]
I'll test the endpoint today and update the ticket.

**Comment by MeghanStothers** [comment]
Dummy data in for and Iman to test the endpoint today

**Comment by iman-jamali-fw** [comment]
@mikeshi-bcgov 

The `https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_vw_registrations_worksites_joined` works great and I can see the registration items including the ones I sent last night. filter by `application_id` also works.

Thanks!

**Comment by chriscaldwell-psa** [comment]
@bhumin-fw  - Hi Bhumin, yes, let me know when we can connect today. Thanks C

**Comment by Stella-Archer** [comment]
@chriscaldwell-psa @bhumin-fw I'm looking for this in both DEV and TEST and don't see 'clinics at this worksite' populating is there a particular ministry/worksite combo I need to query to see the test data?

**Comment by bhumin-fw** [comment]
@Stella-Archer 
try below combination.
![Screenshot 2023-04-27 at 3.52.02 PM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/251d3a86-9eed-4126-9481-222ac8f80976)

**Comment by Stella-Archer** [comment]
Thanks @bhumin-fw oddly enough that did not work for me :(
TEST
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/97588318-00f4-4c4b-9d5c-ce0364b08fbb)
DEV
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/107d73e8-21c0-4210-89ca-8378d6064874)

**Comment by ayushdamani** [comment]
Hey @bhumin-fw ,
I tested this in Test and Dev and it didn't work out for me either.

Test 
![test.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/fd6a1f0f-fed6-4f88-8bdc-13dbdee0e55f)

Dev
![dev.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/ff2e3d61-f680-4ce5-af9b-3917f34cfbcc)

**Comment by Stella-Archer** [comment]
this work great, PO approved and closing this ticket
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/802e17fd-f409-49cf-b397-caaad2112377)
