### ISSUE TITLE
Cold/Flu: Landing Page (Dropdowns)

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#994]
**User Story**
As a user wanting to register my worksite for a clinic, I want to easily find my correct worksite so I can register and be confident I have Identified the right site.

**Tasks**
* [x] under the instructions add a drop down box for:
  * [ ]  Ministry
  * [ ]  City (requires logic)
  * [ ]  Worksite (requires logic)
* [ ] Connect drop down lists to correct data set in DB
* [ ] City Logic: onChange (Ministry input), the city should only display cities under specified Ministry
* [ ] Worksite Logic: onChange the following will occur (ref #990):
  * [ ]  "Registered Clinics for this Worksite" table should appear 
  * [ ] "Don't see your worksite" should hide / disappear
  * [ ] Registered clinics table should only show if the clinic is OPEN. Closed clinics are not pool-able

![image.png](https://images.zenhubusercontent.com/63d039ffe477f5df944dbc73/5cd06265-201d-4d92-8117-7d19499af1ab)

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by EduardoRamirezBC** [comment]
@DonMoffatt How do we connect City/Worksite to your database

**Comment by EduardoRamirezBC** [comment]
The field IDs are being developed in
ticket 1000

**Comment by ca-liu** [comment]
![image.png](https://images.zenhubusercontent.com/63d039ffe477f5df944dbc73/c6ac7a4c-3d04-4638-b09b-44fe458a0102)

Revised dropdown to include Ministry on Screen 1: Landing Page
