### ISSUE TITLE
Cold/Flu: Create tickets

### ISSUE THREAD

**Issue by EduardoRamirezBC** [bcgov/digital-journeys#995]
**User Story**

“As a scrum team member in the Cold / Flu form project I want to create detailed tickets as soon as possible so I can start work on the form and have them ready for Thursday's backlog refinement/grooming.” 

**Tasks**

 - [x] enter detailed information.
 - [ ] confirm it's granular enough to be able to complete in a sprint (3 weeks)
 - [ ] label ticket using the Cold / Flu tag

**Acceptance Criteria**

 - [ ] The board is populated with enough tickets to get the work started
 - [ ] The tickets reflect the work ahead for this week (March 28th)
 - [ ] The tickets reflect the work ahead for the next sprint (March 29th - April 20th)

**Comment by Stella-Archer** [comment]
we did write tix = YAY
