### ISSUE TITLE
Cold/Flu: Registering a clinic at an EXISTING worksite (Front end) 

### ISSUE THREAD

**Issue by NassNK** [bcgov/digital-journeys#999]
**User Story**
“As a user wanting to register my worksite for a clinic, I did find my worksite listed but I have reasons to register our team as a separate clinic”

**Tasks**
* [x] Heading section “ 2023 Influenza Worksite Registration” 
* [x] Instructions text box: “You have chosen this option because your worksite was listed and you didn't find your registration/clinic ”                                            (updated on May 2/2023)
* [x]  Section Divider ( this has been implemented by using panels)
* [x]  Worksite Information fields will prepopulate based on the dataset in the DB and are not editable. 
* [x]  Section Divider
* [x]  Worksite Contact fields: First Name, Last Name, Area Code, Phone Number, Ext, Email Address
These fields are all text box fields and should have an asterisk to indicate that they are   mandatory to complete. 
* [x]  Section Divider
* [ ]  Secondary Worksite Contact fields: First Name, Last Name, Area Code, Phone Number, Ext, Email Address
These fields are all text box fields.
* [x]  Section Divider
* [x]  Text box field “ Number of Employees at Worksite
	This field should have an asterisk to indicate it is mandatory and the logic should be control to a 	 value entry only. 
* [x]  Dropdown options “ Open/Closed” with description “ Is this an open or closed clinic?” 
* [x]  Dropdown options “ Yes/No” with description “Will the team be relocating?” 
* [x]  Text box field “ Special Instructions”  
* [x]  Section Divider

* [x]  Action Button “Submit”

**Acceptance Criteria**
Once all mandatory fields are completed, the user clicks submit to complete the clinic registration for an existing worksite.

**Comment by NassNK** [comment]
![Seperate clinic.jpg](https://images.zenhubusercontent.com/62aa1d72cf0550d16362c78a/69fe1ca1-73d3-4b0d-8608-a315dd20989f)

**Comment by NassNK** [comment]
![image.png](https://images.zenhubusercontent.com/62aa1d72cf0550d16362c78a/a63d292a-a8ec-48b9-bd04-92cd41cecd53)

**Comment by ayushdamani** [comment]
Tested and verified:
- Checked the above listed points.
- I was able to submit the form, once the mandatory fields were completed.

Acceptance criteria met ✔️

**Comment by chriscaldwell-psa** [comment]
Made some updates to an info panel, added an info panel - Bhumin will add logic to the new component today or tomorrow. Tested to see if the data pulled correctly, I was successful this time and did not encounter any error messages.

**Comment by Abuchana** [comment]
@Stella-Archer Ayush tested, over to you for PO review

**Comment by Stella-Archer** [comment]
questions about pop up component #1054

**Comment by bhumin-fw** [comment]
@Stella-Archer 
As per the latest comment from Heather, we need to show info box with visible text.

> Event: User reaches the Worksite Secondary Contact field
> Add: Please include visible text (perhaps another info box like above)
> “To help ensure your team gets the information they need, please include secondary contact information as back up for your work area."

**Comment by Stella-Archer** [comment]
This looks really good now, I have 2 small points:
1/ The "Don't see your registration" button doesn't make sense to me as I'm just coming in to register a clinic at my work site I think it would make more sense if the button was more precise and said "Register a clinic at your work site"
2/ the "You have chosen this option because your **worksite was not listed** or you didn't find your registration/clinic" doesn't make sense because we ARE in a space where the worksite is registered and we are just trying to book a clinic for this Chris has said this is in the works to change so won't dwell on it. 
PO approved and closing tix will make new tickets for the above points if necessary 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/42d5a5ef-aded-48de-8e46-8f5e167b2038)
PO approve & closing

**Comment by Stella-Archer** [comment]
I've checked in with Heather and have her approval to close
